### ISSUE TITLE
求指导，vmess配置

### ISSUE THREAD

**Issue by joshatt** [MetaCubeX/Clash.Meta#113]
```
proxies:
 - name: 11
   .....

 - name: 22
   .....

 # vmess
  # cipher支持 auto/aes-128-gcm/chacha20-poly1305/none
  - name: 33
    type: vmess
    server: server
    port: 443
    uuid: a40d34*******
    alterId: 16
    cipher: auto
    # udp: true
    tls: true
    # skip-cert-verify: true
    # servername: example.com # priority over wss host
    network: ws
    ws-opts:
       path: /op******
       headers:
        Host: ********
    #   max-early-data: 2048
    #   early-data-header-name: Sec-WebSocket-Protocol

proxy-groups:
  ......

rules:
  ......
```

以上配置， 本来能用，然后今天添加了vmess这个部分（带星号的是我个性化的内容），无法导入，提示第一行缺少“-”。然后我尝试注释掉ws-opts或headers， 无效

求指点
