### ISSUE TITLE
[求助]为啥照抄的配置也不行哈~~

### ISSUE THREAD

**Issue by jsjcjsjc** [MetaCubeX/Clash.Meta#116]
这是自己写的,已经很简单了~~但是导入啥也没有,应该是不兼容
都没到哪里出问题的地步,配置文件导入就有点问题,
```
proxies:
  - name: hysteria
    type: hysteria
    server: 1.1.1.1
    port: 443
    auth_str: yourpassword
    alpn: h3
    protocol: udp
    up: 30
    down: 200
    skip-cert-verify: true

proxy-groups:                       
  - name: proxy
    type: select
    proxies:
      - hysteria   

rules:
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,geolocation-!cn,proxy
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,cn,DIRECT
  - MATCH,proxy
```
这是照抄官网的,导入也是啥也没有...
这是哪里除了问题哈...
```
proxies:
  - name: "hysteria"
    type: hysteria
    server: server.com
    port: 443
    auth_str: yourpassword
    alpn: h3
    protocol: udp
    up: '30 Mbps'
    down: '200 Mbps'

proxy-groups:                       
  - name: proxy
    type: select
    proxies:
      - hysteria   

rules:
  - GEOSITE,geolocation-cn,DIRECT
  - GEOSITE,geolocation-!cn,proxy
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,cn,DIRECT
  - MATCH,proxy
 ```
