### ISSUE TITLE
希望 dns-hijack 增加对 TCP 类型的 DNS 支持

### ISSUE THREAD

**Issue by yaohappiness** [MetaCubeX/Clash.Meta#137]
以下配置，在 Clash Premium Core 可以正常截获 TCP 类型的 DNS 查询，希望 Meta 也能支持。

```yaml
tun:
  enable: true
  stack: system
  dns-hijack:
    #- 198.18.0.2:53
    #- 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-detect-interface: true
```
