### ISSUE TITLE
TUN 模式下无法代理 ip 请求，所有 ip 请求不经过内核直连

### ISSUE THREAD

**Issue by lyaaz** [MetaCubeX/Clash.Meta#187]
dns 及 tun 相关配置如下：
```yaml
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
    - '+.apple.com'

  port-whitelist:
  - 80
  - 443

dns:
  enable: true
  listen: 127.0.0.1:1053
  ipv6: false
  use-host: true
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://doh.pub/dns-query
    - https://223.5.5.5/dns-query
  fallback:
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - quic://a.passcloud.xyz:784
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - geolocation-!cn
    ipcidr:
      - 240.0.0.0/4
  fake-ip-filter:
    - "*.lan"
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - time.windows.com
```

```yaml
tun:
  enable: true
  device: meta
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
```
