### ISSUE TITLE
Tun模式下的Office/UWP无法联网的问题

### ISSUE THREAD

**Issue by FlyMeToTheMars** [MetaCubeX/Clash.Meta#188]
# 如何根治Tun模式下Office/UWP无法联网的问题
找了很多方法，也没法解决，在这提前给大佬磕头了

## 问题描述
目前就是Todo/便签/Office 365啥的Tun模式下连不上网络，需要关掉代理才能联网。Tun模式应该是不用在意什么LookBack回环的吧（我打开关闭都试过，目前是关闭状态），CFW啥的issue能找的我基本都翻了一遍，没有解决问题。官方文档也翻了翻，仍然没有解决(自己计算机网络这块比较菜)。感觉Clash现在对新手不是很友好了，tun minix tap 啥的，晕晕乎乎的。
## 环境
客户端用的是Clash-verge（Meta core 1.13.1），系统Win11
## 配置文件
```
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
dns:
  enable: true
  use-hosts: true
  ipv6: false
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:6868
  default-nameserver:
    - 119.29.29.29
    - 114.114.114.114
  nameserver:
    - https://doh.pub/dns-query
    - tls://223.5.5.5:853
  fallback:
    - tls://dns.google:853
    - tls://1.1.1.1:853
  fallback-filter:
    geoip: false
    geosite:
      - cn
    domain:
      - +.example.com
    ipcidr:
      - 0.0.0.0/32
# Enable the TUN listener
tun:
  enable: true
  stack: gvisor #  only gvisor
  dns-hijack: 
    - 0.0.0.0:53 # additional dns server listen on TUN
  auto-route: true # auto set global route
```
## 日志
```
09-16 17:41:07INFO[TCP] 198.18.0.1:9781(EXCEL.EXE) --> substrate.office.com:443 match DomainSuffix(office.com) using Ⓜ️ 微软服务[DIRECT]
09-16 17:41:12INFO[TCP] 198.18.0.1:9785(msedge.exe) --> api.twitter.com:443 match DomainSuffix(twitter.com) using 🔰 节点选择[KoreaBuild]
09-16 17:41:12INFO[TCP] 198.18.0.1:9793(Skype.exe) --> azwcus1-client-s.gateway.messenger.live.com:443 match DomainSuffix(live.com) using Ⓜ️ 微软服务[DIRECT]
09-16 17:41:12INFO[TCP] 198.18.0.1:9790(Skype.exe) --> azwcus1-client-s.gateway.messenger.live.com:443 match DomainSuffix(live.com) using Ⓜ️ 微软服务[DIRECT]
09-16 17:41:12INFO[TCP] 198.18.0.1:9791(Skype.exe) --> azwcus1-client-s.gateway.messenger.live.com:443 match DomainSuffix(live.com) using Ⓜ️ 微软服务[DIRECT]
09-16 17:41:12INFO[TCP] 198.18.0.1:9792(Skype.exe) --> azwcus1-client-s.gateway.messenger.live.com:443 match DomainSuffix(live.com) using Ⓜ️ 微软服务[DIRECT]
09-16 17:41:13INFO[TCP] 198.18.0.1:9801 --> data.bilibili.com:443 match GeoIP(cn) using DIRECT
09-16 17:41:13INFO[TCP] 198.18.0.1:9799 --> data.bilibili.com:443 match GeoIP(cn) using DIRECT
09-16 17:41:13INFO[TCP] 198.18.0.1:9798 --> data.bilibili.com:443 match GeoIP(cn) using DIRECT
09-16 17:41:13INFO[TCP] 198.18.0.1:9800 --> data.bilibili.com:443 match GeoIP(cn) using DIRECT
09-16 17:41:16INFO[TCP] 198.18.0.1:9811(EXCEL.EXE) --> self.events.data.microsoft.com:443 match DomainKeyword(microsoft) using Ⓜ️ 微软服务[DIRECT]
09-16 17:41:18WARNING[TCP] dial DIRECT (match GeoIP(cn)) to 111.196.67.43:7680 error: dual stack tcp shake hands failed
09-16 17:41:18INFO[TCP] 198.18.0.1:9813(FileCoAuth.exe) --> self.events.data.microsoft.com:443 match DomainKeyword(microsoft) using Ⓜ️ 微软服务[DIRECT]
09-16 17:41:20INFO[TCP] 198.18.0.1:9815(EXCEL.EXE) --> uci.cdn.office.net:443 match DomainSuffix(office.net) using Ⓜ️ 微软服务[DIRECT]
09-16 17:41:27WARNING[TCP] dial DIRECT (match GeoIP(cn)) to 124.238.5.42:7680 error: dual stack tcp shake hands failed
09-16 17:41:37WARNING[TCP] dial DIRECT (match GeoIP(cn)) to 113.89.82.198:7680 error: dual stack tcp shake hands failed
09-16 17:41:40WARNING[TCP] dial DIRECT (match GeoIP(cn)) to 120.229.54.44:7680 error: dual stack tcp shake hands failed
09-16 17:41:48INFO[TCP] 198.18.0.1:9836 --> 123.151.190.252:8080 match GeoIP(cn) using DIRECT
09-16 17:41:52INFO[TCP] 198.18.0.1:9840(Todo.exe) --> substrate.office.com:443 match DomainSuffix(office.com) using Ⓜ️ 微软服务[DIRECT]
09-16 17:41:55WARNING[TCP] dial DIRECT (match GeoIP(cn)) to 183.233.228.178:7680 error: dial tcp4 192.168.1.5:0->183.233.228.178:7680: connectex: No connection could be made because the target machine actively refused it.
09-16 17:42:04INFO[TCP] 198.18.0.1:9848(Todo.exe) --> mobile.pipe.aria.microsoft.com:443 match DomainKeyword(microsoft) using Ⓜ️ 微软服务[DIRECT]
```

从日志里面已经可以看到流量走了微软，微软在外面设置的是Direct，但是没有成功建立连接，找不到原因。
我在外面开的是Tun模式 和服务模式，没有打开系统代理。

感恩

### 补充
系统右下角始终是没有连上网络的状态，浏览器对http://www.msftconnecttest.com/的访问结果是404 page not found，我感觉导致office没有连接的直接原因应该就是这个。
