### ISSUE TITLE
hysteria配置：'alpn' is not a slice

### ISSUE THREAD

**Issue by jinzhongjia** [MetaCubeX/Clash.Meta#216]
```yaml
    #【Meta专属】Hysteria
  - name: "hysteria"
    type: hysteria
    server: ****
    port: ****
    auth_str: ****
    #obfs: yourpassword
    alpn: h3
    protocol: udp          #支持udp/wechat-video/faketcp
    up: '12 Mbps'          #若不写单位，默认为Mbps
    down: '62 Mbps'       #若不写单位，默认为Mbps
    #sni: server.com
    #skip-cert-verify: false
    recv_window_conn: 6291456
    recv_window: 25165824
    #ca: "./my.ca"
    #ca_str: "xyz"
    disable_mtu_discovery: true
```

配置是按照官网的抄的，检查的时候会反馈
'alpn' is not a slice
