### ISSUE TITLE
websocket 0-rtt 配置无效

### ISSUE THREAD

**Issue by escapezn** [MetaCubeX/Clash.Meta#224]
服务端是xray1.6.0，clash配置了ws early data不能起到减少rtt的作用。使用xray作为客户端连接，带有?ed=2048参数的配置测试延迟比不带的少1个rtt
![1](https://user-images.githubusercontent.com/30799958/212556721-0f77c0e8-96e9-415d-aef2-98c079138004.png)

clash配置
```
  - name: "ssgr"
    type: ss
    server: 
    port: 80
    cipher: aes-128-gcm
    password: 
    udp: true
    udp-over-tcp: true
    plugin: v2ray-plugin
    plugin-opts:
      mode: websocket # no QUIC now
      tls: false
      host: 
      path: "/path?ed=2048"
      mux: false
      # headers:
      #   custom: value

  - name: "socks"
    type: socks5
    server: 127.0.0.1
    port: 2080
    udp: true
```
xray配置
![2](https://user-images.githubusercontent.com/30799958/212556714-c00f3651-ae27-4565-8e04-b0a6bf7b1dc1.png)

**Comment by malikshi** [comment]
Did you try with headers options? Is work?
    headers:
      Host: hostname
      max-early-data: 2048
      early-data-header-name: Sec-WebSocket-Protocol
  udp: true

**Comment by escapezn** [comment]
> Did you try with headers options? Is work?
> 
> ```
>     headers:
>       Host: hostname
>       max-early-data: 2048
>       early-data-header-name: Sec-WebSocket-Protocol
> ```


原版clash文档记载的两种写法，一开始就写的上面这种，都没有用
```
proxies:
# for v2fly and xray (recommand)
  - name: "vmess-ws-0rtt"
    type: vmess
    server: server
    port: 443
    uuid: uuid
    alterId: 32
    cipher: auto
    network: ws
    ws-opts:
      path: /
      max-early-data: 2048
      early-data-header-name: Sec-WebSocket-Protocol
# for xray compatible (not recommended)
  - name: "vmess-ws-0rtt"
    type: vmess
    server: server
    port: 443
    uuid: uuid
    alterId: 32
    cipher: auto
    network: ws
    ## also work for xray
    # ws-opts:
    #  path: /
    #  max-early-data: 2048
    #  early-data-header-name: Sec-WebSocket-Protocol
    ws-opts:
      path: /?ed=2048
```
