### ISSUE TITLE
新的alpha内核无法自动测速。

### ISSUE THREAD

**Issue by eightsheep67** [MetaCubeX/Clash.Meta#232]
alpha-b9d8b69版本的内核 更新后，节点连接正常，但在控制面板发现 所有的节点没有延迟信息，只能手动点击测速才有，而且不会自动更新，修改interval也没有用，那这样url-test不就失效了吗？

**Comment by ArchGuyWu** [comment]
@eightsheep67 其实是测了延迟的，应该是面板显示的问题

**Comment by eightsheep67** [comment]
> @eightsheep67 其实是测了延迟的，应该是面板显示的问题

但是我实际看了下下面的选择策略，就是万年不变的第一个节，应该是url-test失效了。

**Comment by wwqgtxx** [comment]
@eightsheep67 你该url-test组在interval时间内有新建连接过么，如果该组一直未被使用，的确不会触发urltest，除非你手动设置`lazy: false`，这是原版clash就有的特性

**Comment by eightsheep67** [comment]
>
> @eightsheep67 你该url-test组在interval时间内有新建连接过么，如果该组一直未被使用，的确不会触发urltest，除非你手动设置`lazy: false`，这是原版clash就有的特性
我有四个url-test组，都分配了规则去使用，所有新建的连接都是连组里第一个，不再变化了。
希望大佬帮忙看看哪里出了问题，等下一个alpha修复更新了。

**Comment by wwqgtxx** [comment]
@eightsheep67 你先尝试为四个组都加上`lazy: false`后是否能正常触发自动测试延迟

**Comment by eightsheep67** [comment]
> 

可以了，谢谢大佬，看来是因为新版本内核的默认参数是lazy: true，但是我的组都是正常、高频使用的。为何会触发lazy。

**Comment by wwqgtxx** [comment]
目前的代码逻辑在lazy开启的情况下，如果在interval时间内该组有过一次新建连接，那就会正常进行urltest，否则就顺延到下一个interval时间再重复前面的逻辑，是否是你interval的时间设置的过长或者过短导致了这段逻辑不能正常工作呢

**Comment by eightsheep67** [comment]
> 目前的代码逻辑在lazy开启的情况下，如果在interval时间内该组有过一次新建连接，那就会正常进行urltest，否则就顺延到下一个interval时间再重复前面的逻辑，是否是你interval的时间设置的过长或者过短导致了这段逻辑不能正常工作呢

我原先设置的interval是10，今天更新完发现问题我也想是不是设置太短了，就改成了60、120，都没有用。

**Comment by eightsheep67** [comment]
我刚又测试了一下，lazy改成true就复现了问题。然后interval改120，300，600都没办法出发测速。。。。

**Comment by wwqgtxx** [comment]
如果只有一个url-test组呢，即所有规则都直接指向该组也不能触发测速么

**Comment by eightsheep67** [comment]
> 如果只有一个url-test组呢，即所有规则都直接指向该组也不能触发测速么

刚刚试了下，只要lazy是true就是不行，无法触发。

**Comment by wwqgtxx** [comment]
我在最简化的配置文件下进行了测试，确定了lazy为true的时候是会正常触发urltest的，最新的commit也补上了关于urltest的日志（debug模式下）
```yaml
mixed-port: 7890
external-controller: :7891
external-ui: clash-dashboard-gh-pages
mode: Rule
log-level: debug

proxies:
  - {name: S1, 省略}
  - {name: S2, 省略}
  - {name: S3, 省略}
proxy-groups:
  - name: 自动选择
    type: fallback
    url: http://www.google.com/generate_204
    interval: 30
    proxies:
      - S1
      - S2
      - S3
rules:
 - MATCH,自动选择
```
