### ISSUE TITLE
[BUG] 开启 TUN 导致 Tailscale 无法直接连接其他节点

### ISSUE THREAD

**Issue by mrzhiin** [MetaCubeX/Clash.Meta#239]
版本：v1.13.2

配置：

```
geodata-mode: true
tcp-concurrent: false
sniffer:
  enable: false
  sniffing:
    - tls
    - http
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.apple.com"
    - "+.tailscale.com"
    - "+.tailscale.io"

mixed-port: 7890
allow-lan: false
bind-address: "*"
mode: rule
log-level: warning
ipv6: true
external-controller: 127.0.0.1:9090
interface-name: WLAN
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 114.114.114.114
    - "[240C::6666]:53"
  enhanced-mode: redir-host
  nameserver:
    - https://223.5.5.5/dns-query
tun:
  enable: true
  stack: gvisor # system or gvisor
  auto-route: true
  auto-detect-interface: false

rules:
  - MATCH,DIRECT
```

日志：

```
time="2022-11-04T19:08:50+08:00" level=info msg="Start initial configuration in progress"
time="2022-11-04T19:08:50+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2022-11-04T19:08:50+08:00" level=info msg="Initial configuration complete, total time: 2ms"
time="2022-11-04T19:08:50+08:00" level=info msg="Sniffer is closed"
time="2022-11-04T19:08:50+08:00" level=info msg="DNS server listening at: [::]:53"
time="2022-11-04T19:08:50+08:00" level=info msg="Start initial compatible provider default"
time="2022-11-04T19:08:50+08:00" level=info msg="Use IPv6"
time="2022-11-04T19:08:50+08:00" level=info msg="Use interface name: WLAN"
time="2022-11-04T19:08:50+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2022-11-04T19:08:50+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9090"
time="2022-11-04T19:08:50+08:00" level=info msg="Tun adapter listening at: Meta([198.18.0.1/30],[fdfe:dcba:9876::1/126]), mtu: 9000, auto route: true, ip stack: gVisor"
```

开启后，Tailscale 无法直接连接到其他节点。
