### ISSUE TITLE
求助：tun模式碰上direct规则就打不开网页

### ISSUE THREAD

**Issue by baraja** [MetaCubeX/Clash.Meta#253]
你好，开发者大佬

我这里碰到个两个问题，烦请大佬解答：
一，同样的一个yaml，使用clash meta系统代理就完全没问题，放到clash原版使用tun模式也完全没问题。
但开启clash meta的tun模式后，凡是走direct规则的网站都打不开，走代理的网站才能正常打开
这该如何解决？
二、clash meta开启tun模式后，还有个奇怪的问题
hysteria可以正常使用，trojan则打不开网页（延迟测试也failed），log里面显示
WARNING[TCP] dial Proxy (match Match()) to firebaseremoteconfig.googleapis.com:443 error: TEST.COM:443 connect error: read tcp4 192.168.1.15:10342->[SERVER IP]:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

我的yml示例在这里：https://pastebin.com/ZLqW5qJ9

**Comment by cod-soap** [comment]
我也是个使用者，你是用的什么版本？有更详细的信息吗？

我在使用新版本的tun （1.13.2）  模式也遇到问题，在tun开启自定义路由后  只能走代理的才能打开，走直连的打不开，和你的情况很类似

另外有点好奇，你的yaml示例并没有相关tun配置，是如何启动tun设备的？

**Comment by baraja** [comment]
> 我也是个使用者，你是用的什么版本？有更详细的信息吗？
> 
> 我在使用新版本的tun （1.13.2） 模式也遇到问题，在tun开启自定义路由后 只能走代理的才能打开，走直连的打不开，和你的情况很类似
> 
> 另外有点好奇，你的yaml示例并没有相关tun配置，是如何启动tun设备的？

yml只是一个示例，我用的是clash verge上面的tun开关开启的

**Comment by Skimmle** [comment]
只有 TUN 会遇到这个问题？

**Comment by auqhjjqdo** [comment]
> 只有 TUN 会遇到这个问题？ 配置脱敏后发出来，特别是 DNS 部分

我1.13没用TUN直接系统代理也会遇到direct连接失败，1.12无问题
配置文件没有DNS部分，日志里显示DNS解析io超时和TCP握手失败
```
[DEBUG] [DNS] resolve ****.com error: lookup cn.bing.com: i/o timeout
[DEBUG] [DNS] resolve ****.com error: lookup cn.bing.com on [****::****]:53: no such host
[WARNING] [TCP] dial 🎯 全球直连 (match RuleSet(direct)) to ****.com:443 error: all ips [***.***.***.***] tcp shake hands failed
```

**Comment by Skimmle** [comment]
> > 只有 TUN 会遇到这个问题？ 配置脱敏后发出来，特别是 DNS 部分
> 
> 我1.13没用TUN直接系统代理也会遇到direct连接失败，1.12无问题 配置文件没有DNS部分，日志里显示DNS解析io超时和TCP握手失败
> 
> ```
> [DEBUG] [DNS] resolve ****.com error: lookup cn.bing.com: i/o timeout
> [DEBUG] [DNS] resolve ****.com error: lookup cn.bing.com on [****::****]:53: no such host
> [WARNING] [TCP] dial 🎯 全球直连 (match RuleSet(direct)) to ****.com:443 error: all ips [***.***.***.***] tcp shake hands failed
> ```

你这是 DNS 查询失败了，不写 DNS 会调用系统 DNS，检查系统 DNS 是否正常

**Comment by auqhjjqdo** [comment]
> > > 只有 TUN 会遇到这个问题？ 配置脱敏后发出来，特别是 DNS 部分
> > 
> > 
> > 我1.13没用TUN直接系统代理也会遇到direct连接失败，1.12无问题 配置文件没有DNS部分，日志里显示DNS解析io超时和TCP握手失败
> > ```
> > [DEBUG] [DNS] resolve ****.com error: lookup cn.bing.com: i/o timeout
> > [DEBUG] [DNS] resolve ****.com error: lookup cn.bing.com on [****::****]:53: no such host
> > [WARNING] [TCP] dial 🎯 全球直连 (match RuleSet(direct)) to ****.com:443 error: all ips [***.***.***.***] tcp shake hands failed
> > ```
> 
> 你这是 DNS 查询失败了，不写 DNS 会调用系统 DNS，检查系统 DNS 是否正常

系统DNS没问题的，不开代理都正常访问，相同配置文件换成1.12版本也没问题

**Comment by wwqgtxx** [comment]
@auqhjjqdo 建议你设置一下clash的dns，不要使用系统DNS，看看是否能正常请求

**Comment by auqhjjqdo** [comment]
> 

配置文件增加dns后访问正常了，这是dns部分的配置
```
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
  nameserver:
    - 223.5.5.5
    - 180.76.76.76
    - 119.29.29.29
    - 117.50.11.11
    - 117.50.10.10
    - 114.114.114.114
  fallback:
    - 8.8.8.8
    - 1.1.1.1
    - tls://dns.rubyfish.cn:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
    - https://dns.rubyfish.cn/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
```

这样的话1.13内核在读取系统dns时是否有什么bug导致无法解析呢
