### ISSUE TITLE
【求助】指定的 interface 无效，会自动切换到其他 interface

### ISSUE THREAD

**Issue by vanplus** [MetaCubeX/Clash.Meta#271]
## 配置

```yaml
tun:
  enable: true
  device: Clash-Meta
  # https://github.com/Fndroid/clash_for_windows_pkg/issues/1936
  stack: system # gvisor or system
  # https://github.com/vernesong/OpenClash/issues/521
  dns-hijack:
    - 198.18.0.2:53 # when `fake-ip-range` is 198.18.0.1/16, should hijack 198.18.0.2:53
    # - any:53
    # - tcp://any:53
  auto-route: true # auto set global route for Windows
  interface-name: WLAN
  # auto-detect-interface: false # auto detect interface, conflict with `interface-name`
```

#### 如果先运行 clash.meta 创建 tun interface 再运行其他程序创建其他 interface

>>>
```
time="2022-11-23T17:00:07+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2022-11-23T17:00:07+08:00" level=warning msg="[TUN] default interface changed by monitor,  => WLAN"

time="2022-11-23T17:02:30+08:00" level=warning msg="[TUN] default interface changed by monitor, WLAN => OrayBox"
time="2022-11-23T17:02:30+08:00" level=warning msg="[TUN] default interface changed by monitor, OrayBox => WLAN"
time="2022-11-23T17:02:30+08:00" level=warning msg="[TUN] default interface changed by monitor, WLAN => OrayBox"
time="2022-11-23T17:02:30+08:00" level=warning msg="[TUN] default interface changed by monitor, OrayBox => WLAN"
time="2022-11-23T17:02:31+08:00" level=warning msg="[TUN] default interface changed by monitor, WLAN => OrayBox"
time="2022-11-23T17:02:31+08:00" level=warning msg="[TUN] default interface changed by monitor, OrayBox => WLAN"
time="2022-11-23T17:02:31+08:00" level=warning msg="[TUN] default interface changed by monitor, WLAN => OrayBox"
time="2022-11-23T17:02:32+08:00" level=warning msg="[TUN] default interface changed by monitor, OrayBox => WLAN"
time="2022-11-23T17:02:32+08:00" level=warning msg="[TUN] default interface changed by monitor, WLAN => OrayBox"
time="2022-11-23T17:02:32+08:00" level=warning msg="[TUN] default interface changed by monitor, OrayBox => WLAN"
time="2022-11-23T17:02:32+08:00" level=warning msg="[TUN] default interface changed by monitor, WLAN => OrayBox"
```

#### 如果先运行其他程序创建其他 interface 再 运行 clash.meta 创建 tun interface

>>>
```
time="2022-11-23T17:05:12+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2022-11-23T17:05:12+08:00" level=warning msg="[TUN] default interface changed by monitor,  => OrayBox"
```

## 结论

tun 模式总是选择其他 interface 而不是配置文件中指定的 `WLAN`
