### ISSUE TITLE
[bug]Tun模式启动报错

### ISSUE THREAD

**Issue by qifeng2233** [MetaCubeX/Clash.Meta#276]
系统:ArrowOS12.1(Android12L)
启动Tun失败，日志报错
time="2022-11-27T04:33:45Z" level=error msg="Start TUN listening error: configure tun interface: permission denied"
版本1.13.2，在1.13.1及之前版本中没有出现

**Comment by xishang0128** [comment]
@qifeng2233 没有权限,你确定重新赋权了吗,我这1.13.2正常启动tun

**Comment by Gwenhaell** [comment]
@qifeng2233 换 sing-tun 后，如果禁用本机 ipv6 而 tun 配置了 ipv6，则会报 "Start TUN listening error: configure tun interface: permission denied"

**Comment by qifeng2233** [comment]
> @qifeng2233 换 sing-tun 后，如果禁用本机 ipv6 而 tun 配置了 ipv6，则会报 "Start TUN listening error: configure tun interface: permission denied"

好的，谢谢，我禁用了ipv6

**Comment by qifeng2233** [comment]
> @qifeng2233 换 sing-tun 后，如果禁用本机 ipv6 而 tun 配置了 ipv6，则会报 "Start TUN listening error: configure tun interface: permission denied"

请问有方法让Tun不配置ipv6吗

**Comment by CHIZI-0618** [comment]
> > @qifeng2233 换 sing-tun 后，如果禁用本机 ipv6 而 tun 配置了 ipv6，则会报 "Start TUN listening error: configure tun interface: permission denied"
> 
> 请问有方法让Tun不配置ipv6吗

临时 inet6-address: 置空

```
tun:
  enable: true
  inet6-address:
  stack: system # or gvisor
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true
```

或者更新最新 Alpha 内核
