### ISSUE TITLE
tun模式下，hystaria和tuic协议指定ip-version: ipv6后无法连接

### ISSUE THREAD

**Issue by escapezn** [MetaCubeX/Clash.Meta#292]
环境：Windows 10，Clash.Meta-alpha-910e7fe

为了让hysteria和tuic通过ipv6连接服务器，配置`ip-version: ipv6-prefer`，出现故障无法连接。而在ss协议下相同配置可以正常连接到服务器的ipv6地址。
报错日志
`time="2022-12-10T23:00:21+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:51098 --> 91.108.56.136:443 error: INTERNAL_ERROR: write udp 192.168.82.192:51626->[2403:71c0::]:443: address 2403:71c0:: non-IPv4 address"`

配置文件
```
mixed-port: 7890
geodata-mode: true
tcp-concurrent: true
allow-lan: true
mode: rule
ipv6: true

profile:
  store-selected: true
  store-fake-ip: true

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 223.5.5.5
  enhanced-mode: redir-host
  use-hosts: true
  nameserver:
    - 223.5.5.5

proxies:
  - name: "hy"
    type: hysteria
    server: 
    port: 443
    obfs: 
    alpn:
    - h3
    protocol: udp
    up: 20
    down: 50
    sni: 
    fast-open: true
    ip-version: ipv6

tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - 198.18.0.2:53

```
