### ISSUE TITLE
使用内置iptable功能时权限不足以访问xtables.lock

### ISSUE THREAD

**Issue by handsomexdd1024** [MetaCubeX/Clash.Meta#326]
按照推荐使用clash-meta的内置iptables功能时，出现如下报错：
`can't open lock file /run/xtables.lock: Permission denied`

经排查错误原因可能为：`xtables.lock`的权限为root root 600, `clash-meta`实例运行的用户为clash-meta，故出现`permission denied`现象。

**运行环境**：
Arch Linux 6.1.2-arch1-1, clash-meta的systemd service file如下：
```
[Unit]
Description=Clash-Meta Daemon, Another Clash Kernel.
After=network.target NetworkManager.service systemd-networkd.service iwd.service

[Service]
Type=simple
User=clash-meta
Group=clash-meta
LimitNPROC=500
LimitNOFILE=1000000
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_RAW CAP_NET_BIND_SERVICE
Restart=always
RestartSec=5
ExecStart=/usr/bin/clash-meta -d /etc/clash-meta

[Install]
WantedBy=multi-user.target
```
/etc/clash-meta/config.yaml中相关配置如下：
```
tproxy-port: 7893          #本地Linux Tproxy代理端口
iptables:
  enable: true
  inbound-interface: lo
```
