### ISSUE TITLE
relay 配置 自己的节点 -> wireguard 无法连通

### ISSUE THREAD

**Issue by GeorgeRudd** [MetaCubeX/Clash.Meta#354]
Clash Meta alpha-2cf66f4 windows amd64 with go1.19.5

```yaml
mixed-port: 7890
mode: rule
ipv6: true
log-level: debug
find-process-mode: always
allow-lan: false
geodata-mode: true
tcp-concurrent: true

external-controller: 127.0.0.1:9090   #控制器监听地址
external-ui: yacd-meta                   #http服务路径，可以放静态web网页，如yacd的控制面板，可通过`http://{{external-controller}}/ui`直接使用，添加完后需要右键退出再重启才能生效
secret: "" #控制器登录密码


 
proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 手动切换
      - 转发

  - name: 转发
    type: relay
    proxies:
      - kr
      - wg

  - name: 手动切换
    type: select
    proxies:
      - kr

proxies: 
  - name: "wg"
    type: wireguard
    server: 162.159.192.1
    port: 2408
    ip: 172.16.0.2
    private-key: "私钥"
    public-key: "公钥"
    udp: true
 
  - name: "kr"
    type: ss
    server: ip
    port: 80
    cipher: 2022-blake3-aes-128-gcm
    password: "==:=="
    udp: true
    udp-over-tcp: false
 
rules:
  - DOMAIN-KEYWORD,duckduckgo.com,节点选择
  - GEOSITE,netflix,节点选择
  - GEOSITE,bahamut,节点选择
  - MATCH,节点选择
  
  
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
    
  nameserver:
    - 223.5.5.5
    - 114.114.114.114
    
  fallback:
    - '1.1.1.1#节点选择'
    - '8.8.8.8#节点选择'
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - '!cn'

  proxy-server-nameserver:
    - 223.5.5.5
    - 114.114.114.114
```

```console
23-01-28 19:09:33[ warn ][TCP] dial 节点选择 (match DomainKeyword/duckduckgo.com) 127.0.0.1:10522(chrome.exe) --> duckduckgo.com:443 error: no support
23-01-28 19:09:32[ warn ][TCP] dial 节点选择 (match DomainKeyword/duckduckgo.com) 127.0.0.1:10522(chrome.exe) --> duckduckgo.com:443 error: no support
23-01-28 19:09:32[ warn ][TCP] dial 节点选择 (match DomainKeyword/duckduckgo.com) 127.0.0.1:10522(chrome.exe) --> duckduckgo.com:443 error: no support
23-01-28 19:09:32[ warn ][TCP] dial 节点选择 (match DomainKeyword/duckduckgo.com) 127.0.0.1:10522(chrome.exe) --> duckduckgo.com:443 error: no support

23-01-28 19:10:03[ warn ][TCP] dial 节点选择 (match GeoSite/netflix) 127.0.0.1:10564(chrome.exe) --> www.netflix.com:443 error: no support
23-01-28 19:10:02[ warn ][TCP] dial 节点选择 (match GeoSite/netflix) 127.0.0.1:10564(chrome.exe) --> www.netflix.com:443 error: no support
23-01-28 19:10:02[ warn ][TCP] dial 节点选择 (match GeoSite/netflix) 127.0.0.1:10564(chrome.exe) --> www.netflix.com:443 error: no support
23-01-28 19:10:01[ warn ][TCP] dial 节点选择 (match GeoSite/netflix) 127.0.0.1:10564(chrome.exe) --> www.netflix.com:443 error: no support
23-01-28 19:10:01[ warn ][TCP] dial 节点选择 (match GeoSite/netflix) 127.0.0.1:10564(chrome.exe) --> www.netflix.com:443 error: no support
23-01-28 19:10:01[ warn ][TCP] dial 节点选择 (match GeoSite/netflix) 127.0.0.1:10564(chrome.exe) --> www.netflix.com:443 error: no support
23-01-28 19:10:01[ warn ][TCP] dial 节点选择 (match GeoSite/netflix) 127.0.0.1:10564(chrome.exe) --> www.netflix.com:443 error: no support
```

直接连接kr节点正常。

xray core 使用同样私钥的wg节点是可以正常转发的

客户端配置
```json
		{
			"protocol": "wireguard",
			"settings": {
				"secretKey": "私钥",
				"peers": [
					{
						"publicKey": "公钥",
						"endpoint": "162.159.192.1:2408"
					}
				]
			},
			"streamSettings": {
				"sockopt": {
					"dialerProxy": "kr-out"
				}
			},
			"tag": "proxy-out"
		},
		{
			"tag": "kr-out",
			"protocol": "shadowsocks",
			"settings": {
				"servers": [
					{
						"address": "ip",
						"port": 80,
						"method": "2022-blake3-aes-128-gcm",
						"password": "==:=="
					}
				]
			}
		}
```
