### ISSUE TITLE
代理链配置提示错误

### ISSUE THREAD

**Issue by EsuRt** [MetaCubeX/Clash.Meta#367]
设置了代理链，提示有误，但找不出问题，请教下问题在哪里？

```
port: 7890
socks-port: 7891
ipv6: false
geodata-mode: true
tcp-concurrent: false
allow-lan: true
bind-address: "*"
mode: rule
log-level: debug
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  sniffing:
  - tls
  - http
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:53
  default-nameserver:
  - 223.5.5.5  
  proxy-server-nameserver:
  - https://223.5.5.5/dns-query
  nameserver:
  - https://223.5.5.5/dns-query
  fallback:
  - 'https://1.1.1.1/dns-query#PROXY'
  fallback-filter:
    geosite:
    - geolocation-!cn
    geoip: true
    geoip-code: CN
proxies:
- name: abc
  password:
  server: xxxxxxxxx
  type: vmess
  port: 443
  cipher: auto
  uuid: xxxxxxxxxxxxx
  alterId: 0
  udp: true
proxy-groups:
- name: PROXY
  type: select
  disable-udp: false
  proxies:
  - relay
  - PROXY1
- name: relay
    type: relay
    proxies:
      - PROXY1
      - abc
- name: PROXY1
  type: select
  disable-udp: false
  proxies:
  - abc
  use:
  - aaaa
proxy-providers:
  aaaa:
    type: http
    url: "xxxxxxxxxx"
    interval: 3600
    path: ./aaaa.yaml
rules:
- GEOIP,private,DIRECT,no-resolve
- GEOSITE,geolocation-!cn,PROXY
- GEOSITE,geolocation-cn,DIRECT
- GEOIP,cn,DIRECT
- MATCH,PROXY
```
