### ISSUE TITLE
clashmeta内存占用异常（附heap）

### ISSUE THREAD

**Issue by swong-hs** [MetaCubeX/Clash.Meta#375]
最新的alpha核，AX9000运行，内存占用213M

[heap.txt](https://github.com/MetaCubeX/Clash.Meta/files/10671726/heap.txt)

**Comment by tgNotHouse** [comment]
现在把整个geodata unmarshal后用放内存里，是不是不太合适。一个geodata也就5M左右，这样弄下来就好几百M了。对geodata文件用mmap的方式怎么样。  @Skyxim

**Comment by cubemaze** [comment]
@tgNotHouse 试试

**Comment by tgNotHouse** [comment]
好，目前还在阅读、学习源码中。不过这个问题不怎么麻烦，我先测一下可行性。 @cubemaze

**Comment by swong-hs** [comment]
将dns.prefer-h3: ture字段删除，问题解决。个人猜想是不是h3有问题fallback时导致残留多个geosite在内存里？

**Comment by tgNotHouse** [comment]
![image](https://user-images.githubusercontent.com/19563977/217437496-79ead2d5-78a9-4e7f-afb4-13af955a4ff8.png)

开启后也不行。
无法复现，占用的资源这里是30M左右。

这里是我的配置：

```
dns:
    enable: true
    listen: 0.0.0.0:5353
    ipv6: true
    # default-nameserver: [223.5.5.5, 223.6.6.6]
    enhanced-mode: redir-host
    use-hosts: true
    nameserver:
        - https://mozilla.cloudflare-dns.com/dns-query#DNS&h3=true
    prefer-h3: true
    nameserver-policy:
        'geoip:cn': '114.114.114.114'
```

能否贴一下你的dns配置。
