### ISSUE TITLE
YAML parser error in windows

### ISSUE THREAD

**Issue by msshn** [MetaCubeX/Clash.Meta#378]
I have 2 custom clash rules for bypassing and ad blocking iran domains.
under android and linux, there is no issue and the rules get saved as YAML and work as expected
however under windows, rules can't be saved and clash.meta reurns the following errors for both files:

"initial rule provider iran error: yaml: line 178: mapping values are not allowed in this context"
"initial rule provider iran_ads error: yaml: line 178: mapping values are not allowed in this context"

here is the links to rules:

https://github.com/msshn/iran-hosted-domains/releases/download/20230702/clash_rules.txt
https://github.com/msshn/iran-hosted-domains/releases/download/20230702/clash_rules_ads.txt

but similar rules in the same format like below from Loyalsoldier does not have this issue:

https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt

and here is my rule configuration in clash config file
```
rule-providers:
  iran:
    type: http
    behavior: domain
    url: "https://github.com/msshn/iran-hosted-domains/releases/latest/download/clash_rules.txt"
    path: ./ruleset/iran.yaml
    interval: 86400
  iran_ads:
    type: http
    behavior: domain
    url: "https://github.com/msshn/iran-hosted-domains/releases/latest/download/clash_rules_ads.txt"
    path: ./ruleset/iran_ads.yaml
    interval: 86400
  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
rules :
  - RULE-SET,iran,DIRECT
  - RULE-SET,iran_ads,REJECT
  - RULE-SET,reject,REJECT
  - GEOIP,IR,DIRECT
  - MATCH,PROXY
```

**Comment by Sakaizd** [comment]
It may  caused by network issures,  you can try this:
```yaml
  iran:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://github.com/msshn/iran-hosted-domains/releases/latest/download/clash_rules.txt"
    path: ./ruleset/iran.yaml
    interval: 86400
  iran_ads:
    type: http
    behavior: domain
    url: "https://ghproxy.com/https://github.com/msshn/iran-hosted-domains/releases/latest/download/clash_rules_ads.txt"
    path: ./ruleset/iran_ads.yaml
    interval: 86400
```
