### ISSUE TITLE
Clash.Meta 配置 skip-cert-verify 字段不生效，是否不验证证书？

### ISSUE THREAD

**Issue by LiXin-x** [MetaCubeX/Clash.Meta#382]
最近刚从 Clash 转到 Clash.Meta，偶然发现以下情况，脱敏后报告如下：

客户端：
* clash.meta-darwin-arm64-v1.14.1
* 原版 clash premium：clash-darwin-arm64-v1.13.0

由于泉州白名单，server 我填服务器 ip，sni 填证书域名。使用相同配置进行测试，大致如下：
```
- name: Trojan-X
  type: trojan
  server: 1.2.3.4
  port: 9999
  password: cdpcdpcdp
  # udp: true
  # sni: mysite.com
  alpn:
     - h2
     - http/1.1
  skip-cert-verify: false
```

 skip-cert-verify 值 | true | false | 注释 | false(sni 对应证书）
-- | -- | -- | -- | --
 clash.meta | 正常连接 | 正常连接 | 正常连接 | 正常连接
 clash premium | 正常连接 | 无法连接 | 无法连接 | 正常连接

* 由于 Meta 没有 Debug 模式，不输出关于 TLS 的日志，都显示正常连接的 TCP 日志
* Clash premium 在错误的情况下，会输出：
```
WRN [TCP] dial failed error=1.2.3.4:9999 connect error: x509: cannot validate certificate for 1.2.3.4 because it doesn't contain any IP SANs proxy=Trojan-X lAddr=127.0.0.1:53891 rAddr=149.154.167.41:80 rule=RuleSet rulePayload=Telegram
```

如果不是我错误配置 Clash.Meta，希望能够加上证书验证，增加安全性，谢谢。
