### ISSUE TITLE
ss协议开启udp-over-tcp: true后无法连通，udp类型的dns不通

### ISSUE THREAD

**Issue by GeorgeRudd** [MetaCubeX/Clash.Meta#383]
服务端是xray 1.7.5

```json
		{
			"tag": "shadowsocks-in",
			"port": 80,
			"protocol": "shadowsocks",
			"settings": {
				"method": "2022-blake3-aes-128-gcm",
				"password": "==",
				"clients": [
					{
						"password": "==",
						"email": "1"
					}
				],
				"network": "tcp,udp"
			},
			"sniffing": {
				"enabled": true,
				"destOverride": [
					"http",
					"tls",
					"quic"
				],
				"metadataOnly": false,
				"routeOnly": true
			}
		}

```

Clash Meta alpha-2441955 windows amd64 with go1.20 Wed Feb  8 05:11:14 UTC 2023

ss协议 设置 udp-over-tcp: true 无法连通

```yaml
mixed-port: 7890
mode: rule
ipv6: true
log-level: debug
find-process-mode: always
allow-lan: false
geodata-mode: true
tcp-concurrent: true

tun:
  enable: true
  stack: system
  device: Meta 0 
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-detect-interface: true
  strict-route: true

proxy-groups:

  - name: 节点选择
    type: select
    proxies:
      - jp-ss-1

 
proxies:
             
  - name: jp-ss-1
    type: ss
    server: ip
    port: 80
    cipher: 2022-blake3-aes-128-gcm
    password: "==:=="
    udp: true
    udp-over-tcp: true
       
rules:
  - GEOSITE,cn,DIRECT
  - GEOSITE,private,DIRECT
  - GEOSITE,geolocation-!cn,节点选择
  - GEOIP,cn,DIRECT
  - GEOIP,private,DIRECT
  - GEOIP,!cn,节点选择
  - MATCH,节点选择
  - MATCH,REJECT

dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  use-hosts: true
  nameserver-policy:
    'services.googleapis.cn': 
        - '1.1.1.1#节点选择'
    'geosite:google-cn': 
        - 114.114.114.114
    'geosite:cn': 
        - 223.5.5.5
    '+.msftconnecttest.com': 
        - 223.5.5.5
 
  nameserver:
    - '1.1.1.1#节点选择'
    - '8.8.8.8#节点选择'

  proxy-server-nameserver:
    - 114.114.114.114
    
hosts: 
#支持通配符（非通配符域名优先级高于通配符域名）
  'www.msftconnecttest.com': 23.72.90.20
  'ipv6.msftconnecttest.com': 23.72.90.20
```

日志

```console
23-02-10 11:15:51[ debug ][DNS] resolve mtalk.google.com from udp://1.1.1.1:53
23-02-10 11:15:51[ debug ][DNS] resolve mtalk.google.com from udp://8.8.8.8:53
23-02-10 11:15:51[ debug ][DNS Server] Exchange ;go.microsoft.com. IN A failed: all DNS requests failed, first error: EOF
23-02-10 11:15:51[ debug ][DNS] hijack udp:198.18.0.2:53 from 198.18.0.1:49785
23-02-10 11:15:51[ debug ][DNS] resolve go.microsoft.com from udp://1.1.1.1:53
23-02-10 11:15:51[ debug ][DNS] resolve go.microsoft.com from udp://8.8.8.8:53
23-02-10 11:15:51[ debug ][DNS Server] Exchange ;go.microsoft.com. IN A failed: all DNS requests failed, first error: read tcp4 192.168.2.170:14348->vps ip:80: wsarecv: An existing connection was forcibly closed by the remote host.
23-02-10 11:15:50[ debug ][DNS] hijack udp:[fdfe:dcba:9876::2]:53 from [fdfe:dcba:9876::1]:64834
23-02-10 11:15:50[ debug ][DNS] resolve go.microsoft.com from udp://1.1.1.1:53
23-02-10 11:15:50[ debug ][DNS] resolve go.microsoft.com from udp://8.8.8.8:53
23-02-10 11:15:48[ debug ][DNS Server] Exchange ;mtalk.google.com. IN A failed: all DNS requests failed, first error: EOF
23-02-10 11:15:48[ debug ][DNS] hijack udp:198.18.0.2:53 from 198.18.0.1:56152
23-02-10 11:15:48[ debug ][DNS] resolve mtalk.google.com from udp://1.1.1.1:53
23-02-10 11:15:48[ debug ][DNS] resolve mtalk.google.com from udp://8.8.8.8:53
23-02-10 11:15:48[ debug ][DNS Server] Exchange ;mtalk.google.com. IN A failed: all DNS requests failed, first error: EOF
23-02-10 11:15:48[ debug ][DNS] resolve mtalk.google.com from udp://1.1.1.1:53
23-02-10 11:15:48[ debug ][DNS] resolve mtalk.google.com from udp://8.8.8.8:53
23-02-10 11:15:48[ debug ][DNS] hijack udp:[fdfe:dcba:9876::2]:53 from [fdfe:dcba:9876::1]:49785
23-02-10 11:15:48[ debug ][DNS] hijack udp:[fdfe:dcba:9876::2]:53 from [fdfe:dcba:9876::1]:56152
```

udp-over-tcp: true 时，改成这样就正常
  nameserver:
    - 'tcp://1.1.1.1#节点选择'
    - 'tcp://8.8.8.8#节点选择'

或者 udp-over-tcp: false   
nameserver:
    - '1.1.1.1#节点选择'
    - '8.8.8.8#节点选择'
也是正常的
