### ISSUE TITLE
DNS 设置不起作用

### ISSUE THREAD

**Issue by antonchen** [MetaCubeX/Clash.Meta#384]
我从 Clash 指向 mosdns，我的 mosdns 只有国内网站会返回 IPv6，所以我 DNS 配置开启了 IPv6 返回。
令人奇怪的是我仅配置了 mosdns 但它都会请求 `https://doh.pub:443/dns-query` 并给我返回一个 IPv6，当然并不是 100% 返回，要看它请求了哪个 DNS，尝试过删除缓存重启，并没有用。
下面是我提供的一些信息。

使用版本

```
Clash Meta v1.14.1 linux amd64 with go1.19.5 Wed Jan 11 17:36:06 UTC 2023
```

相关配置

```yaml
ipv6: false
ignore-resolve-fail: true
routing-mark: 0xff
interface-name: ens3
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:5335
  enhanced-mode: redir-host
  default-nameserver:
    - 127.0.0.1:53
  proxy-server-nameserver:
    - 127.0.0.1:53
nameserver:
  - 127.0.0.1:53
fallback:
  - 127.0.0.1:53
```

相关日志

```
time="2023-02-12T23:41:35+08:00" level=debug msg="[https://doh.pub:443/dns-query] using HTTP/2 for this upstream: HTTP3 support is not
time="2023-02-12T23:41:35+08:00" level=debug msg="[DNS] www.youtube.com --> [2001::1f0d:4a01]"
time="2023-02-12T23:41:42+08:00" level=debug msg="[DNS] www.youtube.com --> [108.160.170.39]"
time="2023-02-12T23:41:50+08:00" level=debug msg="[DNS] www.youtube.com --> [2001::1f0d:4a01]"
```
