### ISSUE TITLE
[bug]开tun模式微信朋友圈刷新不了

### ISSUE THREAD

**Issue by skill7899** [MetaCubeX/Clash.Meta#397]
都是用了fake-ip
用原版的clash pro没有这个问题
系统是MAC M1
clash meta版本是
<img width="435" alt="image" src="https://user-images.githubusercontent.com/13962272/219941169-003b09cf-d110-4c92-879e-48622188384c.png">

```


配置如下
#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/*.yaml

## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
## ！！！只有这份文件的端口设置会随ClashX启动生效

## 如果您不知道如何操作，请参阅 官方Github文档 https://github.com/Dreamacro/clash/blob/dev/README.md
#---------------------------------------------------#

# (HTTP and SOCKS5 in one port)
mixed-port: 7892
# RESTful API for clash
external-controller: 127.0.0.1:58153
allow-lan: false
bind-address:
  '*'
mode: rule
log-level: error
proxies:
  - name: trojan-ws
    server: xxx
    port: 443
    type: trojan
    password: xx
    network: ws
    # skip-cert-verify: true
    udp: true
    ws-opts:
      path: /wsIev
  - name: "hysteria"
    type: hysteria
    server: xxx
    #port: 7070
    ports: 20000-50000
    auth_str: xxx
    protocol: "udp"
    alpn: ['h3']
    up: 50 #默认为Mbps
    down: 500
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - hysteria
      - trojan-ws  
geodata-mode: true
hosts:                            
   'cc.ieva.top': 192.168.60.10
#  'a.ieva.top': 10.192.170.145
use-hosts: true 
tun:
  enable: true
  # device: meta
  stack: system #gvisor
  dns-hijack:
  #     - 8.8.8.8:53
  #     - tcp://8.8.8.8:53
    - any:53
  auto-route: true
  auto-detect-interface: true
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
    - '*.apple.com'
  # - '*.baidu.com'

  force-domain:
    # - '+'
    - 'google.com'

  port-whitelist:
    - 443
    - 8000-9000
profile:
  #缓存设置(文件位置./cache.db)
  store-selected: false #节点状态记忆（若不同配置有同代理名称,设置值共享）
  store-fake-ip: true #fake-ip缓存
tcp-concurrent: true
dns:
  enable: true #DNS开关(false/true)
  listen: :53 #DNS监听地址
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    #- 172.16.31.1
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback: 
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
    - https://public.dns.iij.jp/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      #【Meta专属】设定geosite某分类使用fallback返回结果
      - gfw
    domain:
      #列表中的域名使用fallback返回解析结果
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
  enhanced-mode: fake-ip
  ipv6: true
  fake-ip-range: 198.18.1.1/16
  fake-ip-filter:
    #- '*.github.com'
    #- 'github.com'
    # 以下域名列表参考自 vernesong/OpenClash 项目，并由 Hackl0us 整理补充
    # === LAN ===
    - '*.lan'
    # === Linksys Wireless Router ===
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    # === Apple Software Update Service ===
    - 'swscan.apple.com'
    - 'mesu.apple.com'
    # === Windows 10 Connnect Detection ===
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    # === NTP Service ===
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'

    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'

    - 'ntp.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'

    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'

    - 'time1.cloud.tencent.com'
    # === Music Service ===
    ## NetEase
    - '+.music.163.com'
    - '*.126.net'
    ## Baidu
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    ## Kugou
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    ## Kuwo
    - '*.kuwo.cn'
    ## JOOX
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    ## QQ
    - '+.y.qq.com'
    - '+.music.tc.qq.com'
    - 'aqqmusic.tc.qq.com'
    - '+.stream.qqmusic.qq.com'
    ## Xiami
    - '*.xiami.com'
    ## Migu
    - '+.music.migu.cn'
    # === Game Service ===
    ## Nintendo Switch
    - '+.srv.nintendo.net'
    ## Sony PlayStation
    - '+.stun.playstation.net'
    ## Microsoft Xbox
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    # === Other ===
    ## QQ Quick Login
    - 'localhost.ptlogin2.qq.com'
    ## Golang
    - 'proxy.golang.org'
    ## STUN Server
    - 'stun.*.*'
    - 'stun.*.*.*'

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
rules:

  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,Proxy
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,Proxy
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy

```

**Comment by skill7899** [comment]
无论是用fake还是redir模式都不行。

**Comment by y1zhou** [comment]
同样问题，如果关掉tun，打开微信朋友圈（可正常刷新），再打开tun，那么朋友圈就可以刷新，直觉跟微信的内置 DNS 有关系

**Comment by Larvan2** [comment]
@y1zhou 微信用的是httpdns，可能相关域名或ip被代理了

**Comment by skill7899** [comment]
> 同样问题，如果关掉tun，打开微信朋友圈（可正常刷新），再打开tun，那么朋友圈就可以刷新，直觉跟微信的内置 DNS 有关系

你的第二步操作，只能刷一次。之后就刷不了。

**Comment by Skyxim** [comment]
尝试精简配置，确定问题点，如删除规则，仅保留 MATCH,DIRECT。以及删除 DNS 中 fallback、fake-ip-filter 等

**Comment by skill7899** [comment]
> 尝试精简配置，确定问题点，如删除规则，仅保留 MATCH,DIRECT。以及删除 DNS 中 fallback、fake-ip-filter 等

已经精简到如下了，依然不行
```

#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/*.yaml

## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
## ！！！只有这份文件的端口设置会随ClashX启动生效

## 如果您不知道如何操作，请参阅 官方Github文档 https://github.com/Dreamacro/clash/blob/dev/README.md
#---------------------------------------------------#

# (HTTP and SOCKS5 in one port)
mixed-port: 7892
# RESTful API for clash
external-controller: 127.0.0.1:58153
allow-lan: false
bind-address:
  '*'
mode: rule
log-level: error
proxies:
  - name: "ss"
    type: socks5
    server: 127.0.0.1
    port: 1086
geodata-mode: false
tun:
  enable: true
  # device: meta
  stack: system #gvisor
  auto-route: true
  auto-detect-interface: true
sniffer:
  enable: false
  sniffing:
    - tls
    - http
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
    - '*.apple.com'
  # - '*.baidu.com'

  force-domain:
    # - '+'
    - 'google.com'

  port-whitelist:
    - 443
    - 8000-9000
profile:
  #缓存设置(文件位置./cache.db)
  store-selected: false #节点状态记忆（若不同配置有同代理名称,设置值共享）
  store-fake-ip: false #fake-ip缓存
tcp-concurrent: false
dns:
  enable: true #DNS开关(false/true)
  listen: 127.0.0.1:53 #DNS监听地址
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    #- 172.16.31.1
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  enhanced-mode: redir-host #fake-ip
rules:

  - MATCH,DIRECT
```
