### ISSUE TITLE
force-dns-mapping 是否生效问题

### ISSUE THREAD

**Issue by Hill-98** [MetaCubeX/Clash.Meta#399]
根据 config.yaml 的备注所述，`force-dns-mapping` 选项会对 redir-host 类型的流量进行强制嗅探，可是我在路由器使用 redir-host 模式时发现 `force-dns-mapping` 选项好像没有影响任何东西。

开启 `force-dns-mapping` 并关闭 `parse-pure-ip` 时，域名探测未生效，所有 `Redir` 类型流量都没有探测到域名。
关闭 `force-dns-mapping` 并开启 `parse-pure-ip` 时，域名探测生效。
同时开启 `force-dns-mapping` 和 `parse-pure-ip` 时，域名探测生效，但是和只开启 `parse-pure-ip` 好像没区别。

**Comment by Hill-98** [comment]
sniffer 配置部分如下：

```yaml
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  skip-domain:
  - Mijia Cloud
  sniff:
    TLS:
      ports:
      - 443
      - 8000-9000
      - 27000-27100
      override-destination: false
    HTTP:
      ports:
      - 80
      - 8000-9000
      override-destination: false
```

**Comment by Hill-98** [comment]
我好像知道 `force-dns-mapping` 选项的作用了，它是使用内部 DNS 结果把 IP 映射成域名，即使是关闭 override-destination 的情况下。

**Comment by Skyxim** [comment]
@Hill-98 全名应该叫强制 dns 映射 嗅探

**Comment by Hill-98** [comment]
了解了，希望能更新下 docs.metacubex.one，以对这些选项进行更完整的说明。

**Comment by Hill-98** [comment]
![image](https://user-images.githubusercontent.com/25147395/220127772-36482d1f-0f08-46a3-a76b-e2dde2c4e8e2.png)

@Skyxim 关闭 `override-destination` 的情况下，上图所示是不是就是 `force-dns-mapping` 的结果，可是我已经关闭了 `force-dns-mapping` 选项。

**Comment by Hill-98** [comment]
是不是和 tunnel/tunnel.go 的以下代码有关

needLookupIP 不应该在关闭 `force-dns-mapping` 时返回 false 吗？
```go
func preHandleMetadata(metadata *C.Metadata) error {
	// handle IP string on host
	if ip, err := netip.ParseAddr(metadata.Host); err == nil {
		metadata.DstIP = ip
		metadata.Host = ""
	}

	// preprocess enhanced-mode metadata
	if needLookupIP(metadata) {
		host, exist := resolver.FindHostByIP(metadata.DstIP)
		if exist {
			metadata.Host = host
			metadata.DNSMode = C.DNSMapping
			if resolver.FakeIPEnabled() {
				metadata.DstIP = netip.Addr{}
				metadata.DNSMode = C.DNSFakeIP
			} else if node := resolver.DefaultHosts.Search(host); node != nil {
				// redir-host should lookup the hosts
				metadata.DstIP = node.Data()
			}
		} else if resolver.IsFakeIP(metadata.DstIP) {
			return fmt.Errorf("fake DNS record %s missing", metadata.DstIP)
		}
	}

	return nil
}
```

**Comment by Skyxim** [comment]
`override-destination`

> 是不是和 tunnel/tunnel.go 的以下代码有关
> 
> needLookupIP 不应该在关闭 `force-dns-mapping` 时返回 false 吗？
> 
> ```go
> func preHandleMetadata(metadata *C.Metadata) error {
> 	// handle IP string on host
> 	if ip, err := netip.ParseAddr(metadata.Host); err == nil {
> 		metadata.DstIP = ip
> 		metadata.Host = ""
> 	}
> 
> 	// preprocess enhanced-mode metadata
> 	if needLookupIP(metadata) {
> 		host, exist := resolver.FindHostByIP(metadata.DstIP)
> 		if exist {
> 			metadata.Host = host
> 			metadata.DNSMode = C.DNSMapping
> 			if resolver.FakeIPEnabled() {
> 				metadata.DstIP = netip.Addr{}
> 				metadata.DNSMode = C.DNSFakeIP
> 			} else if node := resolver.DefaultHosts.Search(host); node != nil {
> 				// redir-host should lookup the hosts
> 				metadata.DstIP = node.Data()
> 			}
> 		} else if resolver.IsFakeIP(metadata.DstIP) {
> 			return fmt.Errorf("fake DNS record %s missing", metadata.DstIP)
> 		}
> 	}
> 
> 	return nil
> }
> ```

无关，这是嗅探不分的配置。`force-dns-mapping` 是控制是否嗅探的一个参数，默认下只会嗅探无法获得域名的流量，当强制开启他，则会嗅探由 DNS 映射逻辑获得的域名（不包括 SOCKS5、HTTP、SS 和 TUIC 等能直接传输域名的入站协议），也就是开启他就会强制嗅探所有透明代理流量
至于还有个 `parse-pure-ip` 则在支持域名传输入站的协议上强制嗅探所有无域名流量

**Comment by Skyxim** [comment]
> 是不是和 tunnel/tunnel.go 的以下代码有关
> 
> needLookupIP 不应该在关闭 `force-dns-mapping` 时返回 false 吗？
> 
> ```go
> func preHandleMetadata(metadata *C.Metadata) error {
> 	// handle IP string on host
> 	if ip, err := netip.ParseAddr(metadata.Host); err == nil {
> 		metadata.DstIP = ip
> 		metadata.Host = ""
> 	}
> 
> 	// preprocess enhanced-mode metadata
> 	if needLookupIP(metadata) {
> 		host, exist := resolver.FindHostByIP(metadata.DstIP)
> 		if exist {
> 			metadata.Host = host
> 			metadata.DNSMode = C.DNSMapping
> 			if resolver.FakeIPEnabled() {
> 				metadata.DstIP = netip.Addr{}
> 				metadata.DNSMode = C.DNSFakeIP
> 			} else if node := resolver.DefaultHosts.Search(host); node != nil {
> 				// redir-host should lookup the hosts
> 				metadata.DstIP = node.Data()
> 			}
> 		} else if resolver.IsFakeIP(metadata.DstIP) {
> 			return fmt.Errorf("fake DNS record %s missing", metadata.DstIP)
> 		}
> 	}
> 
> 	return nil
> }
> ```

具体类型种类在入站则决定

**Comment by Hill-98** [comment]
配置文件:
```yaml
allow-lan: false
bind-address: 127.0.0.1
external-controller: 127.0.0.1:9090
log-level: debug
mixed-port: 7890
mode: rule
tcp-concurrent: false
dns:
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enable: true
  enhanced-mode: redir-host
  fallback:
    - https://1.1.1.1/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
      - greatfire
  listen: 0.0.0.0:9053
  nameserver:
    - https://120.53.53.53/dns-query
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  force-dns-mapping: false
  parse-pure-ip: true
  skip-domain:
    - Mijia Cloud
  override-destination: false
  sniff:
    TLS:
      ports:
        - 443
        - 8080
        - 8443
        - 27000-27100
    HTTP:
      ports:
        - 80
        - 8000
        - 8080
proxies:
  - name: 默认代理
    type: socks5
    server: 10.10.10.1
    port: 10090
    udp: true
rules:
  - MATCH,默认代理
```

测试步骤:

1. `curl -I -x socks5://127.0.0.1:7890 http://www.youtube.com`，捕获数据包显示发送至 `10.10.10.1:10090` 的 SOCKS 数据包的 `Address Type` 字段为 `IPv4`，`Remote Address` 字段为 `216.239.38.119`。
2.  `q @127.0.0.1:9053 restrictmoderate.youtube.com`，使用 DNS 客户端向 Clash 查询 `restrictmoderate.youtube.com`，得到结果 `216.239.38.119`。
3. `curl -I -x socks5://127.0.0.1:7890 http://www.youtube.com`，捕获数据包显示发送至 `10.10.10.1:10090` 的 SOCKS 数据包的 `Address Type` 字段为 `Domain Name`，`Remote Address` 字段为 `restrictmoderate.youtube.com`。

这是不是可以算做 BUG
