### ISSUE TITLE
PASS 这样使用是否正确

### ISSUE THREAD

**Issue by CyEilo** [MetaCubeX/Clash.Meta#40]
wiki的example里面找不到范例 不知是不是这样设计的

```
proxy-groups:
  - name: manual
    type: select
    proxies:
      - PASS
      - DIRECT
      - Proxies


rules:
  - SRC-IP-CIDR,192.168.1.99/32,manual
```
