### ISSUE TITLE
It appears that there has been an issue resolving the IPv6 address from another device.

### ISSUE THREAD

**Issue by sirlaurie** [MetaCubeX/Clash.Meta#401]
I deploy meta on a raspberry(ip: 192.168.1.5) as gateway and dns server. 

beblow is part of config file

```
ipv6: true
tun:
  enable: true
  device: tun
  stack: system
  auto-route: true
  auto-redir: true
  auto-detect-interface: true
  mtu: 1420
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
```

and gateway route:
```
➜  ip route
default via 192.168.1.1 dev end0 onlink
192.168.1.0/24 dev end0 proto kernel scope link src 192.168.1.5
198.18.0.0/30 dev tun proto kernel scope link src 198.18.0.1
```

on raspberry, I can get a IPv6 via meta's dns, like:
```
➜  nslookup ipv6.test-ipv6.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Name:	ipv6.test-ipv6.com
Address: 2001:470:1:18::115
```

but on the other device, it always failed:
```
➜  nslookup ipv6.test-ipv6.com
Server:		192.168.1.5
Address:	192.168.1.5#53

*** Can't find ipv6.test-ipv6.com: No answer
```
