### ISSUE TITLE
请教关于socks5出站

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [MetaCubeX/Clash.Meta#424]
openclash-clash.meta socks5出站→xray socks5入站→xray reality出站，不懂为什么就测延迟能通，正常连接不通，是否缺少了什么配置？
用windows系统代理http出站→xray http入站→xray reality出站就正常

xray配置
```
{
    "inbounds": [
        {
            "tag": "socks-in",
            "listen": "127.0.0.1",
            "port": 10808,
            "protocol": "socks",
            "settings": {"udp": true}
        },
        {
            "tag": "http-in",
            "listen": "127.0.0.1",
            "port": 10809,
            "protocol": "http"
        },
    ],
    "outbounds": [
        {
            "tag": "proxy",
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": "",
                        "port": ,
                        "users": [
                            {
                                "id": "",
                                "encryption": "none",
                                "flow": ""
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "h2",
                "security": "reality",
                "realitySettings": {
                    "fingerprint": "firefox",
                    "serverName": "",
                    "publicKey": "",
                    "shortId": ""
                }
            }
        },
        {
            "tag": "direct",
            "protocol": "freedom"
        }
    ]
}
```

xray日志
```
2023/03/04 17:17:43 [Info] [3492229842] proxy/socks: TCP Connect request to tcp:91.108.56.156:80
2023/03/04 17:17:43 [Info] [3492229842] app/dispatcher: default route for tcp:91.108.56.156:80
2023/03/04 17:17:43 tcp:127.0.0.1:36932 accepted tcp:91.108.56.156:80 [socks-in >> proxy]
2023/03/04 17:17:43 [Info] [3492229842] proxy/vless/outbound: tunneling request to tcp:91.108.56.156:80 via xxx:443
2023/03/04 17:17:43 [Info] [406610996] proxy/socks: TCP Connect request to tcp:clients4.google.com:443
2023/03/04 17:17:43 [Info] [406610996] app/dispatcher: default route for tcp:clients4.google.com:443
2023/03/04 17:17:43 [Info] [406610996] proxy/vless/outbound: tunneling request to tcp:clients4.google.com:443 via xxx:443
2023/03/04 17:17:43 tcp:127.0.0.1:36942 accepted tcp:clients4.google.com:443 [socks-in >> proxy]
2023/03/04 17:17:47 [Info] [3118113582] proxy/socks: TCP Connect request to tcp:www.google.com:443
2023/03/04 17:17:47 [Info] [3118113582] app/dispatcher: default route for tcp:www.google.com:443
2023/03/04 17:17:47 tcp:127.0.0.1:36958 accepted tcp:www.google.com:443 [socks-in >> proxy]
2023/03/04 17:17:47 [Info] [3118113582] proxy/vless/outbound: tunneling request to tcp:www.google.com:443 via xxx:443
```

clash配置
```
mode: rule
ipv6: false
log-level: info
geodata-mode: true
geodata-loader: memconservative
tcp-concurrent: true
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: false
dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - https://1.1.1.1/dns-query#PROXY
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    "geosite:cn": https://dns.alidns.com/dns-query
  fake-ip-filter:
  - "+.lan"
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
proxies:
- name: SOCKS5-OUT
  type: socks5
  server: 127.0.0.1
  port: 10808
  udp: true
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - SOCKS5-OUT
  - DIRECT
rules:
- GEOIP,private,DIRECT,no-resolve
- GEOIP,telegram,PROXY,no-resolve
- GEOSITE,CN,DIRECT
- GEOIP,CN,DIRECT
- MATCH,PROXY
```

clash日志
```
23-03-05 01:36:12[ warn ][TCP] dial PROXY (match GeoSite/google) 10.10.10.1:13381 --> www.google.com:443 error: 127.0.0.1:10808 connect error: dial tcp 127.0.0.1:10808: connect: connection refused
23-03-05 01:36:12[ warn ][TCP] dial PROXY (match GeoIP/telegram) 10.10.10.1:13380 --> 91.108.56.156:80 error: 127.0.0.1:10808 connect error: dial tcp 127.0.0.1:10808: connect: connection refused
23-03-05 01:36:12[ warn ][TCP] dial PROXY (match GeoIP/telegram) 10.10.10.1:13379 --> 91.108.56.156:80 error: 127.0.0.1:10808 connect error: dial tcp 127.0.0.1:10808: connect: connection refused
23-03-05 01:36:12[ warn ][TCP] dial PROXY (match GeoIP/telegram) 10.10.10.1:13378 --> 91.108.56.156:443 error: 127.0.0.1:10808 connect error: dial tcp 127.0.0.1:10808: connect: connection refused
23-03-05 01:36:12[ warn ][TCP] dial PROXY (match GeoIP/telegram) 10.10.10.1:13377 --> 91.108.56.156:443 error: 127.0.0.1:10808 connect error: dial tcp 127.0.0.1:10808: connect: connection refused
23-03-05 01:36:12[ warn ][TCP] dial PROXY (match GeoIP/telegram) 10.10.10.1:13376 --> 91.108.56.156:80 error: 127.0.0.1:10808 connect error: dial tcp 127.0.0.1:10808: connect: connection refused
23-03-05 01:36:12[ warn ][TCP] dial PROXY (match GeoIP/telegram) 10.10.10.1:13375 --> 91.108.56.156:443 error: 127.0.0.1:10808 connect error: dial tcp 127.0.0.1:10808: connect: connection refused
23-03-05 01:36:12[ warn ][TCP] dial PROXY (match GeoIP/telegram) 10.10.10.1:13374 --> 91.108.56.156:80 error: 127.0.0.1:10808 connect error: dial tcp 127.0.0.1:10808: connect: connection refused
23-03-05 01:36:12[ warn ][TCP] dial PROXY (match GeoIP/telegram) 10.10.10.1:13373 --> 91.108.56.156:443 error: 127.0.0.1:10808 connect error: dial tcp 127.0.0.1:10808: connect: connection refused
```
