### ISSUE TITLE
tuic listen to only ipv6

### ISSUE THREAD

**Issue by hiddify1** [MetaCubeX/Clash.Meta#426]
in my configuration even that i have disabled ipv6 but it only listen to ipv6

```
tuic-server:
  enable: true
  listen: 0.0.0.0:3478 
  token:
    - mytok
  certificate: ../ssl/a.crt
  private-key: ../ssl/a.key
  congestion-controller: bbr
  max-idle-time: 15000
  authentication-timeout: 1000
  alpn:
    - h3
  max-udp-relay-packet-size: 1500

```

`INFO[0000] Tuic proxy listening at: [::]:3478`
```
lsof -i:3479
COMMAND      PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
clashmeta 561194 root    8u  IPv6 2923253      0t0  UDP *:3479
```
