### ISSUE TITLE
Tun Mode  crash occasionally

### ISSUE THREAD

**Issue by ag2s20150909** [MetaCubeX/Clash.Meta#44]
```
##Basic
port: 7890
socks-port: 7891
log-level: info
external-controller: 127.0.0.1:9090
allow-lan: false
##TUN
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - 0.0.0.0:53
  auto-route: true
##DNS
dns:
  enable: true
  use-hosts: true
  ipv6: true
  enhanced-mode: redir-host #fake-ip or redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:6868
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa18620]

goroutine 61097 [running]:
gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*endpoint).SocketOptions(0x0?)
        gvisor.dev/gvisor@v0.0.0-20220419020849-1f2f4462d45b/pkg/tcpip/transport/tcp/endpoint.go:3175
github.com/Dreamacro/clash/listener/tun/ipstack/gvisor.setSocketOptions(0xc0099d67c0?, {0xdc4d08, 0x0})
        github.com/Dreamacro/clash/listener/tun/ipstack/gvisor/tcp.go:84 +0x33
github.com/Dreamacro/clash/listener/tun/ipstack/gvisor.withTCPHandler.func1.1(0xc0099d67c0)
        github.com/Dreamacro/clash/listener/tun/ipstack/gvisor/tcp.go:69 +0x1b4
created by gvisor.dev/gvisor/pkg/tcpip/transport/tcp.(*Forwarder).HandlePacket
        gvisor.dev/gvisor@v0.0.0-20220419020849-1f2f4462d45b/pkg/tcpip/transport/tcp/forwarder.go:94 +0x3b0
```
