### ISSUE TITLE
最新构建alpha版，使用vision+reality报错，出现内存错误

### ISSUE THREAD

**Issue by Zxis233** [MetaCubeX/Clash.Meta#440]
测试后，发现测速也会触发。若将端口改为错误的端口则不会触发。
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5f606d033c]

goroutine 10 [running]:
github.com/Dreamacro/clash/component/tls.GetFingerprint({0x400010eda0?, 0x1c?})
	github.com/Dreamacro/clash/component/tls/utls.go:48 +0x14c
github.com/Dreamacro/clash/transport/vmess.GetUTLSConn({0x5f613f7c28, 0x4000542048}, {0x400010eda0?, 0x0?}, 0x0?)
	github.com/Dreamacro/clash/transport/vmess/tls.go:69 +0x34
github.com/Dreamacro/clash/transport/vmess.StreamTLSConn({0x5f613f7c28?, 0x4000542048}, 0x400036f438)
	github.com/Dreamacro/clash/transport/vmess/tls.go:40 +0x160
github.com/Dreamacro/clash/adapter/outbound.(*Vless).streamTLSOrXTLSConn(0x400012c040, {0x5f613f7c28, 0x4000542048}, 0x0)
	github.com/Dreamacro/clash/adapter/outbound/vless.go:207 +0x234
github.com/Dreamacro/clash/adapter/outbound.(*Vless).StreamConn(0x400012c040, {0x5f613f7c28?, 0x4000542048?}, 0x5f60c23aa3?)
	github.com/Dreamacro/clash/adapter/outbound/vless.go:164 +0x51c
github.com/Dreamacro/clash/adapter/outbound.(*Vless).DialContextWithDialer(0x400012c040, {0x5f613ec908?, 0x4003742330?}, {0x5f613e86b0?, 0x400364c120?}, 0x5f601d8328?)
	github.com/Dreamacro/clash/adapter/outbound/vless.go:250 +0xe8
github.com/Dreamacro/clash/adapter/outbound.(*Vless).DialContext(0x400012c040, {0x5f613ec908, 0x4003742330}, 0x0?, {0x0?, 0x4000090460?, 0x40037461c0?})
	github.com/Dreamacro/clash/adapter/outbound/vless.go:236 +0x248
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0x40005148a0?, {0x5f613ec908?, 0x4003742330?}, 0x5f601df6b8?, {0x0?, 0x5f60227cf8?, 0x400036f988?})
	github.com/Dreamacro/clash/adapter/adapter.go:41 +0x34
github.com/Dreamacro/clash/adapter/outboundgroup.(*Selector).DialContext(0x4000090f40, {0x5f613ec908, 0x4003742330}, 0x0?, {0x0, 0x0, 0x0})
	github.com/Dreamacro/clash/adapter/outboundgroup/selector.go:22 +0x90
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0x4000514960?, {0x5f613ec908?, 0x4003742330?}, 0x5f6020f970?, {0x0?, 0x4000296520?, 0x400036fa08?})
	github.com/Dreamacro/clash/adapter/adapter.go:41 +0x34
github.com/Dreamacro/clash/adapter/outboundgroup.(*Selector).DialContext(0x40000910e0, {0x5f613ec908, 0x4003742330}, 0x5f60239f9c?, {0x0, 0x0, 0x0})
	github.com/Dreamacro/clash/adapter/outboundgroup/selector.go:22 +0x90
github.com/Dreamacro/clash/adapter.(*Proxy).DialContext(0x400036faa8?, {0x5f613ec908?, 0x4003742330?}, 0x79e24ac878?, {0x0?, 0x5f601dfa7c?, 0x400036fad8?})
	github.com/Dreamacro/clash/adapter/adapter.go:41 +0x34
github.com/Dreamacro/clash/tunnel.handleTCPConn.func3({0x5f613ec908?, 0x4003742330?})
	github.com/Dreamacro/clash/tunnel/tunnel.go:415 +0x84
github.com/Dreamacro/clash/tunnel.retry[...]({0x5f613ec908?, 0x4003742330}, 0x400036ff68, 0x400036fef8)
	github.com/Dreamacro/clash/tunnel/tunnel.go:589 +0xc0
github.com/Dreamacro/clash/tunnel.handleTCPConn({0x5f613e9a20, 0x4000208020})
	github.com/Dreamacro/clash/tunnel/tunnel.go:414 +0x514
created by github.com/Dreamacro/clash/tunnel.process
	github.com/Dreamacro/clash/tunnel/tunnel.go:180 +0x74

heap文件为https://github.com/Zxis233/baser/blob/main/heap?raw=true

**Comment by H1JK** [comment]
Please post your proxy config.

**Comment by Zxis233** [comment]
> Please post your proxy config.

Here is my Config.yaml:
```yaml
tproxy-port: 9898
# redir-port: 9454
# mixed-port: 7890
mode: rule
allow-lan: true
unified-delay: true
bind-address: '*'
log-level: debug
ipv6: false
geodata-mode: true
external-controller: 0.0.0.0:9090
external-ui: dashboard/dist
tcp-concurrent: false
# interface-name: ""
enable-process: false
geodata-loader: memconservative
# routing-mark: 233
inbound-tfo: false
global-client-fingerprint: chrome
secret: ""
global-client-fingerprint: chrome
# geox-url: {mmdb: "", geoip: "", geosite: ""}
hosts: {"cacerts.digicert.com": "104.21.21.147", "ota.googlezip.net": "127.0.0.1", "ota-cache1.googlezip.net": "127.0.0.1", "ota-cache2.googlezip.net": "127.0.0.1"}
dns:
  enable: true
  listen: 0.0.0.0:72
  ipv6: true
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter: ["*.local", "*.localhost"]
  nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - https://doh.opendns.com/dns-query
    - https://dns.adguard.com/dns-query
    - https://doh.dns.sb/dns-query
    - https://dns64.cloudflare-dns.com/dns-query
    - https://dns64.dns.google/dns-query
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
proxies:
  - name: "SYT-Reality"
    type: vless
    server: xxx
    port: 40443
    uuid: 107b489a-2c29-4190-b847-d206bf1f2939
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: xxx # REALITY servername
    client-fingerprint: chrome # cannot be empty
    reality-ops:
      public-key: ISwpz3IxjJHMF3wzR5q_-2RETVD2UY_lpAO82NjsHGY
proxy-groups:
  - name: "MyProxy"
    type: select
    proxies:
     - SYT-Reality
  - name: "Ayanami"
    type: select
    use:
     - Ayanami
proxy-providers: #在这配置订阅
  Ayanami: #随便的机场名字
    type: http  #订阅类型
    url: "xxx"  #机场订阅链接
    path: ./proxy_providers/Ayanami.yaml  #下载好的文件的存储位置
    interval: 14400  #自动更新订阅间隔，秒为单位
rule-providers:
  *** ......
rules:
  - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,lancidr,DIRECT  
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,proxy,GLOBAL
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,GLOBAL
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,GLOBAL
```
