### ISSUE TITLE
url-test group重复出现

### ISSUE THREAD

**Issue by gdyan2001** [MetaCubeX/Clash.Meta#46]
```
- name: 🇭🇰 香港
    type: select 
    proxies:
      - ♻️ 自动选择HK
      - DIRECT    
    use:
      - meta
     filter: "HK|香港|🇭🇰"
- name: ♻️ 自动选择HK
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    use:
      - meta
    filter: "HK|香港|🇭🇰"      
```
组🇭🇰 香港中会出现两个  ♻️ 自动选择HK
