### ISSUE TITLE
TUN模式dns泄漏

### ISSUE THREAD

**Issue by shallbytwo** [MetaCubeX/Clash.Meta#470]
设备：MacBookpro
系统版本：13.1 
**客户端**：clash-verge v1.3.0
**内核**：clash-meta alpha 3e47bfa
问题：同一份配置在“系统代理”模式下使用ipleak.net测试**没有**dns泄漏问题，在“TUN”模式下**有**dns泄漏问题。使用https://browserleaks.com/dns 测试也一样。
配置文件：
```
#clash.meta示例: https://docs.metacubex.one/example/ex1
#CLASH.META内核：https://github.com/MetaCubeX/Clash.Meta/tree/Meta
#  https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/docs/config.yaml
mixed-port: 7890
# tcp-concurrent: true         #【Meta专属】TCP连接并发，如果域名解析结果对应多个IP，并发所有IP，选择握手最快的IP进行连接
geodata-mode: true
allow-lan: true
bind-address: '*'
find-process-mode: strict
mode: rule
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
log-level: warning
ipv6: false
external-controller: 0.0.0.0:9090
# secret: "passwd"
global-client-fingerprint: chrome
hosts:
profile:
  store-selected: false
  store-fake-ip: true

tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
  strict_route: true

sniffer:                         #【Meta专属】sniffer域名嗅探器
  enable: true                   #嗅探开关
  sniffing:                      #嗅探协议对象：目前支持tls/http
    - tls
    - http
  skip-domain:                   #列表中的sni字段，保留mapping结果，不通过嗅探还原域名
                                 #优先级比force-domain高
    - 'Mijia Cloud'              #米家设备，建议加
    - 'dlg.io.mi.com'
    - '+.apple.com'              #苹果域名，建议加
  # - '*.baidu.com'              #支持通配符
    
  force-domain:                  #需要强制嗅探的域名，默认只对IP嗅探
  # - '+'                        #去掉注释后等于全局嗅探
    - 'google.com'

dns:
  enable: true
  perfer-h3: true
  listen: 0.0.0.0:1053
  ipv6: false
  default-nameserver:
    - tls://1.12.12.12:853
    - tls://223.5.5.5:853
  enhanced-mode: fake-ip  # redir-host # or  fake-ip 
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: false
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
  nameserver:
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query#h3=true 
  proxy-server-nameserver:          #【Meta专属】解析代理服务器域名的dns
   - https://1.1.1.1/dns-query              # 不写时用nameserver解析

  nameserver-policy:
    "geosite:cn,private,apple":
      - 'https://1.12.12.12/dns-query'
      - 'https://223.5.5.5/dns-query#h3=true'
    'geosite:!cn':
      - 'https://8.8.8.8/dns-query#PROXY'
      - 'https://1.1.1.1/dns-query#PROXY'

#=======================================================================
proxies:
  - name: Vision-REALITY
    type: vless
    server: 123xxxxxxxx
    port: 8443
    uuid: 822xxxxxxxxxxxxx72052
    network: tcp
    tls: true
    udp: false
    flow: xtls-rprx-vision
    servername: www.microsoft.com
    reality-opts:
      public-key: R8txxxxxxxxxxxxxx0o41Q
      short-id: 0caxxxxxxx12b8
    client-fingerprint: chrome

#=======================================================================
proxy-groups:
  - name: "PROXY" 
    type: select
    proxies:
      - Vision-REALITY
====================================================
rule-providers:

#=======================================================================
rules:
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,icloud@cn,DIRECT
  - GEOSITE,apple@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,facebook,PROXY
  - GEOSITE,youtube,PROXY
  #- GEOSITE,geolocation-!cn,PROXY
  - GEOIP,telegram,PROXY,no-resolve
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,cn,DIRECT
  - GEOSITE,geolocation-cn,DIRECT
  - MATCH,PROXY
```
