### ISSUE TITLE
测试1.14.3 Reality连接不成功

### ISSUE THREAD

**Issue by yoohooyoo** [MetaCubeX/Clash.Meta#476]
Xray Core1.8.0pre做服务端，
通过Xray Core已经连接成功。
使用Meta Core做客户端，服务端报错误如下：
```
hs.c.conn == conn: false
handled: false
```
配置如下：
```
- name: "Reality"
  type: vless
  server: x.x.x.x
  port: 443
  uuid: _a uuid_
  network: tcp
  tls: true
  udp: true
  flow: xtls-rprx-vision
  servername: _a servername_
  client-fingerprint: chrome
  reality-ops:
    public-key: _a pubkey_
    short-id: 
```
