### ISSUE TITLE
[Bug] fakeip模式中取消ipv6解析无效

### ISSUE THREAD

**Issue by chummumm** [MetaCubeX/Clash.Meta#484]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-g2f992e9

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
ipv6: true
interface-name: pppoe-WAN
geodata-mode: true
geodata-loader: standard
tcp-concurrent: true
global-client-fingerprint: random
dns:  enable: true
  ipv6: false
  enhanced-mode: fake-ip
```

### Description

fakeip模式下取消ipv6 dns解析无效
![](https://user-images.githubusercontent.com/50511147/229683362-3e34151d-ae7c-41bf-acde-0f92239ef8f1.png)

![](https://user-images.githubusercontent.com/50511147/229683258-05906050-7d65-403e-9292-4db39eb8eebc.png)

![](https://user-images.githubusercontent.com/50511147/229683275-7c800392-12dc-46b9-9ff2-37f965a9251a.png)
