### ISSUE TITLE
[Bug] Can't connect internet on Android arm64

### ISSUE THREAD

**Issue by JeelsBoobz** [MetaCubeX/Clash.Meta#485]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://clash-meta.wiki/) 并无法自行解决问题 I have read the [documentation](https://clash-meta.wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Alpha latest

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
tproxy-port: 9669
mode: 'rule'
allow-lan: true
unified-delay: true
bind-address: "*"
log-level: silent
ipv6: false
inbound-tfo: true
geodata-mode: true
tcp-concurrent: true
external-controller: 0.0.0.0:9090
external-ui: ./dashboard/razord
secret: ""
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
hosts:
  'jeelsboobz.id': 127.0.0.1
profile:
  store-selected: false
  store-fake-ip: false
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter: []
  nameserver:
    - 8.8.8.8
    - 8.8.4.4
  fallback-filter:
    geoip: false
    geoip-code: 'CN'
    geosite: []
    domain: []
    ipcidr: []
sniffer:
  enable: true
  override-destination: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  sniffing:
    - tls
    - http
  port-whitelist:
    - 80
    - 443
  skip-domain: []
  force-domain: []
tun:
  enable: false
  device: utun
  stack: system
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: false
  auto-detect-interface: false
iptables: {enable: false}
interface-name: ""
process-name: true
find-process-mode: strict
proxies:
proxy-groups:
  - name: DEFAULT
    type: select
    url: http://connectivitycheck.gstatic.com/generate_204
    interval: 120
    tolerance: 150
    lazy: true
    proxies:
      - SINGAPORE
      - INDONESIA
      - DIRECT
    use:
      - BYPASSER
      - HOWDY
      - CASPER
      - GLOBAL-ID
      - GLOBAL-SG
  - name: GAMING
    type: select
    url: http://connectivitycheck.gstatic.com/generate_204
    interval: 120
    tolerance: 150
    lazy: true
    proxies:
      - DIRECT
      - INDONESIA
      - SINGAPORE
    use:
      - HOWDY
      - CASPER
      - GLOBAL-ID
      - GLOBAL-SG
  - name: INDONESIA
    type: url-test
    strategy: sticky-sessions
    url: http://connectivitycheck.gstatic.com/generate_204
    interval: 120
    tolerance: 150
    lazy: true
    filter: "ID|🇮🇩"
    use:
      - HOWDY
      - CASPER
      - GLOBAL-ID
  - name: SINGAPORE
    type: load-balance
    strategy: sticky-sessions
    url: http://connectivitycheck.gstatic.com/generate_204
    interval: 120
    tolerance: 150
    lazy: true
    filter: "SG|🇸🇬"
    use:
      - BYPASSER
      - HOWDY
      - CASPER
      - GLOBAL-SG
  - name: HOTSPOT
    type: select
    proxies:
      - REJECT
      - PASS
  - name: ADS
    type: select
    proxies:
      - REJECT
      - PASS
proxy-providers:
  BYPASSER:
    type: file
    interval: 21600
    path: ./confs/proxy-set/bypasser.xl
    health-check:
      enable: true
      interval: 120
      lazy: true
      url: http://connectivitycheck.gstatic.com/generate_204
  HOWDY:
    type: file
    interval: 21600
    path: ./confs/proxy-set/howdy.xl
    health-check:
      enable: true
      interval: 120
      lazy: true
      url: http://connectivitycheck.gstatic.com/generate_204
  CASPER:
    type: file
    interval: 21600
    path: ./confs/proxy-set/casper.xl
    health-check:
      enable: true
      interval: 120
      lazy: true
      url: http://connectivitycheck.gstatic.com/generate_204
  GLOBAL-ID:
    type: http
    interval: 21600
    path: ./confs/proxy-set/global-id.xl
    url: "https://jeelsboobz.cloudaccess.host/clash/account/global?vpn=trojan,vmess,vless&cc=ID&exclude=Akamai,AMAZON,Contabo&network=ws&tls=1&mode=sni&sni=meet.google.com&limit=3"
    health-check:
      enable: true
      interval: 120
      lazy: true
      url: http://connectivitycheck.gstatic.com/generate_204
  GLOBAL-SG:
    type: http
    interval: 21600
    path: ./confs/proxy-set/global-sg.xl
    url: "https://jeelsboobz.cloudaccess.host/clash/account/global?vpn=trojan,vmess,vless&cc=SG&exclude=Akamai,AMAZON,Contabo,ORACLE&network=ws&tls=1&mode=sni&sni=meet.google.com&limit=3"
    health-check:
      enable: true
      interval: 120
      lazy: true
      url: http://connectivitycheck.gstatic.com/generate_204
rule-providers:
  CATEGORY-BASIC-ADS:
    type: http
    behavior: domain
    interval: 86400
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_basicads.yaml
    path: ./confs/rule-set/rule_basicads.yaml
  WhatsApp:
    type: http
    behavior: classical
    interval: 86400
    url: https://pastebin.com/raw/huZ6fA1A
    path: ./confs/rule-set/whatsapp.yaml
rules:
  # AdBlock
  - GEOSITE,CATEGORY-ADS,ADS
  - GEOSITE,CATEGORY-ADS-ALL,ADS
  - RULE-SET,CATEGORY-BASIC-ADS,ADS
  # Whatsapp
  - RULE-SET,WhatsApp,DIRECT
  # Shortlink
  - DOMAIN-SUFFIX,semawur.com,INDONESIA
  # BYPASS GAME
  - OR,((DOMAIN-KEYWORD,.qq.com),(DOMAIN-KEYWORD,.ludashi.com),(DOMAIN-KEYWORD,.anticheatexpert.com)),REJECT
  # GAME DATA
  - OR,((DOMAIN-KEYWORD,.tdatamaster.com),(DOMAIN-KEYWORD,.itopsdk.com),(DOMAIN-KEYWORD,.listdl.com),(DOMAIN-KEYWORD,.amsoveasea.com)),DEFAULT
  # CODM GARENA
  - DOMAIN-KEYWORD,dl.codm.cdn.garenanow.com,DEFAULT
  - OR,((DOMAIN-KEYWORD,.connect.garenanow.com),(DOMAIN-KEYWORD,.connect.garena.com)),INDONESIA
  - OR,((UID,10208),(PROCESS-NAME,com.garena.game.codm)),GAMING
  # PUBGM
  - DOMAIN-KEYWORD,ping.igamecj.com,GAMING
  - DOMAIN-KEYWORD,.gcloudcs.com,GAMING
  - OR,((DOMAIN-KEYWORD,.gjacky.com),(DOMAIN-KEYWORD,file.igamecj.com)),DEFAULT
  - OR,((UID,10235),(PROCESS-NAME,com.tencent.ig),(PROCESS-NAME,com.pubg.krmobile)),GAMING
  # Mobile Legends
  - OR,((DOMAIN-KEYWORD,ip.ml.youngjoygame.com),(DOMAIN-KEYWORD,newlogin.ml.youngjoygame.com)),INDONESIA
  - DOMAIN-KEYWORD,.youngjoygame.com,DEFAULT
  - OR,((PROCESS-NAME,com.mobile.legends),(PROCESS-NAME,com.mobile.legends:UnityKillsMe)),GAMING
  # Hotspot
  - SRC-IP-CIDR,192.168.43.0/24,HOTSPOT
  # Default
  - IP-CIDR,127.0.0.1/32,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - MATCH,DEFAULT
```

### Description

After run clash, and all proxies connected
But can't browsing internet
