### ISSUE TITLE
[Bug] Android使用Tun运行几分钟后便不可用

### ISSUE THREAD

**Issue by csy19960309** [MetaCubeX/Clash.Meta#488]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://clash-meta.wiki/) 并无法自行解决问题 I have read the [documentation](https://clash-meta.wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta alpha-ae722bb android arm64 with go1.20.2 Wed Apr  5 05:53:15 UTC 2023 Use tags: with_low_memory, with_gvisor

### Clash config

```yaml
tproxy-port: 7893
mixd-prot: 7890
allow-lan: true
geodata-mode: false
unified-delay: false
mode: rule
log-level: info
ipv6: false
udp: true
tcp-concurrent: false
enable-process: false

sniffer:
  enable: false
  sniffing:
    - tls
    - http
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
    - '+.apple.com'
    - '*.baidu.com'
  force-domain:
    - '+'
    - 'google.com'  
  port-whitelist:
    - 80
    - 443
    - 8000-9000


profile:
  store-fake-ip: true
  store-selected: true
external-controller: 0.0.0.0:9090
external-ui: clash-dashboard/dist

tun:
  enable: true
  device: Meta
  stack: system # gvisor
  dns-hijack:
    - any:53
  auto-route: true
  auto-detect-interface: true
# 技术原因，enable必须在tun:的下一行

dns:
  enable: true
  #listen: 127.0.0.1:8853
  default-nameserver:
    - 223.5.5.5
    - 1.0.0.1
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*.lan"
    - stun.*.*.*
    - stun.*.*
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - time.asia.apple.com
    - "*.ntp.org.cn"
    - "*.openwrt.pool.ntp.org"
    - time1.cloud.tencent.com
    - time.ustc.edu.cn
    - pool.ntp.org
    - ntp.ubuntu.com
    - ntp.aliyun.com
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - ntp3.aliyun.com
    - ntp4.aliyun.com
    - ntp5.aliyun.com
    - ntp6.aliyun.com
    - ntp7.aliyun.com
    - time1.aliyun.com
    - time2.aliyun.com
    - time3.aliyun.com
    - time4.aliyun.com
    - time5.aliyun.com
    - time6.aliyun.com
    - time7.aliyun.com
    - "*.time.edu.cn"
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.ipv6.microsoft.com"
    - "*.*.xboxlive.com"
    - speedtest.cros.wr.pvp.net
  nameserver:
    - https://223.6.6.6/dns-query
    - https://dns.pub/dns-query
    - https://doh.360.cn/dns-query
  fallback:
    - https://public.dns.iij.jp/dns-query
    - https://jp.tiar.app/dns-query
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com
      - +.weixin.qq.com
      - +.bing.com
```

### Clash log

time="2023-04-06T11:05:37.317285188Z" level=debug msg="[DNS] resolve conn-service-in-03.allawnos.com from https://doh.360.cn:443/dns-query"
time="2023-04-06T11:05:37.317949355Z" level=debug msg="[DNS] resolve conn-service-in-03.allawnos.com from https://223.6.6.6:443/dns-query"
time="2023-04-06T11:05:37.318281959Z" level=debug msg="[DNS] resolve conn-service-in-03.allawnos.com from https://dns.pub:443/dns-query"
time="2023-04-06T11:05:37.333624407Z" level=debug msg="[DNS] conn-service-in-03.allawnos.com --> [129.227.29.114 129.227.195.164], from https://223.6.6.6:443/dns-query"
time="2023-04-06T11:05:37.334414042Z" level=debug msg="[DNS] conn-service-in-03.allawnos.com --> 129.227.29.114"
time="2023-04-06T11:05:37.337110397Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:05:37.341333209Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:05:37.344961855Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:05:37.714700553Z" level=info msg="[TCP] 198.18.0.1:47356 --> conn-service-in-03.allawnos.com:80 match GeoIP(CN) using China-Websites[DIRECT]"
time="2023-04-06T11:05:43.346112165Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:26635"
time="2023-04-06T11:05:43.350358936Z" level=debug msg="[Rule] use default rules"
time="2023-04-06T11:05:43.364061332Z" level=info msg="[UDP] 198.18.0.1:38348(com.google.android.apps.photos, uid=10246) --> photos.googleapis.com:443 match DomainSuffix(googleapis.com) using 🌐 Google[🇯🇵 JPN 01]"
time="2023-04-06T11:05:44.716403519Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:05:45.493129404Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:43846"
time="2023-04-06T11:05:45.499220394Z" level=debug msg="[Rule] use default rules"
time="2023-04-06T11:05:45.499519977Z" level=debug msg="[DNS] conn-service-in-03.allawnos.com --> 129.227.195.164"
time="2023-04-06T11:05:45.502246591Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:05:45.509912373Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:05:45.51289305Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:05:45.880884039Z" level=info msg="[TCP] 198.18.0.1:43278 --> conn-service-in-03.allawnos.com:80 match GeoIP(CN) using China-Websites[DIRECT]"
time="2023-04-06T11:05:47.313851226Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:05:50.41327784Z" level=debug msg="[Rule] use default rules"
time="2023-04-06T11:05:50.417811694Z" level=debug msg="[Process] find process 183.131.147.29: process not found"
time="2023-04-06T11:05:50.421372475Z" level=debug msg="[Process] find process 183.131.147.29: process not found"
time="2023-04-06T11:05:50.425346069Z" level=debug msg="[Process] find process 183.131.147.29: process not found"
time="2023-04-06T11:05:50.451067892Z" level=info msg="[TCP] 198.18.0.1:49444 --> 183.131.147.29:443 match GeoIP(CN) using China-Websites[DIRECT]"
time="2023-04-06T11:05:51.563631172Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:59819"
time="2023-04-06T11:05:51.575056068Z" level=debug msg="[Rule] use default rules"
time="2023-04-06T11:05:51.575353256Z" level=debug msg="[DNS] conn-service-in-03.allawnos.com --> 129.227.29.114"
time="2023-04-06T11:05:51.578208464Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:05:51.58246487Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:05:51.585275704Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:05:52.070050026Z" level=info msg="[TCP] 198.18.0.1:47072 --> conn-service-in-03.allawnos.com:80 match GeoIP(CN) using China-Websites[DIRECT]"
time="2023-04-06T11:05:53.347253932Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:05:55.494534608Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:06:01.569195439Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:06:03.761265282Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:59047"
time="2023-04-06T11:06:03.768987939Z" level=debug msg="[Rule] use default rules"
time="2023-04-06T11:06:03.769417053Z" level=debug msg="[DNS] resolve play.googleapis.com from https://jp.tiar.app:443/dns-query"
time="2023-04-06T11:06:03.769853459Z" level=debug msg="[DNS] resolve play.googleapis.com from https://public.dns.iij.jp:443/dns-query"
time="2023-04-06T11:06:03.913193616Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:49052"
time="2023-04-06T11:06:03.922114814Z" level=debug msg="[Rule] use default rules"
time="2023-04-06T11:06:03.922404553Z" level=debug msg="[DNS] conn-service-in-03.allawnos.com --> 129.227.29.114"
time="2023-04-06T11:06:03.925525022Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:06:03.933074762Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:06:03.936623095Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:06:04.08213148Z" level=debug msg="[DNS] play.googleapis.com --> [172.217.161.74 172.217.26.234 142.250.198.10 142.250.199.106 172.217.175.106 172.217.175.234 216.58.220.106 172.217.175.42 142.250.196.106 142.250.196.138 142.251.222.10 142.251.222.42 216.58.220.138 142.251.42.138 142.251.42.170 142.251.42.202], from https://public.dns.iij.jp:443/dns-query"
time="2023-04-06T11:06:04.082495282Z" level=debug msg="[DNS] play.googleapis.com --> 142.251.222.42"
time="2023-04-06T11:06:04.08663872Z" level=debug msg="[Process] find process play.googleapis.com: process not found"
time="2023-04-06T11:06:04.090432314Z" level=debug msg="[Process] find process play.googleapis.com: process not found"
time="2023-04-06T11:06:04.113055959Z" level=info msg="[TCP] 198.18.0.1:43316 --> play.googleapis.com:443 match DomainSuffix(googleapis.com) using 🌐 Google[🇯🇵 JPN 01]"
time="2023-04-06T11:06:04.307862678Z" level=info msg="[TCP] 198.18.0.1:37306 --> conn-service-in-03.allawnos.com:80 match GeoIP(CN) using China-Websites[DIRECT]"
time="2023-04-06T11:06:09.947713145Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:47559"
time="2023-04-06T11:06:09.952854759Z" level=debug msg="[Rule] use default rules"
time="2023-04-06T11:06:09.953102415Z" level=debug msg="[DNS] conn-service-in-03.allawnos.com --> 129.227.29.114"
time="2023-04-06T11:06:09.955879811Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:06:09.96046028Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:06:09.964752884Z" level=debug msg="[Process] find process conn-service-in-03.allawnos.com: process not found"
time="2023-04-06T11:06:10.333754759Z" level=info msg="[TCP] 198.18.0.1:37310 --> conn-service-in-03.allawnos.com:80 match GeoIP(CN) using China-Websites[DIRECT]"
time="2023-04-06T11:06:11.34601455Z" level=debug msg="[Rule] use default rules"
time="2023-04-06T11:06:11.382852571Z" level=debug msg="[Rule] use default rules"
time="2023-04-06T11:06:11.415865279Z" level=info msg="[TCP] 198.18.0.1:38054(com.tencent.mm, uid=10461) --> 117.89.176.31:80 match GeoIP(CN) using China-Websites[DIRECT]"
time="2023-04-06T11:06:11.441244654Z" level=info msg="[TCP] 198.18.0.1:38058(com.tencent.mm, uid=10461) --> 117.89.176.31:80 match GeoIP(CN) using China-Websites[DIRECT]"
time="2023-04-06T11:06:13.763282622Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:06:13.914447414Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:06:19.948184182Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:06:43.257024851Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:9846"
time="2023-04-06T11:06:48.673585473Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:3754"
time="2023-04-06T11:06:51.660949116Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:53063"
time="2023-04-06T11:06:57.475449892Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:07:10.260929257Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:07:14.096481389Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:07:15.010914201Z" level=debug msg="ipv4: tcp: session not found: 10167"
time="2023-04-06T11:07:19.486607584Z" level=debug msg="ipv4: tcp: session not found: 10167"
time="2023-04-06T11:07:26.48243633Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:17611"
time="2023-04-06T11:07:34.215622264Z" level=debug msg="[Rule] use default rules"
time="2023-04-06T11:07:34.219624348Z" level=debug msg="[Process] find process 192.168.2.210: process not found"
time="2023-04-06T11:07:34.222038306Z" level=debug msg="[Process] find process 192.168.2.210: process not found"
time="2023-04-06T11:07:34.225371066Z" level=debug msg="[Process] find process 192.168.2.210: process not found"
time="2023-04-06T11:07:34.242249868Z" level=info msg="[TCP] 198.18.0.1:40902 --> 192.168.2.210:8009 match IPCIDR(192.168.0.0/16) using China-Websites[DIRECT]"
time="2023-04-06T11:07:36.483923565Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:07:39.588873304Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:28405"
time="2023-04-06T11:07:39.844844397Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:44164"
time="2023-04-06T11:07:43.758166011Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:7020"
time="2023-04-06T11:07:43.760021636Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:59353"
time="2023-04-06T11:07:46.25036127Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:28725"
time="2023-04-06T11:07:46.252642833Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:30744"
time="2023-04-06T11:07:48.520370384Z" level=debug msg="ipv4: tcp: session not found: 10007"
time="2023-04-06T11:07:49.590105488Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:07:49.846463456Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:07:50.152055383Z" level=debug msg="ipv4: tcp: session not found: 10007"
time="2023-04-06T11:07:50.285888769Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:43600"
time="2023-04-06T11:07:50.433291373Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:63810"
time="2023-04-06T11:07:51.423258039Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:40669"
time="2023-04-06T11:07:53.758980955Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:07:53.761351111Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:07:56.270767672Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:07:56.272525224Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:07:57.364128713Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:6281"
time="2023-04-06T11:08:01.824168137Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:08:01.97149621Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:08:02.715194283Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:20083"
time="2023-04-06T11:08:02.96173246Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:08:04.427186105Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:2383"
time="2023-04-06T11:08:04.433101105Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:36688"
time="2023-04-06T11:08:08.886787145Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:08:10.458458186Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:25740"
time="2023-04-06T11:08:10.46034553Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:14385"
time="2023-04-06T11:08:12.71608782Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:08:12.960658914Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:8636"
time="2023-04-06T11:08:12.962634539Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:25961"
time="2023-04-06T11:08:14.428351726Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:08:14.43490782Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:08:20.459895161Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:08:20.461074328Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:08:22.961856775Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:08:22.963076254Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:08:24.288042504Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:59721"
time="2023-04-06T11:08:34.288532135Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:08:35.317058489Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:27166"
time="2023-04-06T11:08:45.318931193Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:08:52.165629107Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:27854"
time="2023-04-06T11:08:52.919602857Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:23221"
time="2023-04-06T11:08:52.95888942Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:45385"
time="2023-04-06T11:08:58.245845772Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:14297"
time="2023-04-06T11:09:02.168777177Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:09:02.920464416Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:09:02.95981926Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:09:08.247223268Z" level=warning msg="Tun listener get error: i/o timeout"
time="2023-04-06T11:09:16.908927796Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:53862"
time="2023-04-06T11:09:17.594478785Z" level=debug msg="[DNS] hijack udp:192.168.2.1:53 from 198.18.0.1:59790"
time="2023-04-06T11:09:18.827526858Z" level=warning msg="Clash shutting down"

### Description

虽然开始有大量Tun listener get error: i/o timeout但仍然可以使用，过几分钟后便只有dns hijack的打印了。
内核版本是5.15.41-android13-8-00002-g7bf0e80200db-ab9478255.
