### ISSUE TITLE
[Bug] Hysteria的FakeTCP模式似乎走了Clash的DIRECT通道，无法连通服务器

### ISSUE THREAD

**Issue by Mars160** [MetaCubeX/Clash.Meta#494]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [x]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://clash-meta.wiki/) 并无法自行解决问题 I have read the [documentation](https://clash-meta.wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-1dbefc4

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
- name: FakeTCP
  type: hysteria
  server: address
  port: port
  protocol: faketcp
  auth_str: Password
  up: 14
  down: 73
  udp: true
  alpn:
  - h3
```

### Description

Hysteria的FakeTCP模式似乎走了Clash的DIRECT通道，无法连通服务器
