### ISSUE TITLE
[Bug] 从P核换Meta后，Destination IP上很多空白

### ISSUE THREAD

**Issue by Rakau** [MetaCubeX/Clash.Meta#499]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://clash-meta.wiki/) 并无法自行解决问题 I have read the [documentation](https://clash-meta.wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.14.3

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "+.lan"
  - "+.local"
  - "+.localhost"
  - "+.msftncsi.com"
  - msftncsi.com
  - msftconnecttest.com
  - "+.msftconnecttest.com"
  - "+.io.mi.com"
  - connect.rom.miui.com
  - lens.l.google.com
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - "+.srv.nintendo.net"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  nameserver:
  - tls://119.29.29.29:853
  - tls://223.5.5.5:853
  - tls://180.76.76.76:853
  fallback:
  - tls://8.8.8.8:853
  - tls://1.1.1.1:853
  - tls://101.101.101.101:853
  fallback-filter:
    geoip: true
    geoip-code: CN
```

### Description

同样的配置在box4上和openclsh上都出现了Destination IP很多空白，我是从P核换过来的，P核正常
