### ISSUE TITLE
[Bug] skip-cert-verify: 选项是如何工作的？

### ISSUE THREAD

**Issue by Azuriye** [MetaCubeX/Clash.Meta#501]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://clash-meta.wiki/) 并无法自行解决问题 I have read the [documentation](https://clash-meta.wiki/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.4.3

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
unified-delay: false
geodata-mode: true
tcp-concurrent: false
find-process-mode: strict
global-client-fingerprint: chrome

allow-lan: true
mode: rule
bind-address: "*"
log-level: info
ipv6: true

external-controller: 0.0.0.0:9090
secret: ""

geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

profile:
  store-selected: true
  store-fake-ip: true

tun:
  enable: true
  stack: system 
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true
  strict_route: true

experimental:
  interface-name: en0

dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
  fallback:
    - 1.0.0.1
    - 8.8.4.4

proxies:
  - name: "vless-vision"
    type: vless
    server: example.com
    port: 443
    uuid: uuid
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    client-fingerprint: chrome

proxy-groups:
  - name: AzuriyeMain
    type: select
    proxies:
      - vless-vision

rules:
  - PROCESS-NAME,Discord.exe,AzuriyeMain
  - PROCESS-NAME,DiscordPTB.exe,AzuriyeMain
  - IN-TYPE,SOCKS,AzuriyeMain
  - MATCH, DIRECT
```

### Clash log

```shell
12/04/2023 00:13:44 Refresh Clash Proxies
time="2023-04-12T00:13:44.9463277+04:00" level=warning msg="[TCP] dial AzuriyeMain (match Process/Discord.exe) 198.18.0.1:18576(Discord.exe) --> updates.discord.com:443 error: example.com:443 connect error: x509: certificate is valid for wwwqa.microsoft.com, www.microsoft.com, staticview.microsoft.com, i.s-microsoft.com, microsoft.com, c.s-microsoft.com, privacy.microsoft.com, not example.com"
time="2023-04-12T00:13:46.3140939+04:00" level=warning msg="[TCP] dial AzuriyeMain (match Process/Discord.exe) 198.18.0.1:18592(Discord.exe) --> discord.com:443 error: example.com:443 connect error: x509: certificate is valid for wwwqa.microsoft.com, www.microsoft.com, staticview.microsoft.com, i.s-microsoft.com, microsoft.com, c.s-microsoft.com, privacy.microsoft.com, not example.com"
time="2023-04-12T00:13:51.1640944+04:00" level=warning msg="[UDP] dial AzuriyeMain (match Process/Discord.exe) 198.18.0.1:61744(Discord.exe) --> api.spotify.com:443 error: new vless client error: x509: certificate is valid for wwwqa.microsoft.com, www.microsoft.com, staticview.microsoft.com, i.s-microsoft.com, microsoft.com, c.s-microsoft.com, privacy.microsoft.com, not example.com"
time="2023-04-12T00:13:51.7125937+04:00" level=warning msg="[TCP] dial AzuriyeMain (match Process/Discord.exe) 198.18.0.1:18606(Discord.exe) --> api.spotify.com:443 error: example.com:443 connect error: x509: certificate is valid for wwwqa.microsoft.com, www.microsoft.com, staticview.microsoft.com, i.s-microsoft.com, microsoft.com, c.s-microsoft.com, privacy.microsoft.com, not example.com"
time="2023-04-12T00:13:51.8125966+04:00" level=warning msg="[TCP] dial AzuriyeMain (match Process/Discord.exe) 198.18.0.1:18609(Discord.exe) --> i.scdn.co:443 error: example.com:443 connect error: x509: certificate is valid for wwwqa.microsoft.com, www.microsoft.com, staticview.microsoft.com, i.s-microsoft.com, microsoft.com, c.s-microsoft.com, privacy.microsoft.com, not example.com"
time="2023-04-12T00:13:51.8130943+04:00" level=warning msg="[TCP] dial AzuriyeMain (match Process/Discord.exe) 198.18.0.1:18608(Discord.exe) --> i.scdn.co:443 error: example.com:443 connect error: x509: certificate is valid for wwwqa.microsoft.com, www.microsoft.com, staticview.microsoft.com, i.s-microsoft.com, microsoft.com, c.s-microsoft.com, privacy.microsoft.com, not example.com"
time="2023-04-12T00:13:52.3750948+04:00" level=warning msg="[TCP] dial AzuriyeMain (match Process/Discord.exe) 198.18.0.1:18608(Discord.exe) --> i.scdn.co:443 error: example.com:443 connect error: x509: certificate is valid for wwwqa.microsoft.com, www.microsoft.com, staticview.microsoft.com, i.s-microsoft.com, microsoft.com, c.s-microsoft.com, privacy.microsoft.com, not example.com"
time="2023-04-12T00:13:52.3795937+04:00" level=warning msg="[TCP] dial AzuriyeMain (match Process/Discord.exe) 198.18.0.1:18609(Discord.exe) --> i.scdn.co:443 error: example.com:443 connect error: x509: certificate is valid for wwwqa.microsoft.com, www.microsoft.com, staticview.microsoft.com, i.s-microsoft.com, microsoft.com, c.s-microsoft.com, privacy.microsoft.com, not example.com"
time="2023-04-12T00:13:52.9502648+04:00" level=warning msg="[TCP] dial AzuriyeMain (match Process/Discord.exe) 198.18.0.1:18609(Discord.exe) --> i.scdn.co:443 error: example.com:443 connect error: x509: certificate is valid for wwwqa.microsoft.com, www.microsoft.com, staticview.microsoft.com, i.s-microsoft.com, microsoft.com, c.s-microsoft.com, privacy.microsoft.com, not example.com"
time="2023-04-12T00:13:54.7104741+04:00" level=warning msg="[TCP] dial AzuriyeMain (match Process/Discord.exe) 198.18.0.1:18630(Discord.exe) --> latency.discord.media:443 error: example.com:443 connect error: x509: certificate is valid for wwwqa.microsoft.com, www.microsoft.com, staticview.microsoft.com, i.s-microsoft.com, microsoft.com, c.s-microsoft.com, privacy.microsoft.com, not example.com"
```

### Description

你好，我正在使用DeepL 来翻译... 我想知道skip-cert-verify选项如何工作，因为...

当我把它设置为真时，我不再得到x509：证书对example.com有效，而不是www.microsoft.com，有时则相反（对www.microsoft.com有效，而不是example.com）。

但我注意到的是，当我把它设置为 "真 "时，由于某种原因，互联网变得非常慢，所以我不确定这个选项到底是如何工作的......

当我禁用该选项或完全删除该行时，我在日志选项卡中得到那些x509警告，但互联网现在工作得很快，这很奇怪，因为该选项主要用于启用或禁用证书验证。

希望这里有人能就这个选项给我更多的启发......

谢谢你提供的这个很棒的软件!

==================================================================================
Hello, I am using DeepL to translate... I wanted to know how skip-cert-verify option works because...

When I set it to true I no longer get x509: certificate is valid for example.com, not [www.microsoft.com](http://www.microsoft.com/) and sometimes the other way around (valid for [www.microsoft.com](http://www.microsoft.com/), not example.com)

But what I've noticed is that when I set it to true for some reason internet becomes very slow so I am not sure how this option really works...

When I disable this option or just completely remove the line I get those x509 warnings in the logs tab but the internet works fast now which is so odd when this option is mostly used for enabling or disabling certificate verification

Hopefully, someone here could enlighten me more regarding this option...

Thank you for this awesome software as well!
