### ISSUE TITLE
[Bug] Meta内核无法选中配置文件，报本地连接错误

### ISSUE THREAD

**Issue by PingZi-Wing** [MetaCubeX/Clash.Meta#504]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.14.3

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mode: rule
mixed-port: 7890
allow-lan: false
log-level: info
ipv6: true
secret: ''
external-controller: 127.0.0.1:9090
dns:
  enable: false
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
  - 8.8.8.8
  - 119.29.29.29
  nameserver-policy:
    blog.google: 119.29.29.29
    googletraveladservices.com: 119.29.29.29
    dl.l.google.com: 119.29.29.29
    clientservices.googleapis.com: 119.29.29.29
    update.googleapis.com: 119.29.29.29
    translate.googleapis.com: 119.29.29.29
    fonts.googleapis.com: 119.29.29.29
    fonts.gstatic.com: 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:
  - '*.lan'
  - '*.linksys.com'
  - '*.linksyssmartwifi.com'
  - swscan.apple.com
  - mesu.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - xbox.*.microsoft.com
  - xbox.*.*.microsoft.com
  - +.xboxlive.com
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - '*.time.edu.cn'
  - '*.ntp.org.cn'
  - +.pool.ntp.org
  - time1.cloud.tencent.com
  - lens.l.google.com
  - +.music.163.com
  - +.126.net
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - '*.kuwo.cn'
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - +.y.qq.com
  - +.music.tc.qq.com
  - aqqmusic.tc.qq.com
  - +.stream.qqmusic.qq.com
  - +.xiami.com
  - +.music.migu.cn
  - +.stun.*.*
  - +.stun.*.*.*
  - +.stun.*.*.*.*
  - +.stun.*.*.*.*.*
  - +.srv.nintendo.net
  - '*.n.n.srv.nintendo.net'
  - +.stun.playstation.net
  - +.battlenet.com.cn
  - +.wotgame.cn
  - +.wggames.cn
  - +.wowsgame.cn
  - +.wargaming.net
  - '*.square-enix.com'
  - '*.finalfantasyxiv.com'
  - '*.ffxiv.com'
  - '*.ff14.sdo.com'
  - ff.dorado.sdo.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - proxy.golang.org
  - +.qq.com
  - +.baidu.com
  - +.163.com
  - +.126.net
  - +.taobao.com
  - +.jd.com
  - +.tmall.com
  - '*.mcdn.bilivideo.cn'
  - +.nvidia.com
  - +.nvidia.cn
  - +.nvgs.nvidia.com
  - +.nvgs.nvidia.cn
  - shark007.net
  proxy-server-nameserver:
  - https://doh-clash.doh.pub/dns-query
  nameserver:
  - dhcp://en0
  - dhcp://en1
  - 223.5.5.5
  fallback:
  - https://doh--clash.doh.pub/dns-query
  fallback-filter:
    ipcidr:
    - 240.0.0.0/4
    - 127.0.0.1
    - 0.0.0.0/32
hosts:
  talk.google.com: 108.177.125.188
  mtalk.google.com: 108.177.125.188
  alt1-mtalk.google.com: 3.3.3.3
  alt2-mtalk.google.com: 3.3.3.3
  alt3-mtalk.google.com: 74.125.200.188
  alt4-mtalk.google.com: 74.125.200.188
  alt5-mtalk.google.com: 3.3.3.3
  alt6-mtalk.google.com: 3.3.3.3
  alt7-mtalk.google.com: 74.125.200.188
  alt8-mtalk.google.com: 3.3.3.3
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: false
  sniffing:
  - tls
  - http
  skip-domain:
  - Mijia Cloud
  - dlg.io.mi.com
  - +.apple.com
  force-domain:
  - google.com
  - '*.netflix.com.com'
proxies: null
proxy-groups:
- name: 🚀 默认节点
  type: select
  proxies:
  - 🇭🇰 香港节点优选
  - 🇯🇵 日本节点优选
  - 🇸🇬 狮城节点优选
  - 🇰🇷 韩国节点优选
  - 🇨🇳 台湾节点优选
  - 🇺🇲 美国节点优选
  - 🇨🇳 自建节点优选
  - 🎯 其他节点手选
- name: 🎯 其他节点手选
  type: select
  use:
  - 订阅机场
  - 免费节点
  filter: ^(?!.*(港|台|日|韩|坡|狮|美|HK|US|TW|JP|KR|SG|Hong|Tai|Japan|Korea|Singapore|States))
- name: 🌍 国际媒体
  type: select
  proxies:
  - 🚀 默认节点
  - DIRECT
  - 🇭🇰 香港节点优选
  - 🇯🇵 日本节点优选
  - 🇸🇬 狮城节点优选
  - 🇰🇷 韩国节点优选
  - 🇨🇳 台湾节点优选
  - 🇺🇲 美国节点优选
- name: 📺 港台B站
  type: select
  proxies:
  - DIRECT
  - 🚀 默认节点
  - 🇭🇰 香港节点优选
  - 🇨🇳 台湾节点优选
- name: ☁️ 微软云盘
  type: select
  proxies:
  - 🚀 默认节点
  - DIRECT
- name: Ⓜ️ 微软服务
  type: select
  proxies:
  - DIRECT
  - 🚀 默认节点
- name: 🍎 苹果服务
  type: select
  proxies:
  - DIRECT
  - 🚀 默认节点
- name: 🍃 广告拦截
  type: select
  proxies:
  - REJECT
  - PASS
- name: 🇨🇳 自建节点优选
  type: url-test
  use:
  - 自建机场
  url: http://www.gstatic.com/generate_204
  interval: 600
  tolerance: 100
  lazy: true
- name: 🇭🇰 香港节点优选
  type: url-test
  use:
  - 订阅机场
  filter: 港|HK|Hong Kong
  url: http://www.gstatic.com/generate_204
  interval: 600
  tolerance: 100
  lazy: true
- name: 🇯🇵 日本节点优选
  type: url-test
  use:
  - 订阅机场
  - 免费节点
  filter: 日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan
  url: http://www.gstatic.com/generate_204
  interval: 600
  tolerance: 100
  lazy: true
- name: 🇸🇬 狮城节点优选
  type: url-test
  use:
  - 订阅机场
  filter: 新加坡|坡|狮城|SG|Singapore
  url: http://www.gstatic.com/generate_204
  interval: 600
  tolerance: 100
  lazy: true
- name: 🇰🇷 韩国节点优选
  type: url-test
  use:
  - 订阅机场
  - 免费节点
  filter: KR|Korea|KOR|首尔|韩|韓
  url: http://www.gstatic.com/generate_204
  interval: 600
  tolerance: 100
  lazy: true
- name: 🇨🇳 台湾节点优选
  type: url-test
  use:
  - 订阅机场
  - 免费节点
  filter: 台|新北|彰化|TW|Taiwan
  url: http://www.gstatic.com/generate_204
  interval: 600
  tolerance: 100
  lazy: true
- name: 🇺🇲 美国节点优选
  type: url-test
  use:
  - 订阅机场
  - 免费节点
  filter: 美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States
  url: http://www.gstatic.com/generate_204
  interval: 600
  tolerance: 150
  lazy: true
proxy-providers:
  自建机场:
    type: http
    path: ./proxy-providers/Own-Meta.yaml
    url: https://ghproxy.com/https://gist.githubusercontent.com/
    interval: 172800
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 900
      lazy: true
  订阅机场:
    type: http
    path: ./proxy-providers/Sub-Meta.yaml
    url: https://xn--4gq62f52gdss.com/api/v1/client
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 900
      lazy: true
  免费节点:
    type: http
    path: ./proxy-providers/free-Meta.yaml
    url: https://ghproxy.com/https://raw.githubuser
    interval: 86400
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 900
      lazy: true
rules:
- RULE-SET,Direct,DIRECT
- RULE-SET,Privacy-Domain,🍃 广告拦截
- RULE-SET,BanAD,🍃 广告拦截
- RULE-SET,BanProgramAD,🍃 广告拦截
- AND,((NETWORK,UDP),(DST-PORT,443)),REJECT
- RULE-SET,Custom_Domain,🚀 默认节点
- RULE-SET,OneDrive,☁️ 微软云盘
- RULE-SET,BilibiliHMT-Domain,📺 港台B站
- RULE-SET,GlobalMedia_Domain,🌍 国际媒体
- RULE-SET,GFW_Domain,🚀 默认节点
- RULE-SET,Apple_Domain,🍎 苹果服务
- RULE-SET,Steam,🚀 默认节点
- RULE-SET,GlobalMedia,🌍 国际媒体,no-resolve
- RULE-SET,GFW,🚀 默认节点
- RULE-SET,Hijacking,🍃 广告拦截
- RULE-SET,Privacy,🍃 广告拦截
- RULE-SET,Apple,🍎 苹果服务
- RULE-SET,Microsoft,Ⓜ️ 微软服务
- MATCH,DIRECT
rule-providers:
  Direct:
    type: http
    behavior: classical
    path: ./RuleSet/Direct.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml
    interval: 172800
  BanAD:
    type: http
    behavior: classical
    path: ./RuleSet/BanAD.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml
    interval: 172800
  BanProgramAD:
    type: http
    behavior: classical
    path: ./RuleSet/BanProgramAD.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml
    interval: 172800
  Privacy-Domain:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/PingZi-Wing/clash-rules/main/Privacy.yaml
    path: ./ruleset/Privacy-Domain.yaml
    interval: 172800
  Privacy:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy.yaml
    path: ./ruleset/blackmatrix7/Privacy.yaml
    interval: 172800
  Hijacking:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hijacking/Hijacking.yaml
    path: ./ruleset/blackmatrix7/Hijacking.yaml
    interval: 172800
  Custom_Domain:
    type: http
    behavior: domain
    path: ./RuleSet/Custom_Domain.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/PingZi-Wing/clash-rules/main/Custom_Domain.yaml
    interval: 172800
  BilibiliHMT-Domain:
    type: http
    behavior: classical
    path: ./RuleSet/BilibiliHMT-Domain.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/PingZi-Wing/clash-rules/main/BilibiliHMT-Domain.yaml
    interval: 172800
  BilibiliHMT-IP:
    type: http
    behavior: classical
    path: ./RuleSet/BilibiliHMT-IP.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/PingZi-Wing/clash-rules/main/BilibiliHMT-IP.yaml
    interval: 172800
  GlobalMedia_Domain:
    type: http
    behavior: domain
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Domain.yaml
    path: ./ruleset/blackmatrix7/GlobalMedia_Domain.yaml
    interval: 172800
  GlobalMedia:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.yaml
    path: ./ruleset/blackmatrix7/GlobalMedia.yaml
    interval: 172800
  GFW_Domain:
    type: http
    behavior: domain
    path: ./RuleSet/GFW_Domain.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
    interval: 172800
  GFW:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.yaml
    path: ./ruleset/GFW.yaml
    interval: 172800
  Apple:
    type: http
    behavior: classical
    path: ./RuleSet/blackmatrix7/Apple.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml
    interval: 172800
  Apple_Domain:
    type: http
    behavior: domain
    path: ./RuleSet/blackmatrix7/Apple_Domain.yaml
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Domain.yaml
    interval: 172800
  OneDrive:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.yaml
    path: ./RuleSet/blackmatrix7/OneDrive.yaml
    interval: 172800
  Microsoft:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./RuleSet/blackmatrix7/Microsoft.yaml
    interval: 172800
  Steam:
    type: http
    behavior: classical
    url: https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml
    path: ./RuleSet/blackmatrix7/Steam.yaml
    interval: 172800
```

### Description

之前在win平台clash verge一直在正常使用，然后在切换另一个配置文件的时候报了如下图一样的错误，后续卸载verge、重装、重新配置防火墙，还是报下图的错误，看日志内核能发起对外连接。不过使用clashN的时候，也是一样不能选中应用配置，我想应该是meta内核的问题。

https://user-images.githubusercontent.com/57025184/231965670-9231726f-0ba5-460d-afe2-7cf89bff9f7a.png
