### ISSUE TITLE
[Bug] meta内核使用wireguard无法科学上网

### ISSUE THREAD

**Issue by terryz89** [MetaCubeX/Clash.Meta#505]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v0.45.103-beta

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
wg配置文件原始信息：
# ENDPOINT 129.xxx.40.xxx
[Interface]
Address = 10.7.0.1/24
PrivateKey = yJnVQZ4bTGhH97gJX+8qPnMV3fKNKVm3E1xRzxxxx
ListenPort = 54xxx
# BEGIN_PEER wg
[Peer]
PublicKey = 8ihXK43PIFs0vkLYr+xCmZ4nT946dV+WOjL/JQ2xxxx
PresharedKey = zDxrQmQk4vEr8wtkhsMiWl3Jta+Ckk6jQiHpWnxxxx
AllowedIPs = 10.7.0.2/32
# END_PEER wg

meta配置文件信息
proxies:
  - name: "wg"
    type: wireguard
    server: 129.xxx.40.xxx
    port: 54xxx
    ip: 10.7.0.2
    public-key: 8ihXK43PIFs0vkLYr+xCmZ4nT946dV+WOjL/xxxxx
    pre-shared-key: zDxrQmQk4vEr8wtkhsMiWl3Jta+Ckk6jQiHpWnxxxx
    private-key: yJnVQZ4bTGhH97gJX+8qPnMV3fKNKVm3E1xRzr1xxxx
    udp: true
    reserved: "U4An"
```

### Description

meta内核按照规则填写wireguard信息后无法科学上网，但是使用wireguard客户端完全没有问题，希望能关注解决下。
