### ISSUE TITLE
[Bug] geoip.dat 不更新

### ISSUE THREAD

**Issue by LiXin-x** [MetaCubeX/Clash.Meta#512]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.14.3

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
geodata-mode: true
geox-url:
  geosite: "https://ghproxy.com/https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geosite.dat"
  mmdb: "https://ghproxy.com/https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb"
  geoip: "https://ghproxy.com/https://github.com/Loyalsoldier/v2ray-rules-dat/raw/release/geoip.dat"
```

### Clash log

```shell
23-04-17 22:37:36[ warn ][REST-API] update GEO databases successful, apply config...
23-04-17 22:37:36[ info ]Geodata Loader mode: memconservative
23-04-17 22:35:36[ warn ][REST-API] updating GEO databases...
```

### Description

关于 Geo 的配置如上，更新 Geo 数据库时，只有 geosite.dat 和 country.mmdb 两个文件会更新。

geoip.dat 的异常情况：

1. 无法手动更新（只能删除 ~/.config/clash/geoip.dat，重启 ClashX.Meta 自动下载）
2. 更新完 GEO 文件后，ClashX.Meta 不加载配置文件，必须重载配置文件
3. 以上两个问题 geodata-mode 在 true/false 都是一样的表现

* 测试的 Meta 版本: 1.14.3 & alpha-4c1682b

**Comment by wuwentao** [comment]
好像我也遇到这个问题，手工删除，手工下载，临时解决了

**Comment by xishang0128** [comment]
请确认你使用的客户端没有修改geodata-mode的值，或者覆写掉geodata-mode，实测正常更新使用的对应数据库

**Comment by wuwentao** [comment]
@xishang0128 多谢大佬回复，
按这么说的话，我这个配置肯定算算修改了的吧，因为文档里写的要用geoip.data，不是要把geodata-mode设为true么？

所以实际配置如下：
```yaml
geodata-mode: true
geox-url:
  geoip: "https://www.xxxxxx.xyz/clash/downloads/db/geoip.dat"
  geosite: "https://www.xxx.xyz/clash/downloads/db/geosite.dat"
  mmdb: "https://www.xxxx.xyz/clash/downloads/db/Country.mmdb"
```
url是自己把文件cache到自己架的www了，不走github了，避免无法下载的问题。
