### ISSUE TITLE
[Bug] 使用Vision Telegram挂socks5代理无法连通

### ISSUE THREAD

**Issue by myleo1** [MetaCubeX/Clash.Meta#519]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Alpha aa6fa7f

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
dns:
  enable: true
  ipv6: false
  default-nameserver: [114.114.114.114, 223.5.5.5, 8.8.4.4]
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    ["*.lan", "*.linksys.com", +.pool.ntp.org, localhost.ptlogin2.qq.co]
  use-hosts: true
  nameserver: ["https://dns.alidns.com/dns-query"]
  fallback: ["https://doh.pub/dns-query", "https://dns.google/dns-query"]
  fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32] }
proxies:
  - {
      "name": "🇯🇵 Vir|JP",
      "type": "vless",
      "server": "xxx",
      "port": 443,
      "uuid": "xxx",
      "network": tcp,
      "tls": true,
      "udp": true,
      "flow": "xtls-rprx-vision",
      "client-fingerprint": "safari",
    }
proxy-groups:
  - { name: "🔰 牧场", type: select, proxies: ["🇯🇵 Vir|JP"] }
  - { name: "📽 Netflix", type: select, proxies: ["🔰 牧场"] }
  - { name: "📺 Disney+", type: select, proxies: ["🔰 牧场"] }
  - { name: "🎬 YouTube", type: select, proxies: ["🔰 牧场"] }
  - { name: "📺 Bilibili", type: select, proxies: [DIRECT] }
  - { name: "📱 Telegram", type: select, proxies: ["🔰 牧场"] }
  - { name: "📺 动画疯", type: select, proxies: ["🔰 牧场"] }
  - { name: "⚛️ ChatGPT", type: select, proxies: ["🔰 牧场"] }
  - { name: "Ⓜ Microsoft", type: select, proxies: [DIRECT] }
  - { name: "🎯 游戏平台", type: select, proxies: [DIRECT] }
  - { name: "🍎 Apple", type: select, proxies: [DIRECT] }
  - { name: "🌎 全球代理", type: select, proxies: ["🔰 牧场"] }
  - { name: "🐟 漏网之鱼", type: select, proxies: [DIRECT, "🔰 牧场"] }
  - { name: "♻️ 自动选择", type: url-test, proxies: ["🇯🇵 Vir|JP"], tolerance: 20, lazy: true, url: "http://www.gstatic.com/generate_204", interval: 300}
rule-providers:
  Unbreak:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleUnbreak.yaml,
      url: http://xx.xx.xx.xx:32580/Clash/RuleSet/Unbreak.yaml,
      interval: 21600,
    }
  Advertising:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleAdvertising.yaml,
      url: http://xx.xx.xx.xx:32580/Clash/RuleSet/Guard/Advertising.yaml,
      interval: 21600,
    }
  Hijacking:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleHijacking.yaml,
      url: http://xx.xx.xx.xx:32580/Clash/RuleSet/Guard/Hijacking.yaml,
      interval: 21600,
    }
  Privacy:
    {
      type: http,
      behavior: classical,
      path: ./providers/rulePrivacy.yaml,
      url: http://xx.xx.xx.xx:32580/Clash/RuleSet/Guard/Privacy.yaml,
      interval: 21600,
    }
  Steam:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleGames/Steam.yaml,
      url: http://xx.xx.xx.xx:32580/ACL4SSR/Clash/Providers/Ruleset/Steam.yaml,
      interval: 21600,
    }
  Blizzard:
    {
      type: http,
      behavior: classical,
      path: ./providers/rule/Games/Blizzard.yaml,
      url: http://xx.xx.xx.xx:32580/Clash/RuleSet/Extra/Game/Blizzard.yaml,
      interval: 21600,
    }
  Nintendo:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleGames/Nintendo.yaml,
      url: http://xx.xx.xx.xx:32580/Clash/RuleSet/Extra/Game/Nintendo.yaml,
      interval: 21600,
    }
  Origin:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleGames/Origin.yaml,
      url: http://xx.xx.xx.xx:32580/Clash/RuleSet/Extra/Game/Origin.yaml,
      interval: 21600,
    }
  Xbox:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleGames/Xbox.yaml,
      url: http://xx.xx.xx.xx:32580/Clash/RuleSet/Extra/Game/Xbox.yaml,
      interval: 21600,
    }
  Epic:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleGames/Epic.yaml,
      url: http://xx.xx.xx.xx:32580/ACL4SSR/Clash/Providers/Ruleset/Epic.yaml,
      interval: 21600,
    }
  Apple:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleApple.yaml,
      url: http://xx.xx.xx.xx:32580/ACL4SSR/Clash/Providers/Ruleset/Apple.yaml,
      interval: 21600,
    }
  Telegram:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleTelegram.yaml,
      url: http://xx.xx.xx.xx:32580/ACL4SSR/Clash/Providers/Ruleset/Telegram.yaml,
      interval: 21600,
    }
  Microsoft:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleMicrosoft.yaml,
      url: http://xx.xx.xx.xx:32580/ACL4SSR/Clash/Providers/Ruleset/Microsoft.yaml,
      interval: 21600,
    }
  Bilibili:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleBilibili.yaml,
      url: http://xx.xx.xx.xx:32580/ACL4SSR/Clash/Providers/Ruleset/Bilibili.yaml,
      interval: 21600,
    }
  YouTube:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleYouTube.yaml,
      url: http://xx.xx.xx.xx:32580/ACL4SSR/Clash/Providers/Ruleset/YouTube.yaml,
      interval: 21600,
    }
  Netflix:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleNetflix.yaml,
      url: http://xx.xx.xx.xx:32580/ACL4SSR/Clash/Providers/Ruleset/Netflix.yaml,
      interval: 21600,
    }
  Disney:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleDisney.yaml,
      url: http://xx.xx.xx.xx:32580/ACL4SSR/Clash/Providers/Ruleset/DisneyPlus.yaml,
      interval: 21600,
    }
  Bahamut:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleBahamut.yaml,
      url: http://xx.xx.xx.xx:32580/Clash/RuleSet/StreamingMedia/Video/Bahamut.yaml,
      interval: 21600,
    }
  ProxyMedia:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleProxyMedia.yaml,
      url: http://xx.xx.xx.xx:32580/ACL4SSR/Clash/Providers/ProxyMedia.yaml,
      interval: 21600,
    }
  ProxyGFWlist:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleProxyGFWlist.yaml,
      url: http://xx.xx.xx.xx:32580/ACL4SSR/Clash/Providers/ProxyGFWlist.yaml,
      interval: 21600,
    }
  Global:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleGlobal.yaml,
      url: http://xx.xx.xx.xx:32580/Clash/RuleSet/Global.yaml,
      interval: 21600,
    }
  ChinaDomain:
    {
      type: http,
      behavior: classical,
      path: ./providers/ruleChinaDomain.yaml,
      url: http://xx.xx.xx.xx:32580/ACL4SSR/Clash/Providers/ChinaDomain.yaml,
      interval: 21600,
    }
  ChinaIp:
    {
      type: http,
      behavior: ipcidr,
      path: ./providers/ruleChinaIp.yaml,
      url: http://xx.xx.xx.xx:32580/ACL4SSR/Clash/Providers/ChinaIp.yaml,
      interval: 21600,
    }
rules:
  - "DOMAIN-SUFFIX,36d.biz,DIRECT"
  - "DOMAIN-SUFFIX,ss01.net,DIRECT"
  - "DOMAIN-SUFFIX,u.mcashier.xyz,DIRECT"
  - "DOMAIN-SUFFIX,36d.uk,🌎 全球代理"
  - "DOMAIN-SUFFIX,ss.mba,🌎 全球代理"
  - "IP-CIDR,192.168.0.0/16,DIRECT,no-resolve"
  - "IP-CIDR,10.0.0.0/8,DIRECT,no-resolve"
  - "IP-CIDR,172.16.0.0/12,DIRECT,no-resolve"
  - "IP-CIDR,127.0.0.0/8,DIRECT,no-resolve"
  - "IP-CIDR,100.64.0.0/10,DIRECT,no-resolve"
  - "IP-CIDR6,::1/128,DIRECT,no-resolve"
  - "IP-CIDR6,fc00::/7,DIRECT,no-resolve"
  - "IP-CIDR6,fe80::/10,DIRECT,no-resolve"
  - "IP-CIDR6,fd00::/8,DIRECT,no-resolve"
  - "RULE-SET,Unbreak,DIRECT"
  - "RULE-SET,Advertising,REJECT"
  - "RULE-SET,Hijacking,REJECT"
  - "RULE-SET,Privacy,REJECT"
  - "RULE-SET,Telegram,📱 Telegram"
  - "DOMAIN-SUFFIX,telegram.org,📱 Telegram"
  - "RULE-SET,Netflix,📽 Netflix"
  - "RULE-SET,Disney,📺 Disney+"
  - "RULE-SET,YouTube,🎬 YouTube"
  - "RULE-SET,Bilibili,📺 Bilibili"
  - "RULE-SET,Bahamut,📺 动画疯"
  - "RULE-SET,Microsoft,Ⓜ Microsoft"
  - "RULE-SET,Apple,🍎 Apple"
  - "RULE-SET,Steam,🎯 游戏平台"
  - "RULE-SET,Blizzard,🎯 游戏平台"
  - "RULE-SET,Nintendo,🎯 游戏平台"
  - "RULE-SET,Origin,🎯 游戏平台"
  - "RULE-SET,Xbox,🎯 游戏平台"
  - "RULE-SET,Epic,🎯 游戏平台"
  - "DOMAIN-SUFFIX,friday.tw,🌎 全球代理"
  - "DOMAIN-SUFFIX,twitchtracker.com,🌎 全球代理"
  - "DOMAIN-SUFFIX,theinspirationgrid.com,🌎 全球代理"
  - "DOMAIN-SUFFIX,openai.com,⚛️ ChatGPT"
  - "DOMAIN-SUFFIX,chat.openai.com,⚛️ ChatGPT"
  - "DOMAIN-SUFFIX,challenges.cloudflare.com,⚛️ ChatGPT"
  - "DOMAIN-SUFFIX,auth0.openai.com,⚛️ ChatGPT"
  - "DOMAIN-SUFFIX,platform.openai.com,⚛️ ChatGPT"
  - "DOMAIN-SUFFIX,ai.com,⚛️ ChatGPT"
  - "RULE-SET,ProxyMedia,🌎 全球代理"
  - "RULE-SET,ProxyGFWlist,🌎 全球代理"
  - "RULE-SET,Global,🌎 全球代理"
  - "RULE-SET,ChinaDomain,DIRECT"
  - "RULE-SET,ChinaIp,DIRECT"
  - "GEOIP,CN,DIRECT"
  - "MATCH,🐟 漏网之鱼"
```

### Clash log

```shell
========================
vision节点LOG:
========================
time="2023-04-23T19:53:15.879503+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=1564, paddingLen=0"
time="2023-04-23T19:53:15.879682+08:00" level=info msg="[TCP] 127.0.0.1:50015 --> 91.108.56.116:443 match RuleSet(Telegram) using 📱 Telegram[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:15.888744+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=537, paddingLen=144"
time="2023-04-23T19:53:15.888831+08:00" level=info msg="[TCP] 127.0.0.1:50017 --> 149.154.175.60:443 match RuleSet(Telegram) using 📱 Telegram[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:15.906368+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=105, paddingLen=12"
time="2023-04-23T19:53:15.906468+08:00" level=info msg="[TCP] 127.0.0.1:50029(Telegram) --> 2.0.0.0:443 match Match using 🐟 漏网之鱼[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:15.910378+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=105, paddingLen=214"
time="2023-04-23T19:53:15.910443+08:00" level=info msg="[TCP] 127.0.0.1:50027(Telegram) --> 2.0.0.0:443 match Match using 🐟 漏网之鱼[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:15.915917+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=105, paddingLen=135"
time="2023-04-23T19:53:15.916001+08:00" level=info msg="[TCP] 127.0.0.1:50030(Telegram) --> 2.0.0.0:443 match Match using 🐟 漏网之鱼[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:15.932383+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=329, paddingLen=235"
time="2023-04-23T19:53:15.932451+08:00" level=info msg="[TCP] 127.0.0.1:50016 --> 91.108.56.116:443 match RuleSet(Telegram) using 📱 Telegram[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:15.93765+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=569, paddingLen=242"
time="2023-04-23T19:53:15.937718+08:00" level=info msg="[TCP] 127.0.0.1:50018 --> 149.154.175.60:443 match RuleSet(Telegram) using 📱 Telegram[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:15.9598+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=569, paddingLen=215"
time="2023-04-23T19:53:15.959878+08:00" level=info msg="[TCP] 127.0.0.1:50020 --> 149.154.175.60:443 match RuleSet(Telegram) using 📱 Telegram[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:15.980132+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=105, paddingLen=156"
time="2023-04-23T19:53:15.980206+08:00" level=info msg="[TCP] 127.0.0.1:50028(Telegram) --> 2.0.0.0:443 match Match using 🐟 漏网之鱼[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:16.112679+08:00" level=error msg="XTLS Vision server responded unknown UUID: 402e55af-813f-7141-0dcb-e27b8d24ab12"
time="2023-04-23T19:53:16.115451+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:53:16.189301+08:00" level=error msg="XTLS Vision server responded unknown UUID: b8aeec03-9735-e79c-703d-69568e982e5b"
time="2023-04-23T19:53:16.191029+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:53:16.22024+08:00" level=debug msg="use specified fingerprint:Safari"
time="2023-04-23T19:53:16.289515+08:00" level=debug msg="use specified fingerprint:Safari"
time="2023-04-23T19:53:16.313817+08:00" level=error msg="XTLS Vision server responded unknown UUID: 58f5c77d-bc0a-d317-4794-0cf3b85e4063"
time="2023-04-23T19:53:16.315198+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:53:16.330858+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=1580, paddingLen=0"
time="2023-04-23T19:53:16.331005+08:00" level=info msg="[TCP] 127.0.0.1:50035 --> 91.108.56.116:443 match RuleSet(Telegram) using 📱 Telegram[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:16.383765+08:00" level=error msg="XTLS Vision server responded unknown UUID: 02b74d79-8d6c-4c8c-ecc1-5b8cd104ee6b"
time="2023-04-23T19:53:16.38522+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:53:16.392655+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=297, paddingLen=49"
time="2023-04-23T19:53:16.392691+08:00" level=debug msg="use specified fingerprint:Safari"
time="2023-04-23T19:53:16.392791+08:00" level=info msg="[TCP] 127.0.0.1:50037 --> 91.108.56.116:443 match RuleSet(Telegram) using 📱 Telegram[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:16.436773+08:00" level=error msg="XTLS Vision server responded unknown UUID: 714c9a3e-7206-4566-7373-d998b41d702a"
time="2023-04-23T19:53:16.438148+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:53:16.478655+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=553, paddingLen=198"
time="2023-04-23T19:53:16.478673+08:00" level=debug msg="use specified fingerprint:Safari"
time="2023-04-23T19:53:16.478777+08:00" level=info msg="[TCP] 127.0.0.1:50040 --> 149.154.175.60:443 match RuleSet(Telegram) using 📱 Telegram[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:16.511297+08:00" level=debug msg="use specified fingerprint:Safari"
time="2023-04-23T19:53:16.578158+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=537, paddingLen=115"
time="2023-04-23T19:53:16.578331+08:00" level=info msg="[TCP] 127.0.0.1:50042 --> 149.154.175.53:443 match RuleSet(Telegram) using 📱 Telegram[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:16.580826+08:00" level=error msg="XTLS Vision server responded unknown UUID: 98866c74-f1fd-25ae-19ed-1ef537ee38f5"
time="2023-04-23T19:53:16.59269+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=553, paddingLen=151"
time="2023-04-23T19:53:16.592873+08:00" level=info msg="[TCP] 127.0.0.1:50044 --> 149.154.175.53:443 match RuleSet(Telegram) using 📱 Telegram[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:16.644425+08:00" level=error msg="XTLS Vision server responded unknown UUID: 30863cef-1520-578a-eb28-77eaf78bcfca"
time="2023-04-23T19:53:16.912696+08:00" level=error msg="XTLS Vision server responded unknown UUID: bd8665d6-66d5-4709-5f04-b8c6382d44a5"
time="2023-04-23T19:53:17.029903+08:00" level=error msg="XTLS Vision server responded unknown UUID: 10048bdd-242e-95c4-30af-751a69bc2c38"
time="2023-04-23T19:53:17.031158+08:00" level=error msg="XTLS Vision server responded unknown UUID: 980054b6-fc3b-9a78-833e-6ba6f93ace6d"
time="2023-04-23T19:53:17.825903+08:00" level=debug msg="use specified fingerprint:Safari"
time="2023-04-23T19:53:18.276759+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=553, paddingLen=245"
time="2023-04-23T19:53:18.276863+08:00" level=info msg="[TCP] 127.0.0.1:50019 --> 149.154.175.60:443 match RuleSet(Telegram) using 📱 Telegram[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:18.73214+08:00" level=error msg="XTLS Vision server responded unknown UUID: 46c5a110-0bda-b3ff-776d-c193853a370a"
time="2023-04-23T19:53:42.162823+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:53:42.162972+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:53:42.165779+08:00" level=debug msg="[DNS] mozilla.cloudflare-dns.com --> 104.16.249.249"
time="2023-04-23T19:53:42.242077+08:00" level=debug msg="use specified fingerprint:Safari"
time="2023-04-23T19:53:42.274891+08:00" level=debug msg="use specified fingerprint:Safari"
time="2023-04-23T19:53:42.327461+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=517, paddingLen=515"
time="2023-04-23T19:53:42.327644+08:00" level=info msg="[TCP] 127.0.0.1:50248(Telegram) --> mozilla.cloudflare-dns.com:443 match Match using 🐟 漏网之鱼[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:42.395939+08:00" level=debug msg="XTLS Vision write padding1: command=0, payloadLen=517, paddingLen=458"
time="2023-04-23T19:53:42.396099+08:00" level=info msg="[TCP] 127.0.0.1:50247(Telegram) --> dns.google.com:443 match RuleSet(ProxyGFWlist) using 🌎 全球代理[🇯🇵 Vir|JP]"
time="2023-04-23T19:53:42.413348+08:00" level=debug msg="XTLS Vision read padding: command=0, payloadLen=3215, paddingLen=0"
time="2023-04-23T19:53:42.413413+08:00" level=debug msg="XTLS Vision found TLS 1.3, packetLength=3215， CipherSuite=TLS_AES_128_GCM_SHA256"
time="2023-04-23T19:53:42.422362+08:00" level=debug msg="XTLS Vision write padding2: command=2, payloadLen=64, paddingLen=1297"
time="2023-04-23T19:53:42.422608+08:00" level=debug msg="XTLS Vision direct write start"
time="2023-04-23T19:53:42.500689+08:00" level=debug msg="XTLS Vision read padding: command=2, payloadLen=1289, paddingLen=0"
time="2023-04-23T19:53:42.501022+08:00" level=debug msg="XTLS Vision direct read start"
time="2023-04-23T19:53:42.53933+08:00" level=debug msg="XTLS Vision read padding: command=0, payloadLen=1400, paddingLen=0"
time="2023-04-23T19:53:42.539392+08:00" level=debug msg="XTLS Vision found TLS 1.3, packetLength=1400， CipherSuite=TLS_AES_128_GCM_SHA256"
time="2023-04-23T19:53:42.539696+08:00" level=debug msg="XTLS Vision read padding: command=0, payloadLen=3426, paddingLen=0"
time="2023-04-23T19:53:42.551675+08:00" level=debug msg="XTLS Vision write padding2: command=2, payloadLen=64, paddingLen=1278"
time="2023-04-23T19:53:42.551995+08:00" level=debug msg="XTLS Vision direct write start"
time="2023-04-23T19:53:42.659374+08:00" level=debug msg="XTLS Vision read padding: command=2, payloadLen=1655, paddingLen=0"
time="2023-04-23T19:53:42.659511+08:00" level=debug msg="XTLS Vision direct read start"

========================
ss节点LOG:
========================

time="2023-04-23T19:54:48.844877+08:00" level=debug msg="[DNS] resolve api-wx-1.rancho.gay from https://dns.alidns.com:443/dns-query"
time="2023-04-23T19:54:48.844927+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:54:48.844925+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:54:48.857916+08:00" level=debug msg="[DNS] api-wx-1.rancho.gay --> [183.240.19.167], from https://dns.alidns.com:443/dns-query"
time="2023-04-23T19:54:48.895161+08:00" level=info msg="[TCP] 127.0.0.1:50787 --> 149.154.175.60:443 match RuleSet(Telegram) using 📱 Telegram[🇭🇰 Hong Kong 04|IEPL]"
time="2023-04-23T19:54:48.900789+08:00" level=info msg="[TCP] 127.0.0.1:50788 --> 149.154.175.60:443 match RuleSet(Telegram) using 📱 Telegram[🇭🇰 Hong Kong 04|IEPL]"
time="2023-04-23T19:54:48.900912+08:00" level=info msg="[TCP] 127.0.0.1:50789 --> 149.154.175.60:443 match RuleSet(Telegram) using 📱 Telegram[🇭🇰 Hong Kong 04|IEPL]"
time="2023-04-23T19:54:48.901019+08:00" level=info msg="[TCP] 127.0.0.1:50785 --> 91.108.56.116:443 match RuleSet(Telegram) using 📱 Telegram[🇭🇰 Hong Kong 04|IEPL]"
time="2023-04-23T19:54:48.910246+08:00" level=info msg="[TCP] 127.0.0.1:50790 --> 149.154.175.60:443 match RuleSet(Telegram) using 📱 Telegram[🇭🇰 Hong Kong 04|IEPL]"
time="2023-04-23T19:54:48.911088+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:54:48.913056+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:54:48.913961+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:54:48.915177+08:00" level=info msg="[TCP] 127.0.0.1:50786 --> 91.108.56.116:443 match RuleSet(Telegram) using 📱 Telegram[🇭🇰 Hong Kong 04|IEPL]"
time="2023-04-23T19:54:48.9153+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:54:48.953447+08:00" level=info msg="[TCP] 127.0.0.1:50800(Telegram) --> 68.0.0.0:443 match Match using 🐟 漏网之鱼[🇭🇰 Hong Kong 04|IEPL]"
time="2023-04-23T19:54:48.954663+08:00" level=info msg="[TCP] 127.0.0.1:50798(Telegram) --> 224.176.241.111:443 match Match using 🐟 漏网之鱼[🇭🇰 Hong Kong 04|IEPL]"
time="2023-04-23T19:54:48.958992+08:00" level=info msg="[TCP] 127.0.0.1:50799(Telegram) --> 224.240.232.111:443 match Match using 🐟 漏网之鱼[🇭🇰 Hong Kong 04|IEPL]"
time="2023-04-23T19:54:48.962996+08:00" level=info msg="[TCP] 127.0.0.1:50797(Telegram) --> 68.0.0.0:443 match Match using 🐟 漏网之鱼[🇭🇰 Hong Kong 04|IEPL]"
time="2023-04-23T19:54:49.545471+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:54:49.545664+08:00" level=debug msg="[DNS] resolve api-wx-1.rancho.gay from https://dns.alidns.com:443/dns-query"
time="2023-04-23T19:54:49.558876+08:00" level=debug msg="[DNS] api-wx-1.rancho.gay --> [183.240.19.167], from https://dns.alidns.com:443/dns-query"
time="2023-04-23T19:54:49.589112+08:00" level=info msg="[TCP] 127.0.0.1:50806 --> 91.108.56.116:443 match RuleSet(Telegram) using 📱 Telegram[🇭🇰 Hong Kong 04|IEPL]"
time="2023-04-23T19:55:14.206055+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:55:14.206399+08:00" level=debug msg="[DNS] resolve mtalk.google.com from https://dns.alidns.com:443/dns-query"
time="2023-04-23T19:55:14.219587+08:00" level=debug msg="[DNS] mtalk.google.com --> [74.125.203.188], from https://dns.alidns.com:443/dns-query"
time="2023-04-23T19:55:14.219828+08:00" level=debug msg="[DNS] resolve mtalk.google.com from https://dns.google:443/dns-query"
time="2023-04-23T19:55:14.219843+08:00" level=debug msg="[DNS] resolve mtalk.google.com from https://doh.pub:443/dns-query"
time="2023-04-23T19:55:14.246149+08:00" level=debug msg="[DNS] mtalk.google.com --> [64.233.187.188], from https://doh.pub:443/dns-query"
time="2023-04-23T19:55:17.195704+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:55:17.195925+08:00" level=debug msg="[Rule] use default rules"
time="2023-04-23T19:55:17.199176+08:00" level=debug msg="[DNS] mozilla.cloudflare-dns.com --> 104.16.249.249"
```

### Description

MacOS系统，Vless Vision协议使用socks5连接Telegram失败，ss节点可以正常连接。
Telegram使用app store版本和官网版本均无法使用。
其他软件无此问题。
