### ISSUE TITLE
[Bug] 1.14.3 与 Alpha 速度慢、且连接不会断开

### ISSUE THREAD

**Issue by antonchen** [MetaCubeX/Clash.Meta#525]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.14.3

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
tproxy-port: 7893
mixed-port: 7890
allow-lan: true
bind-address: "*"
find-process-mode: off
ipv6: false 
global-client-fingerprint: chrome
mode: Rule
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip-lite.dat
  geosite: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country-lite.mmdb
profile:
  store-selected: true
log-level: error 
external-controller: :80
external-ui: dashboard
routing-mark: 0xff
interface-name: eth0
sniffer:
  enable: false
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:5335
  enhanced-mode: redir-host
  default-nameserver:
    - 119.29.29.29
    - 114.114.114.114
    - 127.0.0.1
  proxy-server-nameserver:
    - 119.29.29.29
    - 127.0.0.1
  nameserver: [127.0.0.1]
```

### Description

Debian 上跑 Clash tproxy 做旁路由，Yacd 上发觉有连接不会断开（至少一小时），检查请求本机连接早断开了。
同时感觉速度慢，fast.com 测速 1.14.3 与 Alpha 对比 1.13.2 相差很大，最新版本只能跑 60Mbps 左右，且多次测速越测越慢，立即切换到 1.13.2 测速，速度可达 220Mbps。

两个版本仅 sniffer 版本差异变化，其它旧版不支持配置也未删除。
