### ISSUE TITLE
[Bug] MAC端开了clashx.meta后，微信的视频号打不开

### ISSUE THREAD

**Issue by skill7899** [MetaCubeX/Clash.Meta#528]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-eceea72

### Clash config

```yaml
#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/*.yaml

## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
## ！！！只有这份文件的端口设置会随ClashX启动生效

## 如果您不知道如何操作，请参阅 官方Github文档 https://github.com/Dreamacro/clash/blob/dev/README.md
#---------------------------------------------------#

# (HTTP and SOCKS5 in one port)
mixed-port: 7892
# RESTful API for clash
external-controller: 127.0.0.1:58153
allow-lan: false
bind-address:
  '*'
mode: rule
log-level: debug
find-process-mode: off
proxies:
  - name: "ss"
    type: socks5
    server: 127.0.0.1
    port: 1086
  - name: "css"
    type: socks5
    server: 127.0.0.1
    port: 7891
  #   interface-name: en4
  - name: trojan-ws
    server: xxx
    port: 443
    type: trojan
    password: xx
    network: ws
    # skip-cert-verify: true
    udp: true
    ws-opts:
      path: /wsIev
  - name: "hihy"
    type: hysteria
    server: xxxx
    port: 7070
    #ports: 20000-50000
    auth-str: xxx
    protocol: "udp"
    alpn: ['h3']
    up: 50 #默认为Mbps
    down: 500
  - name: "hihy-m"
    type: hysteria
    server: xxxxx
    #port: 7070
    ports: 20000-50000
    auth-str: xxx
    protocol: "udp"
    alpn: ['h3']
    up: 50 #默认为Mbps
    down: 500
proxy-groups:
  - name: bbbb
    type: select
    proxies:
      - ss
      - css
  - name: Proxy
    type: select
    proxies:
      - hihy
      - hihy-m
      - trojan-ws  
geodata-mode: true
use-hosts: true 
tun:
  enable: true
  # device: meta
  stack: system #gvisor
  auto-route: true
  auto-detect-interface: true
sniffer:
  enable: false
  sniffing:
    - tls
    - http
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
    - '*.apple.com'
  # - '*.baidu.com'

  force-domain:
    # - '+'
    - 'google.com'

  port-whitelist:
    - 443
    - 8000-9000
profile:
  #缓存设置(文件位置./cache.db)
  store-selected: false #节点状态记忆（若不同配置有同代理名称,设置值共享）
  store-fake-ip: true #fake-ip缓存
tcp-concurrent: false
dns:
  enable: true #DNS开关(false/true)
  listen: 127.0.0.1:53 #DNS监听地址
  # nameserver-policy:
  #   'jira.bbbb.com': '172.16.31.1'
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
    - 114.114.114.114
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback: 
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
    - https://public.dns.iij.jp/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      #【Meta专属】设定geosite某分类使用fallback返回结果
      - gfw
    domain:
      #列表中的域名使用fallback返回解析结果
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
  enhanced-mode: fake-ip #fake-ip
  ipv6: true
  fake-ip-range: 198.18.1.1/16
  fake-ip-filter:
    #- '*.github.com'
    #- 'github.com'
    # 以下域名列表参考自 vernesong/OpenClash 项目，并由 Hackl0us 整理补充
    # === LAN ===
    - '*.lan'
    # === Linksys Wireless Router ===
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    # === Apple Software Update Service ===
    - 'swscan.apple.com'
    - 'mesu.apple.com'
    # === Windows 10 Connnect Detection ===
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    # === NTP Service ===
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'

    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'

    - 'ntp.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'

    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'

    - 'time1.cloud.tencent.com'
    # === Music Service ===
    ## NetEase
    - '+.music.163.com'
    - '*.126.net'
    ## Baidu
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    ## Kugou
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    ## Kuwo
    - '*.kuwo.cn'
    ## JOOX
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    ## QQ
    - '+.y.qq.com'
    - '+.music.tc.qq.com'
    - 'aqqmusic.tc.qq.com'
    - '+.stream.qqmusic.qq.com'
    ## Xiami
    - '*.xiami.com'
    ## Migu
    - '+.music.migu.cn'
    # === Game Service ===
    ## Nintendo Switch
    - '+.srv.nintendo.net'
    ## Sony PlayStation
    - '+.stun.playstation.net'
    ## Microsoft Xbox
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    # === Other ===
    ## QQ Quick Login
    - 'localhost.ptlogin2.qq.com'
    ## Golang
    - 'proxy.golang.org'
    ## STUN Server
    - 'stun.*.*'
    - 'stun.*.*.*'
 #   - '*.weixin.qq.com'
rules:
  - AND,((IP-CIDR,10.192.170.145/32),(DST-PORT,3389)),bbbb
  - IP-CIDR,11.0.0.0/8,bbbb
  - IP-CIDR,20.223.0.4/32,bbbb
  - IP-CIDR,1.1.1.3/32,DIRECT
  # - PROCESS-NAME,V2rayU,DIRECT
  # - DOMAIN-SUFFIX,deepl.com,DIRECT
  - DOMAIN-SUFFIX,toyaml.com,DIRECT
#  - PROCESS-NAME,SunloginClient,DIRECT
#  - PROCESS-NAME,unknown process,DIRECT

 # pd 
  - DOMAIN,download.parallels.com,REJECT
  - DOMAIN,update.parallels.com,REJECT
  - DOMAIN,desktop.parallels.com,REJECT
  - DOMAIN,download.parallels.com.cdn.cloudflare.net,REJECT
  - DOMAIN,update.parallels.com.cdn.cloudflare.net,REJECT
  - DOMAIN,desktop.parallels.com.cdn.cloudflare.net,REJECT
  - DOMAIN,www.parallels.cn,REJECT
  - DOMAIN,www.parallels.com,REJECT
  - DOMAIN,reportus.parallels.com,REJECT
  - DOMAIN,parallels.com,REJECT
  - DOMAIN,parallels.cn,REJECT
  - DOMAIN,pax-manager.myparallels.com,REJECT
  - DOMAIN,myparallels.com,REJECT
  - DOMAIN,my.parallels.com,REJECT
  # Apple
  - DOMAIN,safebrowsing.urlsec.qq.com,DIRECT # 如果您并不信任此服务提供商或防止其下载消耗过多带宽资源，可以进入 Safari 设置，关闭 Fraudulent Website Warning 功能，并使用 REJECT 策略。
  - DOMAIN,safebrowsing.googleapis.com,DIRECT # 如果您并不信任此服务提供商或防止其下载消耗过多带宽资源，可以进入 Safari 设置，关闭 Fraudulent Website Warning 功能，并使用 REJECT 策略。
  - DOMAIN,developer.apple.com,Proxy
  - DOMAIN-SUFFIX,digicert.com,Proxy
  - DOMAIN,ocsp.apple.com,Proxy
  - DOMAIN,ocsp.comodoca.com,Proxy
  - DOMAIN,ocsp.usertrust.com,Proxy
  - DOMAIN,ocsp.sectigo.com,Proxy
  - DOMAIN,ocsp.verisign.net,Proxy
  - DOMAIN-SUFFIX,apple-dns.net,Proxy
  - DOMAIN,testflight.apple.com,Proxy
  - DOMAIN,sandbox.itunes.apple.com,Proxy
  - DOMAIN,itunes.apple.com,Proxy
  - DOMAIN-SUFFIX,apps.apple.com,Proxy
  - DOMAIN-SUFFIX,blobstore.apple.com,Proxy
  - DOMAIN,cvws.icloud-content.com,Proxy
  - DOMAIN-SUFFIX,mzstatic.com,DIRECT
  - DOMAIN-SUFFIX,itunes.apple.com,DIRECT
  - DOMAIN-SUFFIX,icloud.com,DIRECT
  - DOMAIN-SUFFIX,icloud-content.com,DIRECT
  - DOMAIN-SUFFIX,me.com,DIRECT
  - DOMAIN-SUFFIX,aaplimg.com,DIRECT
  - DOMAIN-SUFFIX,cdn20.com,DIRECT
  - DOMAIN-SUFFIX,cdn-apple.com,DIRECT
  - DOMAIN-SUFFIX,akadns.net,DIRECT
  - DOMAIN-SUFFIX,akamaiedge.net,DIRECT
  - DOMAIN-SUFFIX,edgekey.net,DIRECT
  - DOMAIN-SUFFIX,mwcloudcdn.com,DIRECT
  - DOMAIN-SUFFIX,mwcname.com,DIRECT
  - DOMAIN-SUFFIX,apple.com,DIRECT
  - DOMAIN-SUFFIX,apple-cloudkit.com,DIRECT
  - DOMAIN-SUFFIX,apple-mapkit.com,DIRECT
  # 国内
  - DOMAIN-SUFFIX,126.com,DIRECT
  - DOMAIN-SUFFIX,126.net,DIRECT
  - DOMAIN-SUFFIX,127.net,DIRECT
  - DOMAIN-SUFFIX,163.com,DIRECT
  - DOMAIN-SUFFIX,360buyimg.com,DIRECT
  - DOMAIN-SUFFIX,36kr.com,DIRECT
  - DOMAIN-SUFFIX,acfun.tv,DIRECT
  - DOMAIN-SUFFIX,air-matters.com,DIRECT
  - DOMAIN-SUFFIX,aixifan.com,DIRECT
  - DOMAIN-KEYWORD,alicdn,DIRECT
  - DOMAIN-KEYWORD,alipay,DIRECT
  - DOMAIN-KEYWORD,taobao,DIRECT
  - DOMAIN-SUFFIX,amap.com,DIRECT
  - DOMAIN-SUFFIX,autonavi.com,DIRECT
  - DOMAIN-KEYWORD,baidu,DIRECT
  - DOMAIN-SUFFIX,bdimg.com,DIRECT
  - DOMAIN-SUFFIX,bdstatic.com,DIRECT
  - DOMAIN-SUFFIX,bilibili.com,DIRECT
  - DOMAIN-SUFFIX,bilivideo.com,DIRECT
  - DOMAIN-SUFFIX,caiyunapp.com,DIRECT
  - DOMAIN-SUFFIX,clouddn.com,DIRECT
  - DOMAIN-SUFFIX,cnbeta.com,DIRECT
  - DOMAIN-SUFFIX,cnbetacdn.com,DIRECT
  - DOMAIN-SUFFIX,cootekservice.com,DIRECT
  - DOMAIN-SUFFIX,csdn.net,DIRECT
  - DOMAIN-SUFFIX,ctrip.com,DIRECT
  - DOMAIN-SUFFIX,dgtle.com,DIRECT
  - DOMAIN-SUFFIX,dianping.com,DIRECT
  - DOMAIN-SUFFIX,douban.com,DIRECT
  - DOMAIN-SUFFIX,doubanio.com,DIRECT
  - DOMAIN-SUFFIX,duokan.com,DIRECT
  - DOMAIN-SUFFIX,easou.com,DIRECT
  - DOMAIN-SUFFIX,ele.me,DIRECT
  - DOMAIN-SUFFIX,feng.com,DIRECT
  - DOMAIN-SUFFIX,fir.im,DIRECT
  - DOMAIN-SUFFIX,frdic.com,DIRECT
  - DOMAIN-SUFFIX,g-cores.com,DIRECT
  - DOMAIN-SUFFIX,godic.net,DIRECT
  - DOMAIN-SUFFIX,gtimg.com,DIRECT
  - DOMAIN,cdn.hockeyapp.net,DIRECT
  - DOMAIN-SUFFIX,hongxiu.com,DIRECT
  - DOMAIN-SUFFIX,hxcdn.net,DIRECT
  - DOMAIN-SUFFIX,iciba.com,DIRECT
  - DOMAIN-SUFFIX,ifeng.com,DIRECT
  - DOMAIN-SUFFIX,ifengimg.com,DIRECT
  - DOMAIN-SUFFIX,ipip.net,DIRECT
  - DOMAIN-SUFFIX,iqiyi.com,DIRECT
  - DOMAIN-SUFFIX,jd.com,DIRECT
  - DOMAIN-SUFFIX,jianshu.com,DIRECT
  - DOMAIN-SUFFIX,knewone.com,DIRECT
  - DOMAIN-SUFFIX,le.com,DIRECT
  - DOMAIN-SUFFIX,lecloud.com,DIRECT
  - DOMAIN-SUFFIX,lemicp.com,DIRECT
  - DOMAIN-SUFFIX,licdn.com,DIRECT
  - DOMAIN-SUFFIX,linkedin.com,DIRECT
  - DOMAIN-SUFFIX,luoo.net,DIRECT
  - DOMAIN-SUFFIX,meituan.com,DIRECT
  - DOMAIN-SUFFIX,meituan.net,DIRECT
  - DOMAIN-SUFFIX,mi.com,DIRECT
  - DOMAIN-SUFFIX,miaopai.com,DIRECT
  - DOMAIN-SUFFIX,microsoft.com,DIRECT
  - DOMAIN-SUFFIX,microsoftonline.com,DIRECT
  - DOMAIN-SUFFIX,miui.com,DIRECT
  - DOMAIN-SUFFIX,miwifi.com,DIRECT
  - DOMAIN-SUFFIX,mob.com,DIRECT
  - DOMAIN-SUFFIX,netease.com,DIRECT
  - DOMAIN-SUFFIX,office.com,DIRECT
  - DOMAIN-SUFFIX,office365.com,DIRECT
  - DOMAIN-KEYWORD,officecdn,DIRECT
  - DOMAIN-SUFFIX,oschina.net,DIRECT
  - DOMAIN-SUFFIX,ppsimg.com,DIRECT
  - DOMAIN-SUFFIX,pstatp.com,DIRECT
  - DOMAIN-SUFFIX,qcloud.com,DIRECT
  - DOMAIN-SUFFIX,qdaily.com,DIRECT
  - DOMAIN-SUFFIX,qdmm.com,DIRECT
  - DOMAIN-SUFFIX,qhimg.com,DIRECT
  - DOMAIN-SUFFIX,qhres.com,DIRECT
  - DOMAIN-SUFFIX,qidian.com,DIRECT
  - DOMAIN-SUFFIX,qihucdn.com,DIRECT
  - DOMAIN-SUFFIX,qiniu.com,DIRECT
  - DOMAIN-SUFFIX,qiniucdn.com,DIRECT
  - DOMAIN-SUFFIX,qiyipic.com,DIRECT
  - DOMAIN-SUFFIX,qq.com,DIRECT
  - DOMAIN-SUFFIX,qqurl.com,DIRECT
  - DOMAIN-SUFFIX,rarbg.to,DIRECT
  - DOMAIN-SUFFIX,ruguoapp.com,DIRECT
  - DOMAIN-SUFFIX,segmentfault.com,DIRECT
  - DOMAIN-SUFFIX,sinaapp.com,DIRECT
  - DOMAIN-SUFFIX,smzdm.com,DIRECT
  - DOMAIN-SUFFIX,snapdrop.net,DIRECT
  - DOMAIN-SUFFIX,sogou.com,DIRECT
  - DOMAIN-SUFFIX,sogoucdn.com,DIRECT
  - DOMAIN-SUFFIX,sohu.com,DIRECT
  - DOMAIN-SUFFIX,soku.com,DIRECT
  - DOMAIN-SUFFIX,speedtest.net,DIRECT
  - DOMAIN-SUFFIX,sspai.com,DIRECT
  - DOMAIN-SUFFIX,suning.com,DIRECT
  - DOMAIN-SUFFIX,taobao.com,DIRECT
  - DOMAIN-SUFFIX,tencent.com,DIRECT
  - DOMAIN-SUFFIX,tenpay.com,DIRECT
  - DOMAIN-SUFFIX,tianyancha.com,DIRECT
  - DOMAIN-SUFFIX,tmall.com,DIRECT
  - DOMAIN-SUFFIX,tudou.com,DIRECT
  - DOMAIN-SUFFIX,umetrip.com,DIRECT
  - DOMAIN-SUFFIX,upaiyun.com,DIRECT
  - DOMAIN-SUFFIX,upyun.com,DIRECT
  - DOMAIN-SUFFIX,veryzhun.com,DIRECT
  - DOMAIN-SUFFIX,weather.com,DIRECT
  - DOMAIN-SUFFIX,weibo.com,DIRECT
  - DOMAIN-SUFFIX,xiami.com,DIRECT
  - DOMAIN-SUFFIX,xiami.net,DIRECT
  - DOMAIN-SUFFIX,xiaomicp.com,DIRECT
  - DOMAIN-SUFFIX,ximalaya.com,DIRECT
  - DOMAIN-SUFFIX,xmcdn.com,DIRECT
  - DOMAIN-SUFFIX,xunlei.com,DIRECT
  - DOMAIN-SUFFIX,yhd.com,DIRECT
  - DOMAIN-SUFFIX,yihaodianimg.com,DIRECT
  - DOMAIN-SUFFIX,yinxiang.com,DIRECT
  - DOMAIN-SUFFIX,ykimg.com,DIRECT
  - DOMAIN-SUFFIX,youdao.com,DIRECT
  - DOMAIN-SUFFIX,youku.com,DIRECT
  - DOMAIN-SUFFIX,zealer.com,DIRECT
  - DOMAIN-SUFFIX,zhihu.com,DIRECT
  - DOMAIN-SUFFIX,zhimg.com,DIRECT
  - DOMAIN-SUFFIX,zimuzu.tv,DIRECT
  - DOMAIN-SUFFIX,zoho.com,DIRECT
  - DOMAIN-SUFFIX,macwk.com,DIRECT
  - DOMAIN-SUFFIX,varmilo.com,DIRECT

  # LAN
  - DOMAIN,injections.adguard.org,DIRECT
  - DOMAIN,local.adguard.org,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,172.168.0.0/12,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,17.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT

  - GEOIP,CN,DIRECT
  - MATCH,Proxy
```

### Clash log

```shell
23-04-26 17:59:37[ info ][TCP] 198.18.1.1:54552 --> channels.weixin.qq.com:443 match DomainSuffix(qq.com) using DIRECT
23-04-26 17:59:37[ info ][TCP] 198.18.1.1:54553 --> channels.weixin.qq.com:443 match DomainSuffix(qq.com) using DIRECT
23-04-26 17:59:37[ debug ][DNS] channels.weixin.qq.com --> 101.91.29.36
23-04-26 17:59:37[ debug ][DNS] channels.weixin.qq.com --> 101.89.47.182
23-04-26 17:59:37[ debug ][Rule] use default rules
23-04-26 17:59:37[ debug ][Rule] use default rules
23-04-26 17:59:37[ debug ][DNS] hijack udp:198.18.0.2:53 from 198.18.1.1:64815
23-04-26 17:59:31[ info ][TCP] 198.18.1.1:54531 --> 183.60.8.218:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:31[ info ][TCP] 198.18.1.1:54528 --> 183.60.8.218:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:31[ debug ][Rule] use default rules
23-04-26 17:59:31[ debug ][Rule] use default rules
23-04-26 17:59:28[ info ][TCP] 198.18.1.1:54518 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:28[ debug ][Rule] use default rules
23-04-26 17:59:22[ info ][TCP] 198.18.1.1:54498 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:22[ debug ][Rule] use default rules
23-04-26 17:59:21[ info ][TCP] 198.18.1.1:54491 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:21[ debug ][Rule] use default rules
23-04-26 17:59:20[ info ][TCP] 198.18.1.1:54484 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:20[ info ][TCP] 198.18.1.1:54480 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:20[ info ][TCP] 198.18.1.1:54476 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:20[ debug ][Rule] use default rules
23-04-26 17:59:20[ info ][TCP] 198.18.1.1:54468 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:20[ info ][TCP] 198.18.1.1:54472 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:20[ debug ][Rule] use default rules
23-04-26 17:59:20[ info ][TCP] 198.18.1.1:54464 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:20[ info ][TCP] 198.18.1.1:54456 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:20[ debug ][Rule] use default rules
23-04-26 17:59:20[ info ][TCP] 198.18.1.1:54460 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:20[ info ][TCP] 198.18.1.1:54444 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:20[ debug ][Rule] use default rules
23-04-26 17:59:20[ debug ][Rule] use default rules
23-04-26 17:59:20[ debug ][Rule] use default rules
23-04-26 17:59:20[ debug ][Rule] use default rules
23-04-26 17:59:20[ info ][TCP] 198.18.1.1:54452 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:20[ debug ][Rule] use default rules
23-04-26 17:59:20[ info ][TCP] 198.18.1.1:54448 --> 183.47.118.145:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:20[ debug ][Rule] use default rules
23-04-26 17:59:19[ debug ][Rule] use default rules
23-04-26 17:59:19[ debug ][Rule] use default rules
23-04-26 17:59:18[ info ][TCP] 198.18.1.1:54433 --> 183.60.8.150:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:18[ info ][TCP] 198.18.1.1:54437 --> 183.60.8.150:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:18[ info ][TCP] 198.18.1.1:54435 --> 183.60.8.150:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:18[ info ][TCP] 198.18.1.1:54431 --> 183.60.8.150:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:18[ debug ][Rule] use default rules
23-04-26 17:59:18[ debug ][Rule] use default rules
23-04-26 17:59:18[ debug ][Rule] use default rules
23-04-26 17:59:18[ debug ][Rule] use default rules
23-04-26 17:59:17[ info ][TCP] 198.18.1.1:54423 --> 183.60.8.150:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:16[ debug ][Rule] use default rules
23-04-26 17:59:13[ info ][TCP] 198.18.1.1:54413 --> 183.60.8.150:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:13[ debug ][Rule] use default rules
23-04-26 17:59:07[ info ][TCP] 198.18.1.1:54392 --> 183.60.8.150:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:07[ info ][TCP] 198.18.1.1:54390 --> 183.60.8.150:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:07[ debug ][Rule] use default rules
23-04-26 17:59:07[ info ][TCP] 198.18.1.1:54386 --> 183.60.8.150:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:07[ info ][TCP] 198.18.1.1:54388 --> 183.60.8.150:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:07[ debug ][Rule] use default rules
23-04-26 17:59:07[ debug ][Rule] use default rules
23-04-26 17:59:07[ debug ][Rule] use default rules
23-04-26 17:59:06[ info ][TCP] 198.18.1.1:54381 --> 183.60.8.150:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:06[ debug ][Rule] use default rules
23-04-26 17:59:05[ info ][TCP] 198.18.1.1:54375 --> 119.147.19.225:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:05[ debug ][Rule] use default rules
23-04-26 17:59:05[ info ][TCP] 198.18.1.1:54371 --> 119.147.19.225:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:05[ info ][TCP] 198.18.1.1:54367 --> 119.147.19.225:80 match GeoIP(CN) using DIRECT
23-04-26 17:59:05[ debug ][Rule] use default rules
23-04-26 17:59:05[ debug ][Rule] use default rules
23-04-26 17:59:05[ info ]
```

### Description

<img width="919" alt="image" src="https://user-images.githubusercontent.com/13962272/234538663-e45e6f4c-472e-45b5-ba00-b14325586bfb.png">
用了clashx pro 是没有问题的，日志也没有发现有报错的地方，另外朋友圈只有第一次可以刷新。第二次又不行的
