### ISSUE TITLE
[Bug] Linux下Dashboard不显示建立连接的进程名称

### ISSUE THREAD

**Issue by nukemiko** [MetaCubeX/Clash.Meta#542]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta 20230501.r0.gf90066f2 linux amd64 with go1.20.3 Mon May  1 23:17:36 UTC 2023

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
geodata-mode: true
tcp-concurrent: true

allow-lan: true
bind-address: "*"

enable-process: true
find-process-mode: strict

mode: rule

log-level: info

ipv6: false

tun:
    enable: true
    stack: system
    auto-route: true
    auto-detect-interface: true
    dns-hijack:
        - 0.0.0.0:53

profile:
    store-selected: true
    store-fake-ip: true

sniffer:
    enable: false
    sniffing:
        - "tls"
        - "http"
    skip-domain:
        - "Mijia Cloud"
        - "dlg.io.mi.com"
        - "+.apple.com"
        - "+.ccrgt.com"
        - "google.com"
        - "+.tplogin.cn"
        - "+.melogin.cn"
    force-domain:
```

### Description

Dashboard的“连接”页面下不显示建立连接的进程名：
![图片](https://user-images.githubusercontent.com/53572814/235640546-5b1a05ea-c256-4f1b-a079-292dfe9fdadc.png)
测试了三个Dashboard（yacd.haishan.me、yacd.metacubex.one、clash.razord.top），都不会显示建立连接的进程名；而使用 clash-premium 内核时，则会正常显示。
未测试其他平台的情况。
