### ISSUE TITLE
[Bug] ss协议开启udp-over-tcp，udp流量不通

### ISSUE THREAD

**Issue by escapezn** [MetaCubeX/Clash.Meta#546]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.14.4

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
- name: "ssgree"
    type: ss
    server: 
    port: 
    cipher: 2022-blake3-aes-128-gcm
    password: "aF82iBqcGv/Xvwun311RYg=="
    udp: true
    udp-over-tcp: true
    tfo: true
```

### Description

服务端xray 1.7.5，客户端clash.meta 1.14.4 ss协议，打开udp-over-tcp时，udp流量不通，回退1.14.1版本正常。

    udp: true
    udp-over-tcp: false
udp正常

    udp: true
    udp-over-tcp: true
udp不通

在 https://github.com/MetaCubeX/Clash.Meta/issues/407 已修复，但在1.14.3及之后的版本重新出现
