### ISSUE TITLE
[Feature] dialer-proxy能否支持使用通过proxy-providers获得的proxy name或proxy-groups name？

### ISSUE THREAD

**Issue by GrayXu** [MetaCubeX/Clash.Meta#548]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

clash meta v1.14.4，这个版本正式为wireguard提供使用dialer-proxy进行链式代理的支持。  
以下配置是可行的
```
proxies: 
  - name: "wg"
    type: wireguard
    server: 162.159.192.1
    port: 2408
    ip: 172.16.0.2
    private-key: "私钥"
    public-key: "公钥"
    udp: true
    dialer-proxy: "kr"
 
  - name: "kr"
    type: ss
    server: ip
    port: 80
    cipher: 2022-blake3-aes-128-gcm
    password: "==:=="
    udp: true
    udp-over-tcp: false
```
但wg的dialer-proxy不能是通过proxy-provider获取的proxy，必须是声明好的proxies之一，也不能是proxy-groups name。虽然可能通过外部获取的proxy可能改变name导致wg本身连接性问题，但对于普通节点都是通过provider获取的用户来说，就无法直接配置dialer-proxy😢     

所以不知道能否提供这项支持，感谢！

**Comment by qist** [comment]
可以这样配置
```
  - name: wg-proxy
    type: select
    use:
      - proxy-provider
------------------------------------
# proxy-provider wg 内容
  - name: "wg"
    type: wireguard
    server: 162.159.192.1
    port: 2408
    ip: 172.16.0.2
    private-key: "私钥"
    public-key: "公钥"
    udp: true
    reserved: [ ]
    mtu: 1280
    dialer-proxy: "wg-proxy"
    remote-dns-resolve: true
    dns: [ 1.1.1.1, 8.8.8.8 ]   
```
