### ISSUE TITLE
[Bug] PPPOE断线重连导致clash.meta被kill

### ISSUE THREAD

**Issue by abcfy2** [MetaCubeX/Clash.Meta#559]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.14.4

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
authentication: [""]
allow-lan: true
mode: Rule
log-level: info
ipv6: true
external-controller: :9999
external-ui: ui
secret:
tun: {enable: false}
experimental: {ignore-resolve-fail: true, interface-name: en0}
dns: {enable: true, ipv6: true, listen: 0.0.0.0:1053, use-hosts: true, enhanced-mode: redir-host, default-nameserver: [114.114.114.114, 223.5.5.5, https://1.0.0.1/dns-query, https://223.5.5.5/dns-query, 127.0.0.1:53], nameserver: [https://223.5.5.5/dns-query], fallback: [https://1.0.0.1/dns-query], fallback-filter: {geoip: true}}
sniffer: {enable: true, skip-domain: [Mijia Cloud], sniff: {tls: {ports: [443, 8443]}, http: {ports: [80, 8080-8880]}}}
store-selected: true
find-process-mode: "off"
hosts:
   'time.android.com': 203.107.6.88
   'time.facebook.com': 203.107.6.88
   'localhost.localdomain': 127.0.0.1
   'TUF-AX5400-0368.': 192.168.50.1
   'TUF-AX5400-0368.local': 192.168.50.1
   'router.asus.com': 192.168.50.1
   'www.asusnetwork.net': 192.168.50.1
   'www.asusrouter.com': 192.168.50.1
#用于编写自定义设定(可参考https://lancellc.gitbook.io/clash)，例如
#新版已经支持直接读取系统hosts(/etc/hosts)并写入配置文件，无需在此处添加！
#新版meta内核已经支持yaml-v3，所有能在脚本中修改的条目请勿在此处配置以免报错！
#port: 7890
proxies:
    #【Meta专属】Hysteria
  - name: "hysteria"
    type: hysteria
    server: hide
    port: hide
    obfs: hide
    alpn:
      - h3
    protocol: udp #支持udp/wechat-video/faketcp
    up: '30 Mbps'          #若不写单位，默认为Mbps
    down: '300 Mbps'       #若不写单位，默认为Mbps
    sni: hide
    # skip-cert-verify: true
    recv-window-conn: 1966080
    recv-window: 8388608
    auth_str: "mypass"
    # ca: "./my.ca"
    # ca_str: "xyz"
    # disable_mtu_discovery: false
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - hysteria

rule-providers:
  proxylist:
    type: file
    behavior: domain
    path: ./ruleset/proxylist.yaml
  whitelist:
    type: file
    behavior: domain
    path: ./ruleset/whitelist.yaml
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

rules:
 - RULE-SET,whitelist,DIRECT
 - RULE-SET,proxylist,Proxy,no-resolve
 - RULE-SET,reject,REJECT
 - RULE-SET,gfw,Proxy,no-resolve
 - RULE-SET,greatfire,Proxy,no-resolve
 - RULE-SET,telegramcidr,Proxy,no-resolve
```

### Clash log

```shell
WARN[2023-05-05T11:13:05.41022272+08:00] [TCP] dial Proxy (match RuleSet/telegramcidr) 192.168.50.196:39576 --> 91.108.56.133:443 error: timeout: no recent network activity 
DEBU[2023-05-05T11:13:05.41117538+08:00] [DNS] resolve tr.fengyu.io from tls://dns.rubyfish.cn:853 
DEBU[2023-05-05T11:13:05.41177234+08:00] [DNS] resolve tr.fengyu.io from https://doh.pub:443/dns-query 
DEBU[2023-05-05T11:13:05.41277586+08:00] [DNS] resolve tr.fengyu.io from tls://dns.rubyfish.cn:853 
DEBU[2023-05-05T11:13:05.41341926+08:00] [DNS] resolve tr.fengyu.io from https://223.5.5.5:443/dns-query 
DEBU[2023-05-05T11:13:05.41586398+08:00] [DNS] resolve tr.fengyu.io from https://223.5.5.5:443/dns-query 
DEBU[2023-05-05T11:13:05.4166044+08:00] [DNS] resolve tr.fengyu.io from https://doh.pub:443/dns-query 
WARN[2023-05-05T11:13:05.70935766+08:00] [TCP] dial DIRECT [2409:8a70:968:7670:bede:5d92:9482:9e1b]:39890 --> edge.microsoft.com:443 error: connect failed: dial tcp [2620:1ec:12::239]:443: i/o timeout | dial tcp [2620:1ec:c11::239]:443: i/o timeout | connect failed: dial tcp 13.107.21.239:443: i/o timeout | dial tcp 204.79.197.239:443: i/o timeout 
DEBU[2023-05-05T11:13:05.75894104+08:00] [Sniffer] Sniff TCP [[2409:8a70:968:7670:bede:5d92:9482:9e1b]:49852]-->[edge.microsoft.com:443] success, replace domain [edge.microsoft.com]-->[edge.microsoft.com] 
DEBU[2023-05-05T11:13:05.75919214+08:00] [Rule] use default rules                     
DEBU[2023-05-05T11:13:07.61357268+08:00] [Sniffer] All sniffing sniff failed with from [192.168.50.196:46420] to [91.108.56.133:443] 
DEBU[2023-05-05T11:13:07.6138493+08:00] [Rule] use default rules                     
DEBU[2023-05-05T11:13:07.61458168+08:00] [Rule] use default rules                     
INFO[2023-05-05T11:13:07.6170668+08:00] [TCP] 192.168.50.196:39730 --> 192.168.50.1:18017 doesn't match any rule using DIRECT 
DEBU[2023-05-05T11:13:07.61824392+08:00] [Sniffer] All sniffing sniff failed with from [2409:8a70:968:7670:bede:5d92:9482:9e1b:57472] to [2001:b28:f23f:f005::a:443] 
DEBU[2023-05-05T11:13:07.61846222+08:00] [Rule] use default rules                     
DEBU[2023-05-05T11:13:07.62168632+08:00] [Sniffer] All sniffing sniff failed with from [2409:8a70:968:7670:bede:5d92:9482:9e1b:40348] to [2001:b28:f23f:f005::a:80] 
DEBU[2023-05-05T11:13:07.62228692+08:00] [Rule] use default rules                     
DEBU[2023-05-05T11:13:07.6288835+08:00] [Rule] use default rules                     
INFO[2023-05-05T11:13:07.63392398+08:00] [TCP] 192.168.50.196:39736 --> 192.168.50.1:18017 doesn't match any rule using DIRECT 
DEBU[2023-05-05T11:13:10.3960446+08:00] re-creating the http client due to requesting https://223.5.5.5:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAAAEAAQ: Get "https://223.5.5.5:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAABwAAQ": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) 
DEBU[2023-05-05T11:13:10.39625128+08:00] [https://223.5.5.5:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAAAEAAQ] using HTTP/2 for this upstream: <nil> 
DEBU[2023-05-05T11:13:10.39645716+08:00] re-creating the http client due to requesting https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAAAEAAQ: Get "https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAABwAAQ": context deadline exceeded 
DEBU[2023-05-05T11:13:10.3965687+08:00] [https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAAAEAAQ] using HTTP/2 for this upstream: <nil> 
DEBU[2023-05-05T11:13:10.39660668+08:00] re-creating the http client due to requesting https://223.5.5.5:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAABwAAQ: Get "https://223.5.5.5:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAABwAAQ": context deadline exceeded 
DEBU[2023-05-05T11:13:10.39672666+08:00] [https://223.5.5.5:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAABwAAQ] using HTTP/2 for this upstream: <nil> 
DEBU[2023-05-05T11:13:10.39712778+08:00] re-creating the http client due to requesting https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAABwAAQ: Get "https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAABwAAQ": context deadline exceeded 
DEBU[2023-05-05T11:13:10.39725966+08:00] [https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAABwAAQ] using HTTP/2 for this upstream: <nil> 
DEBU[2023-05-05T11:13:10.3975183+08:00] re-creating the http client due to requesting https://223.5.5.5:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAABwAAQ: Get "https://223.5.5.5:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAAAEAAQ": context deadline exceeded 
DEBU[2023-05-05T11:13:10.39762944+08:00] [https://223.5.5.5:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAABwAAQ] using HTTP/2 for this upstream: <nil> 
DEBU[2023-05-05T11:13:10.39964352+08:00] [Rule] use default rules                     
DEBU[2023-05-05T11:13:10.39856598+08:00] re-creating the http client due to requesting https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAABwAAQ: Get "https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAAAEAAQ": context deadline exceeded 
DEBU[2023-05-05T11:13:10.40091954+08:00] [https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAABwAAQ] using HTTP/2 for this upstream: <nil> 
INFO[2023-05-05T11:13:10.40025826+08:00] [UDP] [2409:8a70:968:7670:bede:5d92:9482:9e1b]:47287 --> [2607:f298:5:101d:f816:3eff:fefd:8817]:123 doesn't match any rule using DIRECT 
DEBU[2023-05-05T11:13:10.40027938+08:00] re-creating the http client due to requesting https://223.5.5.5:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAAAEAAQ: Get "https://223.5.5.5:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAAAEAAQ": context deadline exceeded 
DEBU[2023-05-05T11:13:10.40176792+08:00] re-creating the http client due to requesting https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAAAEAAQ: Get "https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAAAEAAQ": context deadline exceeded 
DEBU[2023-05-05T11:13:10.40318562+08:00] [https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAAAEAAQ] using HTTP/2 for this upstream: <nil> 
DEBU[2023-05-05T11:13:10.40363486+08:00] [https://223.5.5.5:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAAAEAAQ] using HTTP/2 for this upstream: <nil> 
DEBU[2023-05-05T11:13:10.41200568+08:00] re-creating the http client due to requesting https://doh.pub:443/dns-query?dns=AAABAAABAAAAAAAAAnRyBmZlbmd5dQJpbwAAAQAB: Get "https://doh.pub:443/dns-query?dns=AAABAAABAAAAAAAAAnRyBmZlbmd5dQJpbwAAHAAB": context deadline exceeded 
DEBU[2023-05-05T11:13:10.41222148+08:00] [https://doh.pub:443/dns-query?dns=AAABAAABAAAAAAAAAnRyBmZlbmd5dQJpbwAAAQAB] using HTTP/2 for this upstream: <nil> 
...
```

当这种错误滚了好几屏之后，进程最终就被内核干掉了:

```
DEBU[2023-05-05T11:13:42.75035632+08:00] [https://223.5.5.5:443/dns-query?dns=AAABAAABAAAAAAAAA2RvaANwdWIAABwAAQ] using HTTP/2 for this upstream: <nil> 
DEBU[2023-05-05T11:13:42.75198238+08:00] re-creating the http client due to requesting https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAAnRyBmZlbmd5dQJpbwAAHAAB: Get "https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAAnRyBmZlbmd5dQJpbwAAAQAB": connect failed: dial tcp 1.0.0.1:443: connect: network is unreachable | connect failed: no ip address 
DEBU[2023-05-05T11:13:42.75248982+08:00] [https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAAnRyBmZlbmd5dQJpbwAAHAAB] using HTTP/2 for this upstream: <nil> 
DEBU[2023-05-05T11:13:42.75316748+08:00] re-creating the http client due to requesting https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAAnRyBmZlbmd5dQJpbwAAHAAB: Get "https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAAnRyBmZlbmd5dQJpbwAAHAAB": connect failed: dial tcp 1.0.0.1:443: connect: network is unreachable | connect failed: no ip address 
DEBU[2023-05-05T11:13:42.7535688+08:00] [https://1.0.0.1:443/dns-query?dns=AAABAAABAAAAAAAAAnRyBmZlbmd5dQJpbwAAHAAB] using HTTP/2 for this upstream: <nil> 


Killed
```
```


### Description

我这边的PPPOE大概每2小时会断线，然后路由器自动拨号重连，在这个过程中可以看到上述日志内容，最终导致clash进程被kill
