### ISSUE TITLE
[Bug] 使用trojan时有告警

### ISSUE THREAD

**Issue by suikaremilia** [MetaCubeX/Clash.Meta#570]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Meta v1.14.4 windows amd64 以及alpha-72a00cb windows amd64

### What OS are you seeing the problem on?

Windows, Linux

### Clash config

```yaml
proxies:
  - name: trojan
    type: trojan
    server: server
    port: 443
    password: xxx
    udp: true
    sni: server
    alpn:
      - h2
      - http/1.1
    skip-cert-verify: false
```

### Clash log

```shell
WARNING
[TCP] dial PROXY (match Match/) 127.0.0.1:65053 --> 91.108.56.176:80 error: server:443 connect error: remote error: tls: no application protocol
```

### Description

使用trojan时会收到大量clash log的告警，测速也显示error，但实际不影响访问。
相同的配置使用P内核则无告警
