### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by BaronChushao** [MetaCubeX/Clash.Meta#571]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-72a00cb

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
log-level: debug
mode: rule
ipv6: true
allow-lan: false
tcp-concurrent: true
geodata-mode: true
find-process-mode: off
global-client-fingerprint: edge
external-controller: 0.0.0.0:9090
secret: ""
profile:
  store-selected: true
  store-fake-ip: true

geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"

tun:
  enable: true
  stack: system
  dns-hijack:
    - 0.0.0.0:53
  auto-detect-interface: true
  auto-route: true
  strict-route: true

sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
  force-domain:
    - +.v2ex.com

dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
  nameserver:
    - 8.8.4.4
    - tls://1.0.0.1
    - https://dns.google/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query

rules:
  - GEOSITE,geolocation-!cn,proxy
  - GEOSITE,gfw,proxy
  - GEOSITE,private,DIRECT
  - GEOSITE,CN,DIRECT
  - GEOIP,private,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,match
```

### Clash log

```shell
无
```

### Description

win10跑裸核，启动几分钟之后WLAN就变成一个电脑模样了，然后WLAN显示无internet（实际上有网）
![image](https://github.com/MetaCubeX/Clash.Meta/assets/98247704/0dcb4ab8-f62c-4f17-bc97-69ea90877f49)
![image](https://github.com/MetaCubeX/Clash.Meta/assets/98247704/52a7111d-059b-4fe0-af8b-148e396e5d35)
