### ISSUE TITLE
[Feature]小功能建议

### ISSUE THREAD

**Issue by linger040831** [MetaCubeX/Clash.Meta#579]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

1. 希望提供延迟测速超时时间设置，在节点较多的机场如果超时时间过长，会测试很长时间，如果能手动设置时间能缓解一下问题

```
  health-check:
   enable: false
   lazy: true
   url: https://www.gstatic.com/generate_204
   interval: 300
   time: 1000 # 如果测速时间超过1000ms直接超时
```
2.希望提供类似于stash的引用所有proxies的选项[灵活地组合代理](https://stash.wiki/proxy-protocols/proxy-groups#%E7%81%B5%E6%B4%BB%E5%9C%B0%E7%BB%84%E5%90%88%E4%BB%A3%E7%90%86)
```
proxy-groups:
  - name: my-group
    type: select
    include-all-proxies: true # 引用所有proxies
```
3.希望提供url-test引用proxy-providers时能强制使用url-test的测速规则，而不是使用proxy-providers的health-check，这样在通过filter后不会直接测速整个被引用的proxy-providers（虽然感觉直接测速整个机场更方便，但是节点太多的话太慢了
```
- name: auto
  type: url-test
  use:
      - proxy-providers
  interval: 300
  filter: hk|us
  overlay-health-check: true # 覆盖proxy-providers的health-check，强制使用interval
```
