### ISSUE TITLE
[Bug] Mac端ruleset的text格式支持不生效，不能下载对应txt文件

### ISSUE THREAD

**Issue by PingZi-Wing** [MetaCubeX/Clash.Meta#585]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.14.4

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
##基础配置
port: 7890           # HTTP 代理端口
socks-port: 7891     # Socks 端口
mixed-port: 7892     # 混合端口
allow-lan: true      # 允许局域网连接
mode: rule           # 规则模式
log-level: info      # 日志级别
ipv6: true           # IPV6开关
external-controller: 127.0.0.1:9090   # 控制器监听地址
external-ui: ./dashboard              # 配置 WEB UI 目录，使用 http://127.0.0.1:9090/ui 访问
profile:                   # 缓存设置(文件位置./cache.db)
  store-selected: true     # 节点状态记忆（若不同配置有同代理名称,设置值共享） 
###【Meta专属】
tcp-concurrent: true # TCP连接并发域名解析的所有IP，选择握手最快的IP进行连接 
geox-url:
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
  mmdb: "https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-only-cn-private.mmdb"
global-client-fingerprint: chrome

##DNS配置
hosts:               # host，支持通配符（非通配符域名优先级高于通配符域名）
   'talk.google.com': 108.177.125.188
   'mtalk.google.com': 108.177.125.188 
dns:
  enable: false       # DNS开关(false/true)
  ipv6: true          # IP6解析开关
  listen: 0.0.0.0:53  # dns 监听
  use-hosts: true     # 查询系统hosts配置并返回真实IP  
  enhanced-mode: fake-ip
  fake-ip-filter:
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
  nameserver:        # 默认 DNS 服务
    - dhcp://en0     # dns from dhcp 有线网卡
    - dhcp://en1     # dns from dhcp 无线网卡   
    - 223.5.5.5      # 阿里dns
    #- 119.29.29.29   # 腾讯dns     
  fallback:          # 国外 DNS 服务器
    - https://185.222.222.222/dns-query  # DNS.SB
    - https://208.67.222.222/dns-query   # OpenDNS
  fallback-filter:
    geoip: true      #是否启用 fallback filter 
    ipcidr:
      - 240.0.0.0/4
      - 127.0.0.1
      - 0.0.0.0/32 
  proxy-server-nameserver:     #解析代理节点的域名
    - https://208.67.222.222/dns-query                
  nameserver-policy:           #指定域名使用自定义DNS解析
   'blog.google': '119.29.29.29'
   'googletraveladservices.com': '119.29.29.29'
   'dl.l.google.com': '119.29.29.29'
   'clientservices.googleapis.com': '119.29.29.29'
   'update.googleapis.com': '119.29.29.29'
   'translate.googleapis.com': '119.29.29.29'
   'fonts.googleapis.com': '119.29.29.29'
   'fonts.gstatic.com': '119.29.29.29'
   
##代理配置
proxies:   
  - name: 自建grpc
    server: 20.48.117.21
    port: 8212
                  
#========= 建立锚点 =========#
pp:     &pp {type: http,     interval: 86400, filter: '^(?!.*(关注|过期))', health-check: {enable: true, url: http://www.apple.com/library/test/success.html, interval: 3600} }
auto: &auto {type: url-test, lazy: true,  url: http://www.apple.com/library/test/success.html, interval: 1800, tolerance: 100 }
fall: &fall {type: fallback, lazy: true,  url: http://www.apple.com/library/test/success.html, interval: 1800 }
rpc:   &rpc {type: http,     behavior: classical, interval: 86400}
rpd:   &rpd {type: http,     behavior: domain,    interval: 86400}
rpi:   &rpi {type: http,     behavior: ipcidr,    interval: 86400}
#========= 锚点结束 =========#
proxy-providers:
  自建机场:
    <<: *pp
    url: https://gist.githubusercontent.com/PingZi-Wing/4c01e1/raw/Own4Clash 
    path: ./proxy-providers/Own.yaml    
  订阅机场:
    <<: *pp
    url: https://xn--dqrs61zol.xn--fiqs8s/link/T2CdK8j09ubVRy5hCR4T?config=1&lang=zh 
    path: ./proxy-providers/Sub.yaml    
     
proxy-groups:
  - {name: 🚀 默认节点, type: select, proxies: [自建grpc, 🎯 手动选择, 🇨🇳 自建故障转移,🇭🇰 香港延迟优选, 🇨🇳 台湾延迟优选,🇸🇬 狮城延迟优选,🇯🇵 日本延迟优选,🇰🇷 韩国延迟优选,🇺🇲 美国延迟优选]}
  - {name: 🎯 手动选择, type: select, use: [自建机场, 订阅机场]}
  - {name: 🌍 国际媒体, type: select, proxies: [🚀 默认节点, 🎯 手动选择,🇭🇰 香港延迟优选, 🇨🇳 台湾延迟优选,🇸🇬 狮城延迟优选,🇯🇵 日本延迟优选,🇰🇷 韩国延迟优选,🇺🇲 美国延迟优选,DIRECT]}
  - {name: 📺 港台B站, type: select, proxies: [DIRECT,🚀 默认节点, 🎯 手动选择,🇭🇰 香港延迟优选, 🇨🇳 台湾延迟优选]}  
  - {name: ☁️ 微软云盘, type: select, proxies: [🚀 默认节点,DIRECT]} 
  - {name: Ⓜ️ 微软服务, type: select, proxies: [DIRECT,🚀 默认节点]}
  - {name: 🍎 苹果服务, type: select, proxies: [DIRECT,🚀 默认节点]}
  - {name: 🍃 广告拦截, type: select, proxies: [REJECT,PASS]}      
###节点分组
  - {name: 🇨🇳 自建故障转移, <<: *fall, filter: '^(?!.*(港))', use: [自建机场]}
  - {name: 🇭🇰 香港延迟优选, <<: *auto, filter: '(?=.*(港|HK|(?i)Hong))^((?!(香港→|游戏)).)*$', use: [自建机场]}
  - {name: 🇨🇳 台湾延迟优选, <<: *auto, filter: '台|湾|TW|(?i)Taiwan', use: [自建机场, 订阅机场]}
  - {name: 🇸🇬 狮城延迟优选, <<: *auto, filter: '(?=.*(新|狮|獅|SG|(?i)Singapore))^((?!(新加坡→|游戏)).)*$', use: [订阅机场]}
  - {name: 🇯🇵 日本延迟优选, <<:  *auto, filter: '(?=.*(日|JP|(?i)Japan))^((?!(日本→|游戏)).)*$', use: [订阅机场]}
  - {name: 🇰🇷 韩国延迟优选, <<:  *auto, filter: 'KR|Korea|KOR|首尔|韩|韓', use: [订阅机场]}
  - {name: 🇺🇲 美国延迟优选, <<: *auto, filter: '美|US|(?i)States|American', use: [订阅机场]}
 
##规则配置              
rule-providers:
##不应该被去广告分流规则屏蔽的域名、IP等，请将此分流规则置于去广告规则之前##        
  Direct:
    <<: *rpc
    path: ./rule-providers/Direct.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Direct/Direct.yaml
##广告联盟去广告规则集##        
  BanAD:
    <<: *rpc
    path: ./rule-providers/BanAD.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml
##应用去广告规则集##    
  BanProgramAD:
    <<: *rpc
    path: ./rule-providers/BanProgramAD.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml   
  BlockHttpDNS:
    <<: *rpc
    path: ./rule-providers/BlockHttpDNS.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BlockHttpDNS/BlockHttpDNS.yaml    
##隐私防护规则集##   
  Privacy-Domain:
    <<: *rpd
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_Domain.txt"
    path: ./rule-providers/Privacy-Domain.txt
    format: text
  Privacy:
    <<: *rpc
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy.yaml"
    path: ./rule-providers/Privacy.yaml
##反劫持规则集##   
  Hijacking:
    <<: *rpc
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hijacking/Hijacking.yaml"
    path: ./rule-providers/Hijacking.yaml   
##自定义个人规则集##    
  Custom_Domain:
    <<: *rpd
    path: ./rule-providers/Custom_Domain.txt
    url: https://raw.githubusercontent.com/PingZi-Wing/clash-rules/main/Custom_Domain.txt
    format: text
##Bing###   
  Bing:
    <<: *rpc
    path: ./rule-providers/Bing.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.yaml 
##Open AI###   
  OpenAI:
    <<: *rpc
    path: ./rule-providers/OpenAI.yaml
    url: https://gitlab.com/lodepuly/vpn_tool/-/raw/main/Tool/Clash/Rule/OpenAI.yaml   
##港台B站规则集##   
  BilibiliHMT-Domain:
    <<: *rpc
    path: ./rule-providers/BilibiliHMT-Domain.yaml
    url: https://raw.githubusercontent.com/PingZi-Wing/clash-rules/main/BilibiliHMT-Domain.yaml
  BilibiliHMT-IP:
    <<: *rpc
    path: ./rule-providers/BilibiliHMT-IP.yaml
    url: https://raw.githubusercontent.com/PingZi-Wing/clash-rules/main/BilibiliHMT-IP.yaml    
##全球媒体规则集## 
  GlobalMedia_Domain:
    <<: *rpd
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Domain.txt"
    path: ./rule-providers/GlobalMedia_Domain.txt
    format: text
  GlobalMedia:
    <<: *rpc
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.yaml"
    path: ./rule-providers/GlobalMedia.yaml
##GFWList全量列表##
  GFW_Domain:
    <<: *rpd
    path: ./rule-providers/GFW_Domain.txt
    url: https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/gfw.txt
    format: text
  GFW:
    <<: *rpc
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Global/Global.yaml"
    path: ./rule-providers/GFW.yaml  
##苹果规则集## 
  Apple:
    <<: *rpc
    path: ./rule-providers/Apple.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml
  Apple_Domain:
    <<: *rpd
    path: ./rule-providers/Apple_Domain.txt
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple_Domain.txt
    format: text    
##微软规则集##
  OneDrive:
    <<: *rpc
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.yaml
    path: ./rule-providers/OneDrive.yaml
  Microsoft:
    <<: *rpc
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./rule-providers/Microsoft.yaml
##游戏平台规则集##
  Steam:
    <<: *rpc
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml
    path: ./rule-providers/Steam.yaml  
         
rules:
  - DOMAIN-SUFFIX,githubusercontent.com,🚀 默认节点
  - DOMAIN,github.com,🚀 默认节点
  - DOMAIN,cn.bing.com,DIRECT 
  - RULE-SET,Privacy-Domain,🍃 广告拦截  
  - RULE-SET,BanAD,🍃 广告拦截,no-resolve
  - RULE-SET,BanProgramAD,🍃 广告拦截,no-resolve
  - RULE-SET,Hijacking,🍃 广告拦截,no-resolve
  - RULE-SET,Privacy,🍃 广告拦截,no-resolve
  - RULE-SET,BlockHttpDNS,🍃 广告拦截,no-resolve  
  - RULE-SET,Custom_Domain,🚀 默认节点
  - RULE-SET,Bing,🚀 默认节点,no-resolve
  - RULE-SET,OneDrive,☁️ 微软云盘,no-resolve
  - RULE-SET,OpenAI,🇨🇳 自建故障转移,no-resolve
  - RULE-SET,BilibiliHMT-Domain,📺 港台B站
  - RULE-SET,GlobalMedia_Domain,🌍 国际媒体
  - RULE-SET,GFW_Domain,🚀 默认节点
  - RULE-SET,Apple_Domain,🍎 苹果服务
  - RULE-SET,Steam,🚀 默认节点,no-resolve
  - RULE-SET,GlobalMedia,🌍 国际媒体,no-resolve  
  - RULE-SET,GFW,🚀 默认节点,no-resolve
  - RULE-SET,Apple,🍎 苹果服务,no-resolve
  - RULE-SET,Microsoft,Ⓜ️ 微软服务,no-resolve
  - MATCH,DIRECT
```

### Description

同一个配置文件在Windows的clash verge正常工作，在Mac上使用clashX meta更新时提示文件格式不对：test failed，status 1。换用clash verge发现txt格式的ruleset文件没有下载下来（yaml格式的正常），使用yacd面板也不能下载txt文件。
