### ISSUE TITLE
[Bug] 核心崩溃 panic: buffer overflow: cap 32768,start 0, need 18

### ISSUE THREAD

**Issue by wxyzh** [MetaCubeX/Clash.Meta#587]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta alpha-8e88e0b linux amd64 with go1.20.4 Sun May 28 14:53:19 UTC 2023 Use tags: with_gvisor

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
proxies:
  - name: "xxx"
    type: ss
    server: xxx
    port: xxx
    password: xxxxx
    cipher: xchacha20-ietf-poly1305
    udp: true

listeners:
  - name: shadowsocks-in-1
    type: shadowsocks
    port: 
    listen: 0.0.0.0
    # rule: sub-rule-name1 # 默认使用 rules，如果未找到 sub-rule 则直接使用 rules
    # proxy: proxy # 如果不为空则直接将该入站流量交由指定proxy处理(当proxy不为空时，这里的proxy名称必须合法，否则会出错)
    password: 
    cipher: xchacha20-ietf-poly1305

  - name: shadowsocks-in-2
    type: shadowsocks
    port: xxx
    listen: 0.0.0.0
    # rule: sub-rule-name1 # 默认使用 rules，如果未找到 sub-rule 则直接使用 rules
    # proxy: proxy # 如果不为空则直接将该入站流量交:由指定proxy处理(当proxy不为空时，这里的proxy名称必须合法，否则会出错)
    password: 
    cipher: 2022-blake3-chacha20-poly1305
```

### Clash log

```shell
panic: buffer overflow: cap 32768,start 0, need 18

goroutine 831 [running]:
github.com/sagernet/sing/common/buf.(*Buffer).ExtendHeader(0xc000375c80, 0x12)
        github.com/sagernet/sing@v0.2.5-0.20230519030052-49166ac42700/common/buf/buffer.go:147 +0x1b9
github.com/metacubex/sing-shadowsocks2/internal/shadowio.(*Writer).WriteBuffer(0xc000a38460, 0xc000375c80)
        github.com/metacubex/sing-shadowsocks2@v0.0.0-20230528144023-05418c94ed2d/internal/shadowio/writer.go:83 +0x7d
github.com/metacubex/sing-shadowsocks2/shadowaead.(*clientConn).WriteBuffer(0x13de160?, 0xc0002cea80?)
        github.com/metacubex/sing-shadowsocks2@v0.0.0-20230528144023-05418c94ed2d/shadowaead/method.go:267 +0xcb
github.com/sagernet/sing/common/bufio.CopyExtendedBuffer({0x7f40a77513a8?, 0xc000784300}, {0x7f40a775f2b0?, 0xc0002cea80}, {0x7f40a775e578, 0xc000074540}, 0xc000375c80, {0x0, 0x0, 0x0}, ...)
        github.com/sagernet/sing@v0.2.5-0.20230519030052-49166ac42700/common/bufio/copy.go:124 +0x219
github.com/sagernet/sing/common/bufio.CopyExtended({0x7f40a77513a8, 0xc000784300}, {0x7f40a775f2b0?, 0xc0002cea80}, {0x7f40a775e578?, 0xc000074540}, {0x0, 0x0, 0x0}, {0xc00000f440, ...})
        github.com/sagernet/sing@v0.2.5-0.20230519030052-49166ac42700/common/bufio/copy.go:98 +0x4bf
github.com/sagernet/sing/common/bufio.Copy({0x7f40a77513a8, 0xc000784300}, {0x7f40a77513c8?, 0xc000074560?})
        github.com/sagernet/sing@v0.2.5-0.20230519030052-49166ac42700/common/bufio/copy.go:66 +0x778
github.com/sagernet/sing/common/bufio.CopyConnContextList.func1({0x10499ef?, 0xc000375f78?})
        github.com/sagernet/sing@v0.2.5-0.20230519030052-49166ac42700/common/bufio/copy.go:224 +0x75
github.com/sagernet/sing/common/task.(*Group).RunContextList.func1()
        github.com/sagernet/sing@v0.2.5-0.20230519030052-49166ac42700/common/task/task.go:68 +0x84
created by github.com/sagernet/sing/common/task.(*Group).RunContextList
        github.com/sagernet/sing@v0.2.5-0.20230519030052-49166ac42700/common/task/task.go:67 +0x17e
```

### Description

shadowsocks 入站时核心崩溃
与 #386 类似
