### ISSUE TITLE
[Bug] DNS service did not use /etc/hosts even if `use-hosts` is true

### ISSUE THREAD

**Issue by hronro** [MetaCubeX/Clash.Meta#591]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta v1.14.4 linux amd64 with go1.20.3 Fri Apr 28 17:13:27 UTC 2023

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: redir-host
  use-hosts: true
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,apple":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
```

### Description

DNS service did not use /etc/hosts even if `use-hosts` is true
