### ISSUE TITLE
求助"dialer-proxy"的不生效的原因

### ISSUE THREAD

**Issue by dycwuxing** [MetaCubeX/Clash.Meta#593]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash.meta alpha-1120c81

### What OS are you seeing the problem on?

macOS, Linux

### Clash config

```yaml
proxies:
- {"name":"凤凰城02_VLESS_套CF","type":"vless","server":"CF域名", "port":"443","ws-opts":{"path":"/","headers":{"Host":"oracle111.com"}},"uuid":"1234","udp":true, "network":"ws","tls":true,"skip-cert-verify":true,"servername":"oracle111.com"}

- {"name":"凤凰城02_SS_落地","type":"ss","server":"小鸡IP","port":"12556","cipher":"aes-256-gcm","password":"1111","udp":true,dialer-proxy:"凤凰城02_VLESS_套CF"}

- {"name":"凤凰城02_VMESS_落地","type":"vmess","server":"小鸡IP", "port":"452","ws-opts":{"path":"/","headers":{"Host":"oracle111.com"}},"uuid":"1234","udp":true,"tfo":true,"network":"ws","alterId":0,"cipher":"auto",dialer-proxy:"🎩前置代理"}

proxy-groups:
- {name: 🎩前置代理,type: select, proxies: [🐇最低延迟,🔄负载轮询,👋手动选择,⏬下载专用]}
```

### Description

我为落地机做了2个协议,分别是SS和Vmess
建立了一个套CF的Vless协议用来测试

SS协议落地机使用 套CF协议节点的做为前置
Vmess协议落地机使用 机场的节点做为前置,机场节点整体设置一个策略组(🎩前置代理)

在使用中,"套CF协议的节点"和"机场的策略组"都是可以正常使用的,但是两个落地协议都是"Error"
<img width="1411" alt="image" src="https://github.com/MetaCubeX/Clash.Meta/assets/44988562/6453e156-146f-478b-b878-46fc19c10566">

我又尝试了relay
1:使用"🎩前置代理"做为前置时,不通
<img width="569" alt="image" src="https://github.com/MetaCubeX/Clash.Meta/assets/44988562/0bda6f19-3c60-44ba-83b3-8639d79db1f7">
使用"可用节点"做为前置时,通
<img width="548" alt="image" src="https://github.com/MetaCubeX/Clash.Meta/assets/44988562/0be9a801-2799-4192-ad2f-4904497eb9f4">
