### ISSUE TITLE
[Bug] 无法访问仅有AAAA记录的网站

### ISSUE THREAD

**Issue by soraneoumi** [MetaCubeX/Clash.Meta#594]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-7906fbf

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: false
mode: rule
external-controller: 127.0.0.1:9090
geodata-mode: true
tcp-concurrent: true
ipv6: true

tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  endpoint_independent_nat: true

dns:
  enable: true
  use-hosts: true
  ipv6: true
  prefer-h3: true
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:8383
  nameserver:
    - 'tls://1.1.1.1#PROXY'
    - 'tls://[2606:4700:4700::1111]#PROXY'
    - 'https://1.1.1.1/dns-query#PROXY'
    - 'https://[2606:4700:4700::1111]/dns-query#PROXY'
  nameserver-policy:
    'geosite:cn': ['119.29.29.29','182.254.116.116']


proxies:
  - name: "softbank-ss"
    type: ss
    server: 000000
    port: 00000
    dialer-proxy: "relay-ss"
    cipher: 2022-blake3-aes-128-gcm
    password: "000000"
    udp: true
  - name: "relay-ss"
    type: ss
    server: 000000
    port: 00000
    cipher: 2022-blake3-aes-128-gcm
    password: "000000"
    udp: true

rules:
  - GEOSITE,apple@cn,DIRECT
  - GEOSITE,apple-cn,DIRECT
  - GEOSITE,microsoft@cn,DIRECT
  - GEOSITE,geolocation-cn,DIRECT
  - GEOIP,telegram,PROXY,no-resolve
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
```

### Description

最新alpha版本下，无法访问仅有AAAA记录的网站，如 https://ipv6.google.com 或 https://[2606:4700:4700::1111] ，双栈网站正常。
nslookup解析 ipv6.google.com 提示 No response from server
