### ISSUE TITLE
[Bug] urltest结果不会保留

### ISSUE THREAD

**Issue by Karmylr** [MetaCubeX/Clash.Meta#610]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-ge717486

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
proxy-groups:
  - name: 节点
    type: select
    proxies:
      - 自动选择
      - DIRECT
  - name: 自动选择
    type: url-test
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 150
    proxies:
  - name: 往YouTube上传视频
    type: select
    proxies:
  - name: YouTube直播
    type: select
    proxies:
  - name: YouTube视频
    type: select
    proxies:
  - name: Telegram
    type: select
    proxies:
  - name: test-ipv6
    type: select
    proxies:
      - DIRECT
  - name: 国内流量
    type: select
    proxies:
      - DIRECT
      - 节点
  - name: 漏网之鱼
    type: select
    proxies:
      - 节点
      - DIRECT
rules:
 - DOMAIN-KEYWORD,adservice.google,REJECT
 - DOMAIN-SUFFIX,ad.holmesmind.com,REJECT
 - DOMAIN-SUFFIX,addthis.com,REJECT
 - DOMAIN-SUFFIX,adpushup.com,REJECT
 - DOMAIN-SUFFIX,adrecover.com,REJECT
 - DOMAIN-SUFFIX,adroll.com,REJECT
 - DOMAIN-SUFFIX,ads-twitter.com,REJECT
 - DOMAIN-SUFFIX,ads.linkedin.com,REJECT
 - DOMAIN-SUFFIX,adthrive.com,REJECT
 - DOMAIN-SUFFIX,adtng.com,REJECT
 - DOMAIN-SUFFIX,alexametrics.com,REJECT
 - DOMAIN-SUFFIX,amazon-adsystem.com,REJECT
 - DOMAIN-SUFFIX,atm.youku.com,REJECT
 - DOMAIN-SUFFIX,beacon.qq.com,REJECT
 - DOMAIN-SUFFIX,bizible.com,REJECT
 - DOMAIN-SUFFIX,browser-intake-datadoghq.com,REJECT
 - DOMAIN-SUFFIX,chushoushijian.cn,REJECT
 - DOMAIN-SUFFIX,clickagy.com,REJECT
 - DOMAIN-SUFFIX,cnzz.com,REJECT
 - DOMAIN-SUFFIX,cookielaw.org,REJECT
 - DOMAIN-SUFFIX,da.mgtv.com,REJECT
 - DOMAIN-SUFFIX,data.hicloud.com,REJECT
 - DOMAIN-SUFFIX,data.mob.com,REJECT
 - DOMAIN-SUFFIX,datadome.co,REJECT
 - DOMAIN-SUFFIX,doubleclick.net,REJECT
 - DOMAIN-SUFFIX,e.qq.com,REJECT
 - DOMAIN-SUFFIX,ethicalads.io,REJECT
 - DOMAIN-SUFFIX,flurry.com,REJECT
 - DOMAIN-SUFFIX,fuseplatform.net,REJECT
 - DOMAIN-SUFFIX,gaug.es,REJECT
 - DOMAIN-SUFFIX,gdt.qq.com,REJECT
 - DOMAIN-SUFFIX,getui.com,REJECT
 - DOMAIN-SUFFIX,go-mpulse.net,REJECT
 - DOMAIN-SUFFIX,google-analytics.com,REJECT
 - DOMAIN-SUFFIX,googlesyndication.com,REJECT
 - DOMAIN-SUFFIX,googletagmanager.com,REJECT
 - DOMAIN-SUFFIX,googletagservices.com,REJECT
 - DOMAIN-SUFFIX,gvt2.com,REJECT
 - DOMAIN-SUFFIX,heapanalytics.com,REJECT
 - DOMAIN-SUFFIX,hotjar.com,REJECT
 - DOMAIN-SUFFIX,imrworldwide.com,REJECT
 - DOMAIN-SUFFIX,jpush.cn,REJECT
 - DOMAIN-SUFFIX,ldmnq.com,REJECT
 - DOMAIN-SUFFIX,log.aliyuncs.com,REJECT
 - DOMAIN-SUFFIX,log.mgtv.com,REJECT
 - DOMAIN-SUFFIX,logs.datadoghq.com,REJECT
 - DOMAIN-SUFFIX,marketo.net,REJECT
 - DOMAIN-SUFFIX,mediav.co,REJECT
 - DOMAIN-SUFFIX,mediav.com,REJECT
 - DOMAIN-SUFFIX,meta.io,REJECT
 - DOMAIN-SUFFIX,miaozhen.com,REJECT
 - DOMAIN-SUFFIX,moatads.com,REJECT
 - DOMAIN-SUFFIX,monitor.azure.com,REJECT
 - DOMAIN-SUFFIX,onesignal.com,REJECT
 - DOMAIN-SUFFIX,onetrust.com,REJECT
 - DOMAIN-SUFFIX,pangle.io,REJECT
 - DOMAIN-SUFFIX,pbstck.com,REJECT
 - DOMAIN-SUFFIX,penxiangge.com,REJECT
 - DOMAIN-SUFFIX,permutive.app,REJECT
 - DOMAIN-SUFFIX,pipe.aria.microsoft.com,REJECT
 - DOMAIN-SUFFIX,pos.baidu.com,REJECT
 - DOMAIN-SUFFIX,qhupdate.com,REJECT
 - DOMAIN-SUFFIX,quantserve.com,REJECT
 - DOMAIN-SUFFIX,register.xmpush.xiaomi.com,REJECT
 - DOMAIN-SUFFIX,scorecardresearch.com,REJECT
 - DOMAIN-SUFFIX,segment.com,REJECT
 - DOMAIN-SUFFIX,sentry.io,REJECT
 - DOMAIN-SUFFIX,share.baidu.com,REJECT
 - DOMAIN-SUFFIX,sitemaji.com,REJECT
 - DOMAIN-SUFFIX,snigelweb.com,REJECT
 - DOMAIN-SUFFIX,ssp.hinet.net,REJECT
 - DOMAIN-SUFFIX,sznj91.com,REJECT
 - DOMAIN-SUFFIX,taboola.com.cn,REJECT
 - DOMAIN-SUFFIX,trafficjunky.com,REJECT
 - DOMAIN-SUFFIX,users.51.la,REJECT
 - DOMAIN-SUFFIX,vercel-insights.com,REJECT
 - DOMAIN-SUFFIX,visualwebsiteoptimizer.com,REJECT
 - DOMAIN,a2.xinhuanet.com,REJECT
 - DOMAIN,adash.man.aliyuncs.com,REJECT
 - DOMAIN,adimg.uve.weibo.com,REJECT
 - DOMAIN,ads-api.twitter.com,REJECT
 - DOMAIN,ads.vidoomy.com,REJECT
 - DOMAIN,ads2.contentabc.com,REJECT
 - DOMAIN,adservice.sigmob.cn,REJECT
 - DOMAIN,adtrack.ucweb.com,REJECT
 - DOMAIN,adx.ads.heytapmobi.com,REJECT
 - DOMAIN,aegis.qq.com,REJECT
 - DOMAIN,afd.baidu.com,REJECT
 - DOMAIN,alb.reddit.com,REJECT
 - DOMAIN,alimama.alicdn.com,REJECT
 - DOMAIN,als.baidu.com,REJECT
 - DOMAIN,amdc.m.taobao.com,REJECT
 - DOMAIN,amdcopen.m.taobao.com,REJECT
 - DOMAIN,analytics-api.smzdm.com,REJECT
 - DOMAIN,analytics.plex.tv,REJECT
 - DOMAIN,analytics.rayjump.com,REJECT
 - DOMAIN,analytics.regex101.com,REJECT
 - DOMAIN,android.bugly.qq.com,REJECT
 - DOMAIN,app-measurement.com,REJECT
 - DOMAIN,applog.uc.cn,REJECT
 - DOMAIN,bat.bing.com,REJECT
 - DOMAIN,bdapi.ads.oppomobile.com,REJECT
 - DOMAIN,beacon-api.aliyuncs.com,REJECT
 - DOMAIN,beacon.tingyun.com,REJECT
 - DOMAIN,beacons5.gvt3.com,REJECT
 - DOMAIN,browser.events.data.microsoft.com,REJECT
 - DOMAIN,browser.events.data.msn.cn,REJECT
 - DOMAIN,btloader.com,REJECT
 - DOMAIN,btrace.qq.com,REJECT
 - DOMAIN,cbjs.baidu.com,REJECT
 - DOMAIN,cc.swiftype.com,REJECT
 - DOMAIN,cdn-settings.appsflyersdk.com,REJECT
 - DOMAIN,cdn.consentmanager.mgr.consensu.org,REJECT
 - DOMAIN,cdn.privacy-mgmt.com,REJECT
 - DOMAIN,cdnads.geeksforgeeks.org,REJECT
 - DOMAIN,cfg.imtt.qq.com,REJECT
 - DOMAIN,clog.yuanfudao.com,REJECT
 - DOMAIN,clog2.yuanfudao.com,REJECT
 - DOMAIN,clog3.yuanfudao.com,REJECT
 - DOMAIN,clog4.yuanfudao.com,REJECT
 - DOMAIN,clog5.yuanfudao.com,REJECT
 - DOMAIN,clog6.yuanfudao.com,REJECT
 - DOMAIN,collector.github.com,REJECT
 - DOMAIN,cpro.baidu.com,REJECT
 - DOMAIN,csdn-app.log-global.aliyuncs.com,REJECT
 - DOMAIN,d2ezz24t9nm0vu.cloudfront.net,REJECT
 - DOMAIN,d2v02itv0y9u9t.cloudfront.net,REJECT
 - DOMAIN,daa.shuzilm.cn,REJECT
 - DOMAIN,data.bilibili.com,REJECT
 - DOMAIN,datacollector-drcn.dt.hicloud.com,REJECT
 - DOMAIN,dig.bdurl.net,REJECT
 - DOMAIN,dig.zjurl.cn,REJECT
 - DOMAIN,dm.toutiao.com,REJECT
 - DOMAIN,dotcounter.douyucdn.cn,REJECT
 - DOMAIN,dotserver.douyucdn.cn,REJECT
 - DOMAIN,dragate.dc.oppomobile.com,REJECT
 - DOMAIN,dualstack-logs.amap.com,REJECT
 - DOMAIN,dup.baidustatic.com,REJECT
 - DOMAIN,eclick.baidu.com,REJECT
 - DOMAIN,erebor.douban.com,REJECT
 - DOMAIN,event.csdn.net,REJECT
 - DOMAIN,events.mapbox.com,REJECT
 - DOMAIN,fclog.baidu.com,REJECT
 - DOMAIN,fourier.taobao.com,REJECT
 - DOMAIN,fp-it.fengkongcloud.com,REJECT
 - DOMAIN,frog.yuanfudao.com,REJECT
 - DOMAIN,gc.zgo.at,REJECT
 - DOMAIN,h.trace.qq.com,REJECT
 - DOMAIN,hm.baidu.com,REJECT
 - DOMAIN,log.voicecloud.cn,REJECT
 - DOMAIN,hpd.baidu.com,REJECT
 - DOMAIN,hubble.netease.com,REJECT
 - DOMAIN,i.snssdk.com,REJECT
 - DOMAIN,ib.snssdk.com,REJECT
 - DOMAIN,ichnaea-web.netflix.com,REJECT
 - DOMAIN,imasdk.googleapis.com,REJECT
 - DOMAIN,ivy.pconline.com.cn,REJECT
 - DOMAIN,iyes.youku.com,REJECT
 - DOMAIN,js-agent.newrelic.com,REJECT
 - DOMAIN,js.driftt.com,REJECT
 - DOMAIN,launches.appsflyer.com,REJECT
 - DOMAIN,live.primis.tech,REJECT
 - DOMAIN,log.avlyun.com,REJECT
 - DOMAIN,log.snssdk.com,REJECT
 - DOMAIN,log.tpns.tencent.com,REJECT
 - DOMAIN,log.umsns.com,REJECT
 - DOMAIN,logs.51cto.com,REJECT
 - DOMAIN,logs.amap.com,REJECT
 - DOMAIN,logservice.hicloud.com,REJECT
 - DOMAIN,logservice1.dbankcloud.cn,REJECT
 - DOMAIN,logservice1.hicloud.com,REJECT
 - DOMAIN,m1.51kaowang.com,REJECT
 - DOMAIN,mcs.snssdk.com,REJECT
 - DOMAIN,metric.huya.com,REJECT
 - DOMAIN,metrics.nvidia.com,REJECT
 - DOMAIN,mlog.bigda.com,REJECT
 - DOMAIN,mobads.baidu.com,REJECT
 - DOMAIN,mon.snssdk.com,REJECT
 - DOMAIN,msg-intl.qy.net,REJECT
 - DOMAIN,msg.qy.net,REJECT
 - DOMAIN,mtrace.qq.com,REJECT
 - DOMAIN,net.rayjump.com,REJECT
 - DOMAIN,p.tanx.com,REJECT
 - DOMAIN,pcapp-data-collect.youku.com,REJECT
 - DOMAIN,pingfore.qq.com,REJECT
 - DOMAIN,pingtas.qq.com,REJECT
 - DOMAIN,puds.ucweb.com,REJECT
 - DOMAIN,push.zhanzhang.baidu.com,REJECT
 - DOMAIN,pv.sohu.com,REJECT
 - DOMAIN,px.ucweb.com,REJECT
 - DOMAIN,qpb0.sohu.com,REJECT
 - DOMAIN,qpb1.sohu.com,REJECT
 - DOMAIN,r.apkpure.net,REJECT
 - DOMAIN,rabc1.iteye.com,REJECT
 - DOMAIN,report-stats.ad.jiguang.cn,REJECT
 - DOMAIN,report.edu.qq.com,REJECT
 - DOMAIN,s.union.360.cn,REJECT
 - DOMAIN,sax.sina.com.cn,REJECT
 - DOMAIN,sbeacon.sina.com.cn,REJECT
 - DOMAIN,sdk.51.la,REJECT
 - DOMAIN,securemvt.apple.com.cn,REJECT
 - DOMAIN,sensors.ibreader.com,REJECT
 - DOMAIN,servedbyadbutler.com,REJECT
 - DOMAIN,smetrics.nvidia.com,REJECT
 - DOMAIN,sofire.bdstatic.com,REJECT
 - DOMAIN,sp0.baidu.com,REJECT
 - DOMAIN,sp1.baidu.com,REJECT
 - DOMAIN,static.cloudflareinsights.com,REJECT
 - DOMAIN,stats.wp.com,REJECT
 - DOMAIN,statwup.huya.com,REJECT
 - DOMAIN,svibeacon.onezapp.com,REJECT
 - DOMAIN,target.microsoft.com,REJECT
 - DOMAIN,tdid.m.qq.com,REJECT
 - DOMAIN,tobapplog.ctobsnssdk.com,REJECT
 - DOMAIN,toblog.ctobsnssdk.com,REJECT
 - DOMAIN,tpstelemetry.tencent.com,REJECT
 - DOMAIN,tr.www.cloudflare.com,REJECT
 - DOMAIN,track.sohu.com,REJECT
 - DOMAIN,tunion-api.m.taobao.com,REJECT
 - DOMAIN,twin-iq.kickfire.com,REJECT
 - DOMAIN,uc.ucweb.com,REJECT
 - DOMAIN,ulogs.umeng.com,REJECT
 - DOMAIN,ulogs.umengcloud.com,REJECT
 - DOMAIN,umengacs.m.taobao.com,REJECT
 - DOMAIN,umengjmacs.m.taobao.com,REJECT
 - DOMAIN,unagi.amazon.com,REJECT
 - DOMAIN,wkctj.baidu.com,REJECT
 - DOMAIN,wwads.cn,REJECT
 - DOMAIN,www.clarity.ms,REJECT
 - DOMAIN,zhihu-web-analytics.zhihu.com,REJECT
 - DOMAIN,zz.bdstatic.com,REJECT
 - DOMAIN-SUFFIX,bilivideo.com,DIRECT
 - DOMAIN-SUFFIX,bilivideo.cn,DIRECT
 - DST-PORT,22,DIRECT
 - DST-PORT,123,DIRECT
 - SRC-PORT,25565,DIRECT
 - DOMAIN,ikandy.fun,DIRECT
 - DOMAIN-SUFFIX,qq.com,DIRECT
 - DOMAIN-SUFFIX,bdys03.com,DIRECT
 - DOMAIN-SUFFIX,ipv4.duiadns.net,test-ipv6
 - DOMAIN-SUFFIX,ipv6-test.pl,test-ipv6
 - DOMAIN-SUFFIX,ipv6.br,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.alpinedc.ch,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.arauc.br,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.belwue.net,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.carnet.hr,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.cgates.lt,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.ch,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.cl,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.com,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.com.au,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.csclub.uwaterloo.ca,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.cz,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.do.ayepv6.com,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.epic.network,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.fratec.net,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.freerangecloud.com,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.go6.si,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.hkg.vr.org,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.hu,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.in,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.is,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.iu13.net,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.ke.liquidtelecom.ne,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.ke.liquidtelecom.net,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.micso.network,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.nl,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.noroutetohost.net,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.ro,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.roedu.net,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.se,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.sin.vr.org,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.ttk.ru,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.vu.ayepv6.com,test-ipv6
 - DOMAIN-SUFFIX,testipv6.cn,test-ipv6
 - DOMAIN-SUFFIX,testipv6.de,test-ipv6
 - DOMAIN,ipv4-test-ipv6.eurobilltracker.com,test-ipv6
 - DOMAIN,ipv6-test-ipv6.eurobilltracker.com,test-ipv6
 - DOMAIN,ipv6-test.com,test-ipv6
 - DOMAIN,ipv6.duiadns.ne,test-ipv6
 - DOMAIN,ipv6.joram.it,test-ipv6
 - DOMAIN,ipv6.mudgee.host,test-ipv6
 - DOMAIN,ipv6.nsx.de,test-ipv6
 - DOMAIN,ipv6.stdio.be,test-ipv6
 - DOMAIN-SUFFIX,v6test.snozzages.com,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.ams.vr.org,test-ipv6
 - DOMAIN-SUFFIX,test-ipv6.tld.sk,test-ipv6
 - IP-CIDR,91.108.56.0/22,Telegram
 - IP-CIDR,91.108.4.0/22,Telegram
 - IP-CIDR,91.108.8.0/22,Telegram
 - IP-CIDR,91.108.16.0/22,Telegram
 - IP-CIDR,91.108.12.0/22,Telegram
 - IP-CIDR,149.154.160.0/20,Telegram
 - IP-CIDR,91.105.192.0/23,Telegram
 - IP-CIDR,91.108.20.0/22,Telegram
 - IP-CIDR,185.76.151.0/24,Telegram
 - IP-CIDR,2001:b28:f23d::/48,Telegram
 - IP-CIDR,2001:b28:f23f::/48,Telegram
 - IP-CIDR,2001:67c:4e8::/48,Telegram
 - IP-CIDR,2001:b28:f23c::/48,Telegram
 - IP-CIDR,2a0a:f280::/32,Telegram
 - AND,((DOMAIN-SUFFIX,rtmp.youtube.com),(DST-PORT,1935)),YouTube直播
 - DOMAIN,upload.youtube.com,往YouTube上传视频
 - DOMAIN-SUFFIX,googlevideo.com,YouTube视频
 - DOMAIN-SUFFIX,yahoo.com,节点
 - GEOIP,CN,国内流量
 - MATCH,漏网之鱼
```

### Description

在dashboard点击测速按钮后可以正常测延迟，但是刷新网页之后就恢复到点击测速按钮之前了

https://github.com/MetaCubeX/Clash.Meta/assets/69903376/af776151-26ad-4f95-8d6d-25733a4d51d2
