### ISSUE TITLE
[Bug] 关于vless-ws配置里的3个问题

### ISSUE THREAD

**Issue by toyo2333** [MetaCubeX/Clash.Meta#616]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.14.5

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
- name: "vless-ws"
    type: vless
    server: server
    port: 443
    uuid: uuid
    udp: true
    tls: true
    network: ws
    # client-fingerprint: random # Available: "chrome","firefox","safari","random","none"
    servername: example.com # priority over wss host
    # skip-cert-verify: true
    # fingerprint: xxxx
    ws-opts:
      path: "/"
      headers:
        Host: example.com
```

### Description

请教，关于vless-ws的的配置的疑问

1，这里的upd:true开关的作用是什么呢？是否需要开启（我原来是再v2rayN里的客户端的vless配置里没看到这个选项），请指教
2，    servername: example.com 这里。。。我的address就是一个域名，我在v2rayN和小火箭里没有看到servername选项，这里填写相同的？或者注释掉？
3，  headers下面的 Host: example.com这个该填写什么呢？我的v2rayN和小火箭里这里都是留空的，那么咱们这里应该写什么呢？null？none？ 还是把headers整个注释掉？

盼望解答，谢谢！
