### ISSUE TITLE
[Bug] 关于配置文件里傻瓜示例里DNS的一个问题

### ISSUE THREAD

**Issue by toyo2333** [MetaCubeX/Clash.Meta#617]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.14.5

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - '*'
    - '+.lan'
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - 'tls://8.8.4.4#dns'
    - 'tls://1.0.0.1#dns'
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
```

### Description

傻瓜配置文件示例里DNS配置如上，这里有个疑问

我看整个策略比较严谨
1，域名解析服务器的域名doh.pub等交给阿里云解析
2，国内的域名默认交给阿里云和腾讯解析
3，其他的（国外访问）交给8.8.4.4和1.0.0.1解析

但这里 
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - 
为什么又指定了交给腾讯去解析？

比如我的VPS在国外，用域名访问，那在这个环节不就泄露了么？或者说我的理解有误？

请指教！
