### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lateid** [MetaCubeX/Clash.Meta#623]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash -1.14.5 & clash -Prerelease-Alpha

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mixed-port: *

tcp-concurrent: true
geodata-mode: true
global-client-fingerprint: random

allow-lan: true
bind-address: "*"
log-level: info
external-controller: *
secret: *

# DNS配置
dns:
  enable: true # 关闭将使用系统 DNS
  prefer-h3: true # 开启 DoH 支持 HTTP/3，将并发尝试
  listen: 0.0.0.0:53 # 开启 DNS 服务器监听
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
    # - tls://1.12.12.12:853
    # - tls://223.5.5.5:853
    # - system  # append DNS server from system configuration. If not found, it would print an error log and skip.
  enhanced-mode: fake-ip # or redir-host
  
  fake-ip-range: 198.18.0.1/16 # fake-ip 池设置
  
  nameserver:
    - https://doh.pub/dns-query # DNS over HTTPS
    - https://dns.alidns.com/dns-query#h3=true # 强制 HTTP/3，与 perfer-h3 无关，强制开启 DoH 的 HTTP/3 支持，若不支持将无法使用
    - https://mozilla.cloudflare-dns.com/dns-query#DNS&h3=true # 指定策略组和使用 HTTP/3
    - 8.8.8.8 # default value
    - tls://223.5.5.5:853 # DNS over TLS
    - dhcp://en0 # dns from dhcp
    - quic://dns.adguard.com:784 # DNS over QUIC
    # - '8.8.8.8#en0' # 兼容指定DNS出口网卡
 
  nameserver-policy:
    #   'www.baidu.com': '114.114.114.114'
    #   '+.internal.crop.com': '10.0.0.1'
    "geosite:cn,private,apple":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "www.baidu.com,+.google.cn": [223.5.5.5, https://dns.alidns.com/dns-query]
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53

# 嗅探域名 可选配置
sniffer:
  enable: false
  override-destination: false
  sniff: # TLS 默认如果不配置 ports 默认嗅探 443
    TLS:
    #  ports: [443, 8443]
    
    # 默认嗅探 80
    HTTP: # 需要嗅探的端口
      
      ports: [80, 8080-8880]
      # 可覆盖 sniffer.override-destination
      override-destination: true
  force-domain:
    - +.v2ex.com
  sniffing:
    - tls
    - http
  port-whitelist:
    - "80"
    - "443"
    # - 8000-9999
proxies:
   - name: "hinet"
      server: *
      port: 33552
      type: tuic
      uuid: *
      password: *
      # heartbeat-interval: 10000
      alpn: [h3]
      disable-sni: true
      reduce-rtt: true
      udp-relay-mode: quic # Available: "native", "quic". Default: "native"
      congestion-controller: bbr # Available: "cubic", "new_reno", "bbr". Default: "cubic"
      # max-udp-relay-packet-size: 1500
      fast-open: true
      # max-open-streams: 100 # default 100, too many open streams may hurt performance
      sni: *
```

### Description

使用clash.meta内核，tuic协议的代理。多线程speedtest测速时，下载速度测试完后无法测试上传速度，此时所有的节点显示超时网络连接失败，但是其他设备使用同一节点一切正常，实际情况应为本地clash.meta内核崩溃。垦请大家测试一下，并向大家咨询是否有解决方法。
