### ISSUE TITLE
Thunderbird无法收发邮件

### ISSUE THREAD

**Issue by CussiusKon** [MetaCubeX/Clash.Meta#633]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.14.5

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mode: rule
mixed-port: 10800
allow-lan: false
log-level: warning
ipv6: false
secret: xxx
external-controller: 127.0.0.1:9093
dns:
  enable: true
  prefer-h3: false
  listen: 0.0.0.0:53
  ipv6: true
  ipv6-timeout: 300
  default-nameserver:
  - https://1.1.1.1/dns-query
  - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter:
  - '*.lan'
  - localhost.ptlogin2.qq.com
  - +.msftconnecttest.com
  - connectivitycheck.gstatic.com
  nameserver:
  - https://1.1.1.1/dns-query#h3=true
  - https://1.12.12.12/dns-query#h3=true
  nameserver-policy:
    +.msftconnecttest.com:
    - 223.5.5.5
    RULE-SET:person-domain-direct-blackmode:
    - https://doh.pub/dns-query#h3=true
    - https://dns.alidns.com/dns-query#h3=true
    RULE-SET:person-domain-proxy-blackmode:
    - https://1.1.1.1/dns-query#h3=true
  fallback: []
tun:
  enable: true
  device: Meta
  stack: system
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
  mtu: 9000
  strict-route: true
profile:
  store-selected: true
  store-fake-ip: true
bind-address: '*'
sniffer:
  enable: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    TLS: null
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
  force-domain:
  - +.v2ex.com
  skip-domain:
  - +.apple.com
  - Mijia Cloud
  - +.jd.com
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb
geodata-mode: true
find-process-mode: strict
global-client-fingerprint: chrome
proxies:
- name: xxx
  type: vless
  server: xxx
  port: 8443
  uuid: xxx
  network: tcp
  tls: true
  servername: xxx
  udp: true
  flow: xtls-rprx-vision
  client-fingerprint: chrome
rules:
- RULE-SET,person-reject,REJECT
- RULE-SET,person-applications,DIRECT
- RULE-SET,applications,DIRECT
- RULE-SET,person-domain-direct-blackmode,DIRECT
- GEOSITE,spotify,us-vision
- RULE-SET,person-domain-proxy-blackmode,xxx
- RULE-SET,person-ip-direct-blackmode,DIRECT,no-resolve
- RULE-SET,telegramcidr,xxx,no-resolve
- RULE-SET,person-ip-proxy,xxx,no-resolve
- MATCH,DIRECT
rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  person-reject:
    type: file
    behavior: classical
    path: ./ruleset/person-reject.yaml
  person-domain-direct:
    type: file
    behavior: classical
    path: ./ruleset/person-domain-direct.yaml
  person-domain-direct-blackmode:
    type: file
    behavior: classical
    path: ./ruleset/person-domain-direct-blackmode.yaml
  person-domain-proxy:
    type: file
    behavior: classical
    path: ./ruleset/person-domain-proxy.yaml
  person-domain-proxy-blackmode:
    type: file
    behavior: classical
    path: ./ruleset/person-domain-proxy-blackmode.yaml
  person-ip-direct:
    type: file
    behavior: classical
    path: ./ruleset/person-ip-direct.yaml
  person-ip-proxy:
    type: file
    behavior: classical
    path: ./ruleset/person-ip-proxy.yaml
  person-ip-direct-blackmode:
    type: file
    behavior: ipcidr
    path: ./ruleset/person-ip-direct-blackmode.yaml
  icloud:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400
  person-applications:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/person-applications.yaml
    interval: 86400
```

### Clash log

```shell
time="2023-06-22T18:29:52.5048328+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) 198.18.0.1:56001(AvastSvc.exe) --> imap.163.com:993 error: connect failed: dial tcp 103.74.29.45:993: connectex: The requested address is not valid in its context. | connect failed: no ip address"
time="2023-06-22T18:29:52.5200689+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) 198.18.0.1:56001(AvastSvc.exe) --> imap.163.com:993 error: connect failed: dial tcp 103.74.29.45:993: connectex: The requested address is not valid in its context. | connect failed: no ip address"
time="2023-06-22T18:29:52.5200689+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) 198.18.0.1:55999(AvastSvc.exe) --> imap.aliyun.com:993 error: connect failed: dial tcp 59.82.9.176:993: connectex: The requested address is not valid in its context. | connect failed: no ip address"
time="2023-06-22T18:29:52.5354834+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) 198.18.0.1:56001(AvastSvc.exe) --> imap.163.com:993 error: connect failed: dial tcp 103.74.29.45:993: connectex: The requested address is not valid in its context. | connect failed: no ip address"
time="2023-06-22T18:29:52.5513395+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) 198.18.0.1:55999(AvastSvc.exe) --> imap.aliyun.com:993 error: connect failed: dial tcp 59.82.9.176:993: connectex: The requested address is not valid in its context. | connect failed: no ip address"
time="2023-06-22T18:29:52.5736595+08:00" level=debug msg="[Rule] use default rules"
time="2023-06-22T18:29:52.5741864+08:00" level=warning msg="[TCP] dial DIRECT (match Match/) 198.18.0.1:56001(AvastSvc.exe) --> imap.163.com:993 error: connect failed: dial tcp 103.74.29.45:993: connectex: The requested address is not valid in its context. | connect failed: no ip address"
```

### Description

Thunderbird进程走直连规则，无法收发邮件。包括163 qq aliyun。
