### ISSUE TITLE
[Bug] 配置文件测速问题

### ISSUE THREAD

**Issue by WangHaonie** [MetaCubeX/Clash.Meta#634]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-919daf0

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
rules:
proxy-providers: {}
rule-providers: {}
profile:
  store-selected: true
  store-fake-ip: true
tun:
  enable: true
  stack: system
  auto-detect-interface: true
  auto-route: true
  dns-hijack:
    - any:53
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:1053
  ipv6: false
  use-hosts: false
  default-nameserver:
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
  nameserver-policy:
    geosite:cn: 119.29.29.29
    geolocation-!cn: 119.29.29.29
    gfw: 119.29.29.29
  nameserver:
    - 119.29.29.29
  fallback:
    - 119.29.29.29
  proxy-server-nameserver:
    - 119.29.29.29
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
geodata-mode: true
geox-url:
  geoip: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat
  geosite: https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat
  mmdb: https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb
find-process-mode: always
tcp-concurrent: true
hosts:
  diskgenius.cn: 0.0.0.0
  www.diskgenius.cn: 0.0.0.0
```

### Clash log

```shell
见下方 Description
```

### Description

看样子像是切换到另一个配置文件之后，依然在对上一个配置文件进行测速，日志如下 (77.4 MB)：(是个 4MB 的 7z 压缩包 )
[2023-06-22-083118.jpg](https://github.com/MetaCubeX/Clash.Meta/assets/68315280/db4cb969-b017-495f-a509-ad6658069cbe)
另外内存占用也好像有一点点高 (277 MB)，这是 heap (没有压缩)
[heap.jpg](https://github.com/MetaCubeX/Clash.Meta/assets/68315280/b55de8ff-439d-463c-822a-793e53e20ef7)
