### ISSUE TITLE
[Bug] macOS 14.0 Beta版  软件闪退

### ISSUE THREAD

**Issue by ningnw** [MetaCubeX/Clash.Meta#637]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

最新

### Clash config

```yaml
# !!当前配置文件请使用基于 Clash.Meta 内核程序
mixed-port: 7890
allow-lan: true
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enabled: true
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853

script:
  code: |
    def main(ctx, metadata):
      # Log ProcessName
      ctx.log('Process Name: ' + ctx.resolve_process_name(metadata))
      return 'DIRECT'

proxies:


proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动选择
  - name: 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
  - name: 全球直连
    type: select
    proxies:

rules:
  - DOMAIN-SUFFIX,localhost,全球直连
  - IP-CIDR,10.0.0.0/8,全球直连,no-resolve
  - IP-CIDR,127.0.0.0/8,全球直连,no-resolve
  - IP-CIDR,172.16.0.0/12,全球直连,no-resolve
  - IP-CIDR,192.168.0.0/16,全球直连,no-resolve
  - IP-CIDR6,::1/128,全球直连,no-resolve
  - DOMAIN-SUFFIX,internet.com,全球直连
  - GEOIP,CN,全球直连
# 长风网站，自动注入
  - DOMAIN-SUFFIX,v2rayse.com,节点选择
  - DOMAIN-SUFFIX,cff.pw,节点选择
  - DOMAIN-SUFFIX,vpnse.org,节点选择
  - DOMAIN-SUFFIX,cfmem.com,节点选择
  - MATCH,节点选择
```

### Description

升级了14.0 Beta版之后，软件开机自启动可以正常运行，右上角菜单栏也正常显示网速
但是点击了软件图标之后，软件立刻自动闪退
窗口打不开，麻烦回复一下在哪里可以查看日志，然后我补充上
