### ISSUE TITLE
[Bug] 1.15.0 版本健康检查报错过多， 1.14.5 正常。

### ISSUE THREAD

**Issue by M1A6I3L** [MetaCubeX/Clash.Meta#640]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.15.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
z: &z {url: 'https://apple.com', interval: 999, tolerance: 999, lazy: true}
y: &y {type: http, interval: 54321, health-check: {<<: *z, enable: true}}
proxy-providers:
  a: {<<: *y, path: ./proxy_provider/a.yaml, url: ""}
  b: {<<: *y, path: ./proxy_provider/b.yaml, url: ""}
  c: {<<: *y, path: ./proxy_provider/c.yaml, url: ""}
proxy-groups:
  - {<<: *z, name: P, type: url-test, proxies: [DIRECT, REJECT], use: [a, b, c]}
  - {<<: *z, name: S, type: url-test, proxies: [DIRECT, REJECT], use: [a, b, c]}
  - {<<: *z, name: D, type: select, proxies: [DIRECT, P, S, REJECT]}
  - {<<: *z, name: R, type: select, proxies: [REJECT, P, S, DIRECT]}
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- SRC-IP-CIDR,192.168.100.71/31,D
- SRC-IP-CIDR,192.168.100.74/31,P
- SRC-IP-CIDR,192.168.100.77/31,S
- GEOSITE,CATEGORY-ADS-ALL,R
- SRC-IP-CIDR,192.168.100.82/31,D
- SRC-IP-CIDR,192.168.100.85/31,P
- SRC-IP-CIDR,192.168.100.88/31,S
- GEOSITE,CN,D
- GEOIP,CN,D
- GEOSITE,GEOLOCATION-!CN@CN,D
- DOMAIN-KEYWORD,EMBY,S
- SRC-IP-CIDR,192.168.100.93/31,D
- SRC-IP-CIDR,192.168.100.96/31,P
- SRC-IP-CIDR,192.168.100.99/31,S
- MATCH,P
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
log-level: error
allow-lan: true
external-controller: 0.0.0.0:9090
secret: '123456'
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: true
interface-name: pppoe-wan
geodata-mode: true
geodata-loader: standard
tcp-concurrent: true
find-process-mode: 'off'
global-client-fingerprint: random
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - 223.5.5.5
  - https://doh.pub/dns-query
  - https://223.5.5.5/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
sniffer:
  enable: true
  parse-pure-ip: true
profile:
  store-selected: true
  store-fake-ip: true
authentication:
- Clash:vc95kkh8
```
```


### Clash log

```shell
非log能体现的问题，再加上太长，就不放了。详细问题在下面 Description 写明

基本上就是围绕这两行

level=warning msg="because P failed multiple times, active health check"
level=debug msg="Start New Health Checking {859cccd7-8747-4825-a1b9-efb1a3033d3a}"
```
```


### Description

升级 1.15.0 后发现节点频繁掉线，机场群表示无异常，退回 1.14.5 后正常。
多次升降级对比（Alpha和1.15.0表现一致）：

1、 1.15.0 `because failed multiple times, active health check`  一个小时出现了26次（这是找问题时发现的，不包含下面针对性测试时出现的次数，应该接近日常使用出现的频率吧）。 1.14.5 没有出现过。

2、健康检查过程中又会触发 `failed multiple times, active health check` ，导致短时间内多次连接机场全部节点被风控，直接失联了超过一半节点。
![1](https://github.com/MetaCubeX/Clash.Meta/assets/58336295/35c5e7a0-5ebc-4e5c-8777-6f1a8398f511)
![2](https://github.com/MetaCubeX/Clash.Meta/assets/58336295/a86a9bce-bd1e-4581-aec3-84c2e7ac4baa)

3、一次 `failed` 会触发多个 `Health Checking`。但因为 1.14.5  `interval`  设定而启动的测试也会出现多个，不确定失联是否和多个 `Health Checking` 有关
![3](https://github.com/MetaCubeX/Clash.Meta/assets/58336295/b0927d60-1169-453d-93e9-e0668319558a)

4、如果通过 Yacd-meta 手动指定了 `url-test` 的主节点，那么 `failed` 的次数会更多（非确定，可能是巧合，删除db文件后运行1.15.0连着出现了6次和4次。手动指定主节点后连着出现了7次和9次，下面放一张9次的图）
![4](https://github.com/MetaCubeX/Clash.Meta/assets/58336295/d1ae2b9c-0ec9-46a4-8e78-b2544a9df000)

现在已经退回 1.14.5 了，写 issue 又半个多小时，没出现健康检查问题。 ~~另感谢机场这六个多小时只风控没封我号。~~
