### ISSUE TITLE
[Feature] supporting ODOH in nameserver, fallback & ...

### ISSUE THREAD

**Issue by Graveyard9988** [MetaCubeX/Clash.Meta#643]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

6h

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
nameserver:
    - h3://223.5.5.5/dns-query
    - h3://223.6.6.6/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
  proxy-server-nameserver:
    - https://dns.google.com/dns-query
    - h3://odoh.cloudflare-dns.com/dns-query
    - h3://anycast.dns.nextdns.io/dns-query
    - h3://dns.nextdns.io/dns-query
  fallback:
    - https://dns.google.com/dns-query
    - h3://odoh.cloudflare-dns.com/dns-query
    - h3://anycast.dns.nextdns.io/dns-query
    - h3://dns.nextdns.io/dns-query
```

### Clash log

```shell
..
```

### Description

  nameserver:
    - h3://223.5.5.5/dns-query
    - h3://223.6.6.6/dns-query
    - https://1.12.12.12/dns-query
    - https://120.53.53.53/dns-query
  proxy-server-nameserver:
    - https://dns.google.com/dns-query
    - h3://odoh.cloudflare-dns.com/dns-query
    - h3://anycast.dns.nextdns.io/dns-query
    - h3://dns.nextdns.io/dns-query
  fallback:
    - https://dns.google.com/dns-query
    - h3://odoh.cloudflare-dns.com/dns-query
    - h3://anycast.dns.nextdns.io/dns-query
    - h3://dns.nextdns.io/dns-query
