### ISSUE TITLE
[Bug] 在Windows上无法使用tuic_V5的配置

### ISSUE THREAD

**Issue by ouyeantai** [MetaCubeX/Clash.Meta#646]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [X]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clash alpha 0b1aff5

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
- name: proxy
      server: server.com
      port: 18386
      type: tuic
      user: kdu73927-d1782-njc8-n9xs-ncx873k7du38
      password: _V3I)_sGCglA1%kc$fRX
      heartbeat-interval: 3000
      alpn: [h3]
      disable-sni: false
      reduce-rtt: true
      request-timeout: 8000
      udp-relay-mode: native # Available: "native", "quic". Default: "native"
      congestion-controller: bbr # Available: "cubic", "new_reno", "bbr". Default: "cubic"
      fast-open: false
      skip-cert-verify: true
```

### Description

在Windows上无法使用tuic_v5的配置，已经在最新的clash_verge上尝试了，连不通。也在windows上直接使用最新的clash meta alpha core去运行相同的配置文件，也是不行的。但是同样的配置文件改为tuic_v4的配置，不管是VERGE还是“裸CORE”运行，都没问题。同样的配置在clash meta for android上，不管是v4还是v5都能正常连通。

我的服务端也是用docker跑的clash meta 的alpha分支，一直保持同步最新的版本。
