### ISSUE TITLE
[Bug] System hosts not loaded in Clash Android

### ISSUE THREAD

**Issue by JeelsBoobz** [MetaCubeX/Clash.Meta#649]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.15.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
tproxy-port: 9898
redir-port: 9797
mode: 'rule'
allow-lan: true
unified-delay: true
strict-urltest: true
bind-address: "*"
log-level: silent
ipv6: false
geodata-mode: true
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"
tcp-concurrent: true
external-controller: 0.0.0.0:9090
external-ui: ./dashboard
hosts:
  'jeelsboobz.gov.id': 127.0.0.1
  'knmod.com': 47.88.94.221
  'fakecez.com': 47.88.94.221
  '+.senpaimod.xyz': 47.88.94.221
  '+.vipn3.my.id': 47.88.94.221
profile:
  store-selected: true
  store-fake-ip: false
dns:
  enable: true
  ipv6: false
  default-nameserver:
    - 8.8.8.8
    - 8.8.4.4
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter: []
  nameserver:
    - 8.8.8.8
    - 8.8.4.4
  fallback-filter:
    geoip: false
    geoip-code: 'CN'
    geosite: []
    domain: []
    ipcidr: []
sniffer:
  enable: true
  override-destination: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
  sniffing:
    - tls
    - http
  port-whitelist:
    - 80
    - 443
  skip-domain: []
  force-domain: []
tun:
  enable: false
  device: utun
  stack: system
  dns-hijack:
    - 'any:53'
    - 'tcp://any:53'
  auto-route: false
  auto-detect-interface: false
iptables: {enable: false}
interface-name: ""
find-process-mode: always
proxies:
proxy-groups:
  - name: DEFAULT
    type: select
    url: https://connectivitycheck.gstatic.com/generate_204
    interval: 120
    tolerance: 150
    lazy: true
    proxies:
      - SINGAPORE
      - INDONESIA
    use:
      - CASPER
      - HOWDY
      - TheFool-ID
      - TheFool-SG
  - name: GAMING
    type: select
    url: https://connectivitycheck.gstatic.com/generate_204
    interval: 120
    tolerance: 150
    lazy: true
    proxies:
      - SINGAPORE
      - INDONESIA
      - DIRECT
    use:
      - CASPER
      - HOWDY
      - TheFool-ID
      - TheFool-SG
  - name: INDONESIA
    type: load-balance
    strategy: sticky-sessions
    url: https://connectivitycheck.gstatic.com/generate_204
    interval: 120
    tolerance: 150
    lazy: true
    filter: "🇮🇩"
    use:
      - CASPER
      - HOWDY
      - TheFool-ID
  - name: SINGAPORE
    type: load-balance
    strategy: sticky-sessions
    url: https://connectivitycheck.gstatic.com/generate_204
    interval: 120
    tolerance: 150
    lazy: true
    filter: "🇸🇬"
    use:
      - CASPER
      - HOWDY
      - TheFool-SG
  - name: ADS
    type: select
    proxies:
      - REJECT
      - PASS
proxy-providers:
  CASPER:
    type: file
    interval: 21600
    path: ./provider/proxy/casper.xl
    health-check:
      enable: true
      interval: 10
      lazy: true
      url: https://connectivitycheck.gstatic.com/generate_204
  HOWDY:
    type: file
    interval: 21600
    path: ./provider/proxy/howdy.xl
    health-check:
      enable: true
      interval: 120
      lazy: true
      url: https://connectivitycheck.gstatic.com/generate_204
  TheFool-ID:
    type: http
    interval: 21600
    path: ./provider/proxy/global-id.xl
    url: ""
    health-check:
      enable: true
      interval: 120
      lazy: true
      url: https://connectivitycheck.gstatic.com/generate_204
  TheFool-SG:
    type: http
    interval: 21600
    path: ./provider/proxy/global-sg.xl
    url: ""
    health-check:
      enable: true
      interval: 120
      lazy: true
      url: https://connectivitycheck.gstatic.com/generate_204
rule-providers:
  CATEGORY-BASIC-ADS:
    type: http
    behavior: domain
    interval: 86400
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_basicads.yaml
    path: ./provider/rule/rule_basicads.yml
  WhatsApp:
    type: http
    behavior: classical
    interval: 86400
    url: https://pastebin.com/raw/huZ6fA1A
    path: ./provider/rule/whatsapp.yml
rules:
  # Shortlink #
  - DOMAIN-SUFFIX,semawur.com,INDONESIA
  # Whatsapp #
  - RULE-SET,WhatsApp,DIRECT
  # AdBlock #
  - GEOSITE,CATEGORY-ADS,ADS
  - GEOSITE,CATEGORY-ADS-ALL,ADS
  - RULE-SET,CATEGORY-BASIC-ADS,ADS
  # Dana #
  - DOMAIN-KEYWORD,m.dana.id,INDONESIA
  # Google #
  - OR,((DOMAIN,google.com),(DOMAIN,www.google.com)),INDONESIA
  # CODM GARENA #
  - DOMAIN-KEYWORD,dl.codm.cdn.garenanow.com,DEFAULT
  - OR,((DOMAIN-KEYWORD,.connect.garenanow.com),(DOMAIN-KEYWORD,.connect.garena.com)),INDONESIA
  - AND,((PROCESS-NAME,com.garena.game.codm),(DST-PORT,80/443)),DEFAULT
  - AND,((PROCESS-NAME,com.garena.game.codm),(NETWORK,UDP)),GAMING
  # PUBGM GAMEPLAY #
  - DOMAIN-KEYWORD,ping.igamecj.com,GAMING
  - AND,((DOMAIN-KEYWORD,.igamecj.com),(NETWORK,UDP)),GAMING
  # PUBGM GL #
  - AND,((PROCESS-NAME,com.tencent.ig),(NETWORK,UDP)),GAMING
  - AND,((PROCESS-NAME,com.tencent.ig),(DST-PORT,80/443)),DEFAULT
  # PUBGM KR #
  - AND,((PROCESS-NAME,com.pubg.krmobile),(NETWORK,UDP)),GAMING
  - AND,((PROCESS-NAME,com.pubg.krmobile),(DST-PORT,80/443)),DEFAULT
  # MLBB #
  - AND,((PROCESS-NAME,com.mobile.legends),(DST-PORT,80/443)),DEFAULT
  - AND,((PROCESS-NAME,com.mobile.legends),(NETWORK,UDP)),GAMING
  # Default #)
  - IP-CIDR,127.0.0.1/32,DIRECT,no-resolve
  - IP-CIDR6,::1/128,DIRECT,no-resolve
  - MATCH,DEFAULT
```

### Description

If using Clash, my hosts in /system/etc/hosts not loaded
Tested on Android 12
