### ISSUE TITLE
[Feature] 建议调整’proxy-groups‘下'use'字段的排序优先级

### ISSUE THREAD

**Issue by iKira** [MetaCubeX/Clash.Meta#652]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

目前‘proxy-groups'下，代理配置可以通过'use'引用外部节点，但是通过'use'引用的节点在某些情况下并不具备高优先级排序，例如：

- name: 节点策略组0
  type: select
  use:
    - 外部节点组1
  proxies:
    - 节点策略组1
    - DIRECT

实际的节点排序是：
    - 节点策略组1
    - DIRECT
    - 外部节点组1

请考虑下能否优化下这里的排序规则，让 '节点策略组0' 内的节点严格按照实际排列顺序去排列。

**Comment by xishang0128** [comment]
yaml不允许重复key,所以做不到

**Comment by iKira** [comment]
> 

我只是举个例子，实际实现时应该可以灵活调整的，例如：
```
- name: 节点策略组0
  type: select
  proxies:
    - 节点策略组1
    - "use": 外部节点组1
    - DIRECT
```
