### ISSUE TITLE
[Bug] 订阅正常的情况下频繁报错触发主动测试

### ISSUE THREAD

**Issue by Rafeal-Ma** [MetaCubeX/Clash.Meta#653]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.14.5

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
proxy-providers:
  🍚 饿饭CC:
    type: http
    url: 
    path: ./proxies/Efancc.yaml
    interval: 86400
    health-check:
      lazy: true 
      enable: true
      url: https://cp.cloudflare.com/
      interval: 3600
proxy-groups:               

  - {name: 🇭🇰 香港节点, type: url-test, tolerance: 100, filter: "香港", use: [🍚 饿饭CC]}         
  - {name: 🇸🇬 新加坡节点, type: url-test, tolerance: 100, filter: "新加坡", use: [🍚 饿饭CC]} 
  - {name: 🇨🇳 台湾节点, type: url-test, tolerance: 100, filter: "台湾", use: [🍚 饿饭CC]}   
  - {name: 🇯🇵 日本节点, type: url-test, tolerance: 100, filter: "日本", use: [🍚 饿饭CC]}
  - {name: 🇺🇸 美国节点, type: url-test, tolerance: 100, filter: "美国", use: [🍚 饿饭CC]}
  - {name: 🇬🇧 英国节点, type: url-test, tolerance: 100, filter: "英国", use: [🍚 饿饭CC]}
```

### Description

![image](https://github.com/MetaCubeX/Clash.Meta/assets/126082509/47c8b38f-d606-4da3-bcfe-2b6d2e5ace33)
![image](https://github.com/MetaCubeX/Clash.Meta/assets/126082509/a88aa667-f28c-41e8-96b2-ba46f29a4778)
在url-test或者fallback情况下都会出现如图主动测ping。并且是连续性的。
问题出现的版本在1.14.5和1.15.0的meta核心还有7.2日的alpha核心都存在这样的问题。
后来换回1.14.4版本核心后就没出现了。
