### ISSUE TITLE
[Feature] 使用两个锚点

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [MetaCubeX/Clash.Meta#655]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法找到这个功能 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 

### Description

在同一个位置使用两个锚点

```yaml
my_proxy_groups: &my_proxy_groups
  proxies: [node select,node url-test,node fallback,node load-balance ch,node load-balance rr]

use_all_providers: &use_all_providers
  use:
  - provider1
  - provider2

proxy-groups:
  - name: "main select"
    type: select
    <<: *use_all_providers
    <<: *my_proxy_groups
```
