### ISSUE TITLE
[Bug] cdn站点无法持续访问

### ISSUE THREAD

**Issue by ThermalEng** [MetaCubeX/Clash.Meta#666]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-b0e76ec

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
proxy-groups:
- name: "\U0001F680 默认节点"
  type: select
  disable-udp: false
  proxies:
  - 自动故障切换
  use:
  - clashcloud
- name: "\U0001F680 特别分流"
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - "\U0001F680 默认节点"
  - "\U0001F1FA\U0001F1F8 美国节点"
  use:
  - clashcloud
- name: "\U0001F34E 苹果服务"
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - "\U0001F680 默认节点"
  - "\U0001F680 功能节点"
- name: "\U0001F4BB 微软服务"
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - "\U0001F680 默认节点"
  - "\U0001F680 功能节点"
- name: ⓖ 谷歌国内域名
  type: select
  disable-udp: false
  proxies:
  - DIRECT
  - REJECT
  - PASS
  - "\U0001F680 默认节点"
  - "\U0001F680 特别分流"
  - "\U0001F680 功能节点"
- name: "\U0001F30D 国外媒体"
  type: select
  disable-udp: false
  proxies:
  - "\U0001F680 默认节点"
  - "\U0001F680 功能节点"
- name: "\U0001F4F2 Telegram"
  type: select
  disable-udp: false
  proxies:
  - "\U0001F680 默认节点"
  - "\U0001F680 功能节点"
- name: "\U0001F41F 漏网之鱼"
  type: select
  disable-udp: false
  proxies:
  - "\U0001F680 默认节点"
  - DIRECT
  - REJECT
- name: "\U0001F680 功能节点"
  type: select
  disable-udp: false
  proxies:
  - 自动故障切换
  use:
  - clashcloud-ss
- name: "\U0001F1FA\U0001F1F8 美国节点"
  type: select
  disable-udp: false
  use:
  - clashcloud
  filter: 美国
- name: 自动故障切换
  type: fallback
  disable-udp: false
  proxies:
  - "节点1香港 \U0001F1ED\U0001F1F0"
  - "节点2韩国 \U0001F1F0\U0001F1F7"
  - "节点3 新加坡 \U0001F1F8\U0001F1EC"
  url: https://cp.cloudflare.com/generate_204
  interval: '300'
- name: "节点1香港 \U0001F1ED\U0001F1F0"
  type: select
  disable-udp: false
  use:
  - clashcloud
  filter: 香港
- name: "节点2韩国 \U0001F1F0\U0001F1F7"
  type: select
  disable-udp: false
  use:
  - clashcloud
  filter: 韩国
- name: "节点3 新加坡 \U0001F1F8\U0001F1EC"
  type: select
  disable-udp: false
  use:
  - clashcloud
  - clashcloud-ss
  filter: 新加坡
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- "DOMAIN-SUFFIX,dns.cloudflare.com,\U0001F680 默认节点"
- "DOMAIN-SUFFIX,dns.google,\U0001F680 默认节点"
- "DOMAIN-SUFFIX,openai.com,\U0001F680 默认节点"
- "DOMAIN-SUFFIX,sentry.io,\U0001F680 特别分流"
- "DOMAIN-SUFFIX,bing.com,\U0001F680 特别分流"
- "DOMAIN-SUFFIX,clarity.ms,\U0001F680 特别分流"
- "DOMAIN-SUFFIX,bing.net,\U0001F680 特别分流"
- DOMAIN-SUFFIX,eamerica.vrdesktop.net,REJECT
- DOMAIN-SUFFIX,eeurope.vrdesktop.net,REJECT
- DOMAIN-SUFFIX,edownload.vrdesktop.net,REJECT
- GEOSITE,private,DIRECT
- GEOSITE,category-games@cn,DIRECT
- "GEOSITE,apple-cn,\U0001F34E 苹果服务"
- GEOSITE,google-cn,ⓖ 谷歌国内域名
- RULE-SET,anti_AD,REJECT
- "RULE-SET,Microsoft(By ACL4SSR),\U0001F4BB 微软服务"
- "RULE-SET,ProxyMedia,\U0001F30D 国外媒体"
- GEOSITE,cn,DIRECT
- "GEOSITE,geolocation-!cn,\U0001F680 默认节点"
- "GEOIP,TELEGRAM,\U0001F4F2 Telegram"
- "GEOIP,NETFLIX,\U0001F30D 国外媒体"
- GEOIP,CN,DIRECT
- "GEOIP,US,\U0001F1FA\U0001F1F8 美国节点"
- GEOIP,PRIVATE,DIRECT
- "MATCH,\U0001F41F 漏网之鱼"
redir-port: 7892
tproxy-port: 7895
port: 10080
socks-port: 7891
mixed-port: 7893
mode: rule
allow-lan: true
external-controller: 0.0.0.0:9090
secret: '123456'
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
ipv6: true
dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
  - 119.29.29.29
  - 61.139.2.69
  fallback:
  - https://1.1.1.1/dns-query
  - 127.0.0.1:5335
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
    - gfw
    ipcidr:
    - 240.0.0.0/4
  nameserver-policy:
    geosite:cn:
    - udp//:61.139.2.69
    - udp://223.5.5.5
    geosite:gfw:
    - udp://127.0.0.1:5335
    - https://1.1.1.1/dns-query
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
profile:
  store-selected: true
authentication:
- GoHome:R2=@Home
rule-providers:
  Microsoft(By ACL4SSR):
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/Microsoft-ACL4SSR.yaml"
    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/Ruleset/Microsoft.yaml
    interval: 604800
  ProxyMedia:
    type: http
    behavior: classical
    path: "/etc/openclash/rule_provider/ProxyMedia.yaml"
    url: https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ProxyMedia.yaml
    interval: 604800
  anti_AD:
    type: http
    behavior: domain
    path: "./rule_provider/anti_AD.yaml"
    url: https://anti-ad.net/clash.yaml
    interval: 86400
```

### Description

openclash使用meta内核，未开启绕过中国大陆，全部流量走内核。
手机在使用京东、Bilibili等采用cdn的站点app时，大约过不到10分钟，将发生页面不存在错误。使用redir和fake-ip模式均会发生这样的问题。开启绕过中国大陆，问题消失。
猜测是内核的dns缓存和mapping机制与cdn站点ip更新存在矛盾，这样的话手机clash可能也存在类似问题。建议修复。
