### ISSUE TITLE
[Bug] wireguard利用dialer-proxy选项 使CF WARP通过VPS中继失败

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [MetaCubeX/Clash.Meta#678]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta alpha-7632827 linux amd64 with go1.21rc3 Thu Jul 20 15:28:17 UTC 2023 Use tags: with_gvisor

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
- name: AWS-SGP
  type: tuic
  server: 脱敏处理
  port: 脱敏处理
  uuid: 脱敏处理
  password: 脱敏处理
  alpn: [h3]
  reduce-rtt: true
  udp-relay-mode: native
  congestion-controller: bbr
  fast-open: true
  sni: 
- name: WARP
  type: wireguard
  server: engage.cloudflareclient.com
  port: 2408
  ip: 172.16.0.2
  ipv6: 2606:4700:110:837f:a62f:69e2:63f1:341e
  private-key: 脱敏处理
  public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
  udp: true
  reserved: [0,0,0]
  dialer-proxy: "PROXY"
proxy-groups:
- name: PROXY
  type: select
  proxies:
    - AWS-SGP
- name: CF-WARP
  type: select
  proxies:
    - WARP
rules:
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,CF-WARP
```
```


### Clash log

```shell
time="2023-07-31T18:09:29.5335936+08:00" level=debug msg="[WG](WARP) Interface up requested"
time="2023-07-31T18:09:29.5335936+08:00" level=debug msg="[DNS] resolve cp.cloudflare.com from https://1.1.1.1:443/dns-query"
time="2023-07-31T18:09:29.5335936+08:00" level=debug msg="[WG](WARP) UDP bind has been updated"
time="2023-07-31T18:09:29.5335936+08:00" level=debug msg="[WG](WARP) Routine: receive incoming receive - started"
time="2023-07-31T18:09:29.5335936+08:00" level=debug msg="[WG](WARP) peer(bmXO…fgyo) - Starting"
time="2023-07-31T18:09:29.5335936+08:00" level=debug msg="[DNS] resolve engage.cloudflareclient.com from https://1.1.1.1:443/dns-query"
time="2023-07-31T18:09:29.5335936+08:00" level=debug msg="[WG](WARP) peer(bmXO…fgyo) - Routine: sequential sender - started"
time="2023-07-31T18:09:29.5335936+08:00" level=debug msg="[WG](WARP) Interface state was Down, requested Up, now Up"
time="2023-07-31T18:09:29.5335936+08:00" level=debug msg="[WG](WARP) peer(bmXO…fgyo) - Routine: sequential receiver - started"
time="2023-07-31T18:09:29.5927237+08:00" level=debug msg="[DNS] cp.cloudflare.com --> [104.16.132.229 104.16.133.229], from https://1.1.1.1:443/dns-query"
time="2023-07-31T18:09:29.5927237+08:00" level=debug msg="[WG](WARP) peer(bmXO…fgyo) - Sending handshake initiation"
time="2023-07-31T18:09:29.5973392+08:00" level=debug msg="[DNS] engage.cloudflareclient.com --> [162.159.192.1], from https://1.1.1.1:443/dns-query"
time="2023-07-31T18:09:29.5973392+08:00" level=debug msg="New TuicV5 Client at 0xc00310c468"
time="2023-07-31T18:09:30.0069803+08:00" level=debug msg="[WG](WARP) peer(bmXO…fgyo) - Received handshake response"
time="2023-07-31T18:09:30.1236525+08:00" level=debug msg="[WG](WARP) Received message with unknown type"
```

### Description

预期效果：Local→VPS→CF-Warp，没实现成功，客户端OpenClash，代理节点服务端: 官方TUIC V5，核心版本最新alpha（commits 7632827）
yacd面板有相关连接
![image](https://github.com/MetaCubeX/Clash.Meta/assets/38343280/840bef01-23a0-42c3-9adf-0f263bed5289)

**Comment by ShoukakuChuuCC** [comment]
万恶的DNS原因

remote-dns-resolve: true
dns: [ 1.1.1.1, 8.8.8.8 ]
加上后解决

**Comment by qzi** [comment]
我在想通过 dialer-proxy 中继，似乎失去了wireguard failover的能力了

**Comment by thomasTAT** [comment]
你好，手机流量下 Clash meta for andriod + WireGuard 正常连接，切换后WiFi断连，需要重启 clash 才能恢复连接，请问你有遇到过吗？https://github.com/MetaCubeX/mihomo/discussions/1810



# 完整配置信息：
```
#clash config

proxies:

- name: "SF-UK-LD"
  type: wireguard
  ip: 10.14.0.2
  private-key: dfjashdjfjkdsfhjkdshfjkdhjkfhkdjfdfhdjfhdjfhd
  peers:
    - server: uk-lon.prod.surfshark.com
      port: 51820
      public-key: iBJRXLZwXuWWrOZE1ZrAXEKMgV/z0WjG0Tks5rnWLBI=
      allowed-ips: ['0.0.0.0/0']  
  udp: true


proxy-groups:
  
  - name: "ChatGPT"
    type: select
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - SF-UK-LD

rules:
  - DOMAIN-SUFFIX,openai.com,ChatGPT
  - DOMAIN-SUFFIX,chatgpt.com,ChatGPT
  - MATCH,DIRECT


```
