### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Cloud0310** [MetaCubeX/Clash.Meta#683]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta v1.15.0 windows amd64 with go1.20.5

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
trojan:
    type: http
    url: <trojan sub>
    path: ./proxy/trojan.yaml
    interval: 86400
    health-check:
      enable: true
      interval: 600
      url: https://cp.cloudflare.com/generate_204
  shadowsocks:
    type: http
    url: <shadowsocks sub>
    path: ./proxy/ss.yaml
    interval: 86400
    health-check:
      enable: true
      interval: 600
      url: https://cp.cloudflare.com/generate_204
```

### Description

使用同节点名称不同协议的proxy-providers时，在策略组中仅有一个协议的节点，实际文件中为不同协议。
如：
<img width="1110" alt="image" src="https://github.com/MetaCubeX/Clash.Meta/assets/60375730/a1b6cfea-8901-42a2-850f-eafd4f8ce241">
<img width="1280" alt="image" src="https://github.com/MetaCubeX/Clash.Meta/assets/60375730/8ed4ac60-ee41-4b1f-b3dc-6249737ea318">
