### ISSUE TITLE
[Bug] Dokcer 里面运行clashmeta怎么打开tun模式

### ISSUE THREAD

**Issue by 2069692020** [MetaCubeX/Clash.Meta#688]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [x]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

clashmet

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7895
mixed-port: 7893
ipv6: false
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
external-ui: /home/yacd
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  listen: 0.0.0.0:7874
  nameserver:
  - 1.1.1.1
  - 114.114.114
  - 223.5.5.5
  - https://doh.pub/dns-query
  - https://223.5.5.5/dns-query
  fallback:
  - https://dns.cloudflare.com/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://jp.tiar.app/dns-query
  - https://jp.tiarap.org/dns-query
tun:
  enable: true
  stack: system # system / lwip
  dns-hijack:
    - 0.0.0.0:53
  auto-detect-interface: true
  auto-route: true
  mtu: 9000
  strict-route: true
  inet4-route-address: 
    - 0.0.0.0/1
    - 128.0.0.0/1
```

### Clash log

```shell
ERRO[2023-08-11T04:54:23.493883647Z] Start TUN listening error: configure tun int
erface: no such file or directory                                                
ERRO[2023-08-11T04:54:27.914064364Z] Start TUN listening error: configure tun int
erface: no such file or directory                                                
ERRO[2023-08-11T04:54:29.994180931Z] Start TUN listening error: configure tun int
erface: no such file or directory                                                
ERRO[2023-08-11T04:54:32.374032526Z] Start TUN listening error: configure tun int
erface: no such file or directory
```

### Description

物理机安装ubuntu直接运行clashmeta 可以开启tun模式  在docker里面运行clashmeta有报错
ERRO[2023-08-11T04:54:32.374032526Z] Start TUN listening error: configure tun int
erface: no such file or directory
