### ISSUE TITLE
规则中使用 GEOSITE:google-cn 报错

### ISSUE THREAD

**Issue by pounod** [MetaCubeX/Clash.Meta#689]
```
rules:
...
  - GEOSITE:google-cn,DIRECT
...
```

配置文件中包含"**GEOSITE:google-cn**"规则时，加载配置文件报错，提示不支持。

<img width="372" alt="geosite-ymal-clash" src="https://github.com/MetaCubeX/Clash.Meta/assets/140609704/3e038257-7873-42a2-aee0-e6c5ea915bc5">

检查 `geosite.dat` 文件，发现包含 google-cn 域名列表。

这个问题该如何解决？

**Comment by 13wenwen** [comment]
单独弄一个google中国的rule-set不就完事了。

**Comment by QIN2DIM** [comment]
多了一个冒号，改成：`- GEOSITE,google-cn,DIRECT`

**Comment by pounod** [comment]
> 多了一个冒号，改成：
> 
> ```yaml
> rules:
>   - GEOSITE,google-cn,DIRECT
> ```

感谢，确实我语法有问题，冒号改成逗号，加载不再报错了。不过有新错误日志：

127.0.0.1:59087 --> fonts.googleapis.com:443 error: dns resolve failed: couldn't find ip
2023/08/12 09:55:34.584  [info] [TCP] 127.0.0.1:59121 --> fonts.gstatic.com:443 match GeoSite(google-cn) using DIRECT

我用的这个配置模版：https://clash-meta.wiki/example/#_2
是不是配置文件还要修改完善？

**Comment by pounod** [comment]
自己尝试了下不再报错了，把 `google-cn` 加入下面的规则中：
就是不知道会不会有其它的问题。

nameserver-policy:
    "geosite:cn,google-cn,private":

**Comment by Skyxim** [comment]
@pounod 一切以文档为准，没写就是不能这样做

**Comment by pounod** [comment]
> 自己尝试了下不再报错了，把 `google-cn` 加入下面的规则中： 就是不知道会不会有其它的问题。
> 
> nameserver-policy: "geosite:cn,google-cn,private":

@Skyxim 不能这样添加是吧？那要放弃 google-cn 规则？你是如何处理的？用2楼的 rule-set ？

**Comment by QIN2DIM** [comment]
@pounod 访问这些资源全走代理就好，速度慢是你的代理不行……

其次，在正确配置 DNS 的前提下，直连访问不会报错。你没有找到 IP 可能的原因是 DNS 污染，建议使用 DOH（或h3） 或 QUIC 解析域名。

```markdown
23-08-12 21:22:03[ info ][TCP] 127.0.0.1:11835(msedge.exe) --> fonts.gstatic.com:443 match GeoSite(google-cn) using DIRECT
23-08-12 21:22:03[ info ][TCP] 127.0.0.1:11836(msedge.exe) --> fonts.gstatic.com:443 match GeoSite(google-cn) using DIRECT
23-08-12 21:22:03[ debug ][DNS] fonts.gstatic.com --> [203.208.41.34], from https://223.5.5.5:443/dns-query
23-08-12 21:22:03[ debug ][DNS] resolve fonts.gstatic.com from https://223.5.5.5:443/dns-query
```

如果你决定要直连访问，推荐使用如下配置：
在这个策略流向中，最终使用 阿里的 DOH 解析域名，可以有效避免裸连的污染和劫持。
```yaml
dns:
  enable: true
  prefer-h3: true
  nameserver:
    - https://dns.google/dns-query#PROXY
    - https://security.cloudflare-dns.com/dns-query#PROXY
    - quic://dns.adguard-dns.com
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
  nameserver-policy:
    geosite:cn:
      - https://223.5.5.5/dns-query#h3=true
rules:
  - GEOSITE,google-cn,DIRECT # For your demand
  - GEOSITE,category-scholar-!cn,PROXY
  - GEOSITE,category-ads-all,REJECT
  - GEOSITE,youtube,PROXY
  - GEOSITE,google,PROXY
  - GEOSITE,cn,DIRECT
  - GEOSITE,private,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT
  - GEOSITE,geolocation-!cn,PROXY
  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,telegram,PROXY
  - GEOIP,CN,DIRECT
  - DST-PORT,80/8080/443/8443,PROXY
  - MATCH,DIRECT
```
