### ISSUE TITLE
更新GEO数据库功能故障

### ISSUE THREAD

**Issue by pounod** [MetaCubeX/Clash.Meta#690]
由于在客户端那边反馈基本无人问津，尝试在上游反馈。
不知上游是否也存在同样的问题：每次触发GEO更新，并不能完整更新GEO数据库，包含：
geosite.dat
geoip.dat
country.mmdb

```
geodata-mode: true
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
```
https://github.com/MetaCubeX/ClashX.Meta/issues/25#issue-1848296431
