### ISSUE TITLE
[Bug] 系统代理模式，网卡流量转发不出去

### ISSUE THREAD

**Issue by james-curtis** [MetaCubeX/Clash.Meta#704]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.15.0 Meta

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
mode: rule
mixed-port: 7890
allow-lan: false
log-level: debug
ipv6: false
secret: ''
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: redir-host
  nameserver:
  - 223.5.5.5
  - 119.29.29.29
  proxy-server-nameserver:
  - https://223.5.5.5/dns-query
  - https://1.12.12.12/dns-query
sniffer:
  enable: true
  sniff:
    TLS:
      ports:
      - 443
      - 8443
    HTTP:
      ports:
      - 80
      - 8080-8880
proxies: null
proxy-groups:
- name: 默认
  type: select
  proxies:
  - 自动选择
  - 负载均衡
  - 故障转移
  - 手动选择
  - 选择机场
  - 香港
  - 台湾
  - 日本
  - 新加坡
  - 美国
  - 其它地区
  - DIRECT
- name: 自动选择
  tolerance: 10
  type: url-test
  interval: 600
  use:
  - www.eevpn.com
  - hiclouda.com
  - 慈善机场.xyz
  - cf.1air.xyz
  - www.三毛机场.shop
  - dash.fscloud.cc
  - bai.ee
  - 一元机场.com
  - 一元者也.com
- name: 手动选择
  type: select
  interval: 600
  use:
  - www.eevpn.com
  - hiclouda.com
  - 慈善机场.xyz
  - cf.1air.xyz
  - www.三毛机场.shop
  - dash.fscloud.cc
  - bai.ee
  - 一元机场.com
  - 一元者也.com
- name: 手动选择2
  type: select
  proxies:
  - 默认
  - 香港
  - 台湾
  - 日本
  - 新加坡
  - 美国
  - 其它地区
  - 手动选择
  - 自动选择
  - 负载均衡
  - 故障转移
  - DIRECT
- name: 选择机场
  type: select
  proxies:
  - www.eevpn.com
  - hiclouda.com
  - 慈善机场.xyz
  - cf.1air.xyz
  - www.三毛机场.shop
  - dash.fscloud.cc
  - bai.ee
  - 一元机场.com
  - 一元者也.com
- name: 负载均衡
  strategy: consistent-hashing
  type: load-balance
  interval: 600
  use:
  - www.eevpn.com
  - hiclouda.com
  - 慈善机场.xyz
  - cf.1air.xyz
  - www.三毛机场.shop
  - dash.fscloud.cc
  - bai.ee
  - 一元机场.com
  - 一元者也.com
- name: 故障转移
  type: fallback
  interval: 600
  use:
  - www.eevpn.com
  - hiclouda.com
  - 慈善机场.xyz
  - cf.1air.xyz
  - www.三毛机场.shop
  - dash.fscloud.cc
  - bai.ee
  - 一元机场.com
  - 一元者也.com
- name: Abroad SSH
  type: select
  proxies:
  - 默认
  - 选择机场
  - 香港
  - 台湾
  - 日本
  - 新加坡
  - 美国
  - 其它地区
  - 手动选择
  - 手动选择2
  - 自动选择
  - 负载均衡
  - 故障转移
  - DIRECT
- name: Google
  type: select
  proxies:
  - 默认
  - 选择机场
  - 香港
  - 台湾
  - 日本
  - 新加坡
  - 美国
  - 其它地区
  - 手动选择
  - 手动选择2
  - 自动选择
  - 负载均衡
  - 故障转移
  - DIRECT
- name: Scholar
  type: select
  proxies:
  - 默认
  - 选择机场
  - 香港
  - 台湾
  - 日本
  - 新加坡
  - 美国
  - 其它地区
  - 手动选择
  - 手动选择2
  - 自动选择
  - 负载均衡
  - 故障转移
  - DIRECT
- name: GitHub
  type: select
  proxies:
  - 默认
  - 选择机场
  - 香港
  - 台湾
  - 日本
  - 新加坡
  - 美国
  - 其它地区
  - 手动选择
  - 手动选择2
  - 自动选择
  - 负载均衡
  - 故障转移
  - DIRECT
- name: Apple
  type: select
  proxies:
  - DIRECT
  - 默认
  - 选择机场
  - 香港
  - 台湾
  - 日本
  - 新加坡
  - 美国
  - 其它地区
  - 手动选择
  - 手动选择2
  - 自动选择
  - 负载均衡
  - 故障转移
- name: OpenAI
  type: select
  proxies:
  - 默认
  - 选择机场
  - 香港
  - 台湾
  - 日本
  - 新加坡
  - 美国
  - 其它地区
  - 手动选择
  - 手动选择2
  - 自动选择
  - 负载均衡
  - 故障转移
  - DIRECT
- name: NETFLIX
  type: select
  proxies:
  - 默认
  - 选择机场
  - 香港
  - 台湾
  - 日本
  - 新加坡
  - 美国
  - 其它地区
  - 手动选择
  - 手动选择2
  - 自动选择
  - 负载均衡
  - 故障转移
  - DIRECT
- name: 国内
  type: select
  proxies:
  - DIRECT
  - 默认
  - 选择机场
  - 香港
  - 台湾
  - 日本
  - 新加坡
  - 美国
  - 其它地区
  - 手动选择
  - 手动选择2
  - 自动选择
  - 负载均衡
  - 故障转移
- name: 漏网之鱼
  type: select
  proxies:
  - 默认
  - 选择机场
  - 香港
  - 台湾
  - 日本
  - 新加坡
  - 美国
  - 其它地区
  - 手动选择
  - 手动选择2
  - 自动选择
  - 负载均衡
  - 故障转移
  - DIRECT
- name: 香港
  filter: (?i)港|hk|hongkong|hong kong
  type: url-test
  interval: 600
  use:
  - www.eevpn.com
  - hiclouda.com
  - 慈善机场.xyz
  - cf.1air.xyz
  - www.三毛机场.shop
  - dash.fscloud.cc
  - bai.ee
  - 一元机场.com
  - 一元者也.com
- name: 台湾
  filter: (?i)台|tw|taiwan
  type: url-test
  interval: 600
  use:
  - www.eevpn.com
  - hiclouda.com
  - 慈善机场.xyz
  - cf.1air.xyz
  - www.三毛机场.shop
  - dash.fscloud.cc
  - bai.ee
  - 一元机场.com
  - 一元者也.com
- name: 日本
  filter: (?i)日本|jp|japan
  type: url-test
  interval: 600
  use:
  - www.eevpn.com
  - hiclouda.com
  - 慈善机场.xyz
  - cf.1air.xyz
  - www.三毛机场.shop
  - dash.fscloud.cc
  - bai.ee
  - 一元机场.com
  - 一元者也.com
- name: 美国
  filter: (?i)美|us|unitedstates|united states
  type: url-test
  interval: 600
  use:
  - www.eevpn.com
  - hiclouda.com
  - 慈善机场.xyz
  - cf.1air.xyz
  - www.三毛机场.shop
  - dash.fscloud.cc
  - bai.ee
  - 一元机场.com
  - 一元者也.com
- name: 新加坡
  filter: (?i)(新|sg|singapore)
  type: url-test
  interval: 600
  use:
  - www.eevpn.com
  - hiclouda.com
  - 慈善机场.xyz
  - cf.1air.xyz
  - www.三毛机场.shop
  - dash.fscloud.cc
  - bai.ee
  - 一元机场.com
  - 一元者也.com
- name: 其它地区
  filter: (?i)^(?!.*(?:🇭🇰|🇯🇵|🇺🇸|🇸🇬|🇨🇳|港|hk|hongkong|台|tw|taiwan|日|jp|japan|新|sg|singapore|美|us|unitedstates)).*
  type: url-test
  interval: 600
  use:
  - www.eevpn.com
  - hiclouda.com
  - 慈善机场.xyz
  - cf.1air.xyz
  - www.三毛机场.shop
  - dash.fscloud.cc
  - bai.ee
  - 一元机场.com
  - 一元者也.com
- name: www.eevpn.com
  use:
  - www.eevpn.com
  type: url-test
  interval: 600
- name: hiclouda.com
  use:
  - hiclouda.com
  type: url-test
  interval: 600
- name: 慈善机场.xyz
  use:
  - 慈善机场.xyz
  type: url-test
  interval: 600
- name: cf.1air.xyz
  use:
  - cf.1air.xyz
  type: url-test
  interval: 600
- name: www.三毛机场.shop
  use:
  - www.三毛机场.shop
  type: url-test
  interval: 600
- name: dash.fscloud.cc
  use:
  - dash.fscloud.cc
  type: url-test
  interval: 600
- name: bai.ee
  use:
  - bai.ee
  type: url-test
  interval: 600
- name: 一元机场.com
  use:
  - 一元机场.com
  type: url-test
  interval: 600
- name: 一元者也.com
  use:
  - 一元者也.com
  type: url-test
  interval: 600
proxy-providers:
  一元机场.com:
    path: ./proxy-providers/一元机场.com.yaml
    url: https://sub1.smallstrawberry.com/api/v1/client/subscribe?token=
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
  dash.fscloud.cc:
    path: ./proxy-providers/dash.fscloud.cc.yaml
    url: https://sub.fscloud.cc/api/v1/client/subscribe?token=
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
  一元者也.com:
    path: ./proxy-providers/一元者也.com.yaml
    url: https://dy.v-too.cloud/api/v1/client/subscribe?token=
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
  bai.ee:
    path: ./proxy-providers/bai.ee.yaml
    url: https://dy.zzjq.xyz/api/v1/client/subscribe?token=
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
  www.eevpn.com:
    path: ./proxy-providers/www.eevpn.com.yaml
    url: https://api.ejiasu.net/api/v1/client/subscribe?token=
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
  hiclouda.com:
    path: ./proxy-providers/hiclouda.com.yaml
    url: https://subscr.b-cdn.net/api/v2/subscr?scrid=
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
  慈善机场.xyz:
    path: ./proxy-providers/慈善机场.xyz.yaml
    url: https://www.csyyds.xyz/api/v1/client/subscribe?token=
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
  www.三毛机场.shop:
    path: ./proxy-providers/www.三毛机场.shop.yaml
    url: https://dy.jimaoyun.top/api/v1/client/subscribe?token=
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
  cf.1air.xyz:
    path: ./proxy-providers/cf.1air.xyz.yaml
    url: https://1air.393636.xyz/api/v1/client/subscribe?token=&flag=clash
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 600
rules:
- RULE-SET,LocalAreaNetwork,DIRECT
- AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(GEOSITE,geolocation-!cn),REJECT
- AND,((DOMAIN-SUFFIX,github.com),(DST-PORT,22)),Abroad SSH
- GEOSITE,openai,OpenAI
- GEOSITE,github,GitHub
- GEOSITE,apple,Apple
- GEOSITE,netflix,NETFLIX
- GEOSITE,category-scholar-!cn,Scholar
- GEOSITE,geolocation-!cn,漏网之鱼
- GEOSITE,google@cn,国内
- GEOSITE,google,Google
- GEOSITE,CN,国内
- GEOIP,google,Google
- GEOIP,netflix,NETFLIX
- GEOIP,CN,国内
- DST-PORT,22,Abroad SSH
- MATCH,漏网之鱼
rule-providers:
  LocalAreaNetwork:
    type: http
    behavior: classical
    format: yaml
    path: ./rule-providers/LocalAreaNetwork.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml
    interval: 86400
```

### Description

今天重装系统，全新系统，关闭了防火墙和UAC

系统版本
![image](https://github.com/MetaCubeX/Clash.Meta/assets/49338067/9670ae91-25e8-4ac9-b580-1432fe3b977d)

抓包图片
![image](https://github.com/MetaCubeX/Clash.Meta/assets/49338067/9235b4d4-099c-47f3-aa8a-efb666087753)

日志：2023-08-27-0012 - 副本.log
[2023-08-27-0012 - 副本.log](https://github.com/MetaCubeX/Clash.Meta/files/12446027/2023-08-27-0012.-.log)
