### ISSUE TITLE
VMESS + TCP + HTTP

### ISSUE THREAD

**Issue by EbadiDev** [MetaCubeX/Clash.Meta#710]
I have reviewed all the configuration files in [docs/config.yaml](https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/docs/config.yaml), but I was unable to find any examples of VMESS over TCP with HTTP headers support.

I noticed there is a vmess-http example, however it does not seem to support custom host headers:
```yaml
  - name: "vmess-http"
    type: vmess
    server: server
    port: 443
    uuid: uuid
    alterId: 32
    cipher: auto
    # udp: true
    # network: http
    # http-opts:
    #   method: "GET"
    #   path:
    #     - '/'
    #     - '/video'
    #   headers:
    #     Connection:
    #       - keep-alive
    # ip-version: ipv4 # 设置使用 IP 类型偏好，可选：ipv4，ipv6，dual，默认值：dual
```
According to the [Xray documentation](https://xtls.github.io/Xray-docs-next/config/transports/tcp.html#httpheaderobject), VMESS over HTTP supports configuring headers like this:
```json
{
  "version": "1.1",
  "method": "GET",
  "path": ["/"],
  "headers": {
    "Host": ["www.baidu.com", "www.bing.com"],
    "User-Agent": [
      "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36",
      "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/601.1 (KHTML, like Gecko) CriOS/53.0.2785.109 Mobile/14A456 Safari/601.1.46"
    ],
    "Accept-Encoding": ["gzip, deflate"],
    "Connection": ["keep-alive"],
    "Pragma": "no-cache"
  }
}
```
I wanted to check if Clash-META supports configuring VMESS over TCP with custom HTTP headers like this example from Xray?
