### ISSUE TITLE
Windows平台拨号后启用tun模式无法上网

### ISSUE THREAD

**Issue by RimuruChan** [MetaCubeX/Clash.Meta#721]
经测试，Clash premium 平台正常，Clash-meta出现此故障。
相关配置：
```
dns:
  enable: true
  enhanced-mode: fake-ip
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
  nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 8.8.8.8
  fallback: []
tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
```
