### ISSUE TITLE
Warp的wireguard如何配置server的ipv6地址

### ISSUE THREAD

**Issue by LordHumphrey** [MetaCubeX/Clash.Meta#724]
```yaml
  - name: "WARP"
    type: wireguard
    server: '[2606:4700:d0::36a9:b92a:743f:0b34]'
    port: 5956

```
server字段已经以下方法：

1. `server: '[2606:4700:d0::36a9:b92a:743f:0b34]'`
2. `server: '2606:4700:d0::36a9:b92a:743f:0b34'`
3. `server: [2606:4700:d0::36a9:b92a:743f:0b34]`
均无法连接，另，日志等级已经调整到debug，但仍无法获取到测试节点延迟的日志。
