### ISSUE TITLE
域名嗅探针对socks代理不起作用--起作用

### ISSUE THREAD

**Issue by sunnoy** [MetaCubeX/Clash.Meta#726]
mixed-port: 9000
sniffer:
  enable: true
log-level: debug

无法嗅探域名

**Comment by xishang0128** [comment]
@sunnoy sniff只处理tun/redirect/tproxy等无法传递域名的入站

**Comment by sunnoy** [comment]
socks5也不能传递域名呢

**Comment by xishang0128** [comment]
@sunnoy socks在设计上一直都可以传递,所以不嗅探

**Comment by sunnoy** [comment]
这个决定是否嗅探的关键代码能发下么 我学习一下 本地有一个场景需要使用

**Comment by sunnoy** [comment]
实测  可探测

```yaml
mixed-port: 9000
sniffer:                           #【Meta专属】sniffer域名嗅探器
  enable: true                    # 嗅探器开关
    # 开启后对 redir-host 类型识别的流量进行强制嗅探
  # 包含 Tun、Redir 和 TProxy 或 DNS 为 redir-host
  # force-dns-mapping: false
#  parse-pure-ip: true           # 对所有未获取到域名的流量进行强制嗅探

#  override-destination: true      # 是否使用嗅探结果作为实际访问,默认 true
  # 全局配置,优先级低于 sniffer.sniff 实际配置
  sniff: # TLS 默认如果不配置 ports 默认嗅探 443
    TLS:
      ports: [443]
    HTTP: # 需要嗅探的端口, 默认嗅探 80
      ports: [80]
```
