### ISSUE TITLE
DNS 缓存未生效每次都会查询上游 DNS

### ISSUE THREAD

**Issue by lvii** [MetaCubeX/Clash.Meta#741]
Hi

clash.meta 运行在路由器上 DNS 使用的 fake-ip 模式

```
# clash -v
Clash Meta v1.15.1 linux arm64 with go1.21.0 Sun Aug 13 15:03:07 UTC 2023
Use tags: with_gvisor
```

在电脑上面使用 `curl` 请求发现每次都会使用上游 DNS 查询解析域名：

```sh
for i in {1..8}
do
    curl -sH 'accept: application/dns-json' "https://cloudflare-dns.com/dns-query?name=abc.xyz&type=A"
    echo
    sleep 0.5
done
```

`cloudflare-dns.com` 域名 **交替解析** 到下面 2 个 IP 地址 104.16.**_248_**.249 和  104.16.**_249_**.249 

``` php
23-09-09 19:36:04 debug [DNS]  cloudflare-dns.com --> 104.16.248.249
23-09-09 19:36:04 debug [DNS]  cloudflare-dns.com --> 104.16.249.249
23-09-09 19:36:04 debug [DNS]  cloudflare-dns.com --> 104.16.249.249
23-09-09 19:36:03 debug [DNS]  cloudflare-dns.com --> 104.16.248.249
23-09-09 19:36:02 debug [DNS]  cloudflare-dns.com --> 104.16.249.249
23-09-09 19:36:01 debug [DNS]  cloudflare-dns.com --> 104.16.248.249
23-09-09 19:36:00 debug [DNS]  cloudflare-dns.com --> 104.16.249.249
23-09-09 19:35:59 debug [DNS]  cloudflare-dns.com --> 104.16.248.249
23-09-09 19:35:58 debug [DNS]  cloudflare-dns.com --> 104.16.248.249
```

完整的 debug 日志：

``` php
23-09-09 19:36:04 info  [TCP]  192.168.16.199:64761 --> cloudflare-dns.com:443 match Match using PROXY[tuic-jp]
23-09-09 19:36:04 debug [DNS]  cloudflare-dns.com --> 104.16.248.249
23-09-09 19:36:04 debug [DNS]  cloudflare-dns.com --> [104.16.248.249 104.16.249.249], from udp://223.5.5.5:53
23-09-09 19:36:04 debug [DNS]  resolve cloudflare-dns.com from udp://223.5.5.5:53
23-09-09 19:36:04 debug [Rule] use default rules

23-09-09 19:36:04 info  [TCP]  192.168.16.199:64754 --> cloudflare-dns.com:443 match Match using PROXY[tuic-jp]
23-09-09 19:36:04 debug [DNS]  cloudflare-dns.com --> 104.16.249.249
23-09-09 19:36:04 debug [DNS]  cloudflare-dns.com --> [104.16.248.249 104.16.249.249], from udp://223.5.5.5:53
23-09-09 19:36:04 debug [DNS]  resolve cloudflare-dns.com from udp://223.5.5.5:53
23-09-09 19:36:04 debug [Rule] use default rules

23-09-09 19:36:04 info  [TCP]  192.168.16.199:64754 --> cloudflare-dns.com:443 match Match using PROXY[tuic-jp]
23-09-09 19:36:04 debug [DNS]  cloudflare-dns.com --> 104.16.249.249
23-09-09 19:36:04 debug [DNS]  cloudflare-dns.com --> [104.16.248.249 104.16.249.249], from udp://223.5.5.5:53
23-09-09 19:36:04 debug [DNS]  resolve cloudflare-dns.com from udp://223.5.5.5:53
23-09-09 19:36:04 debug [Rule] use default rules

23-09-09 19:36:03 info  [TCP]  192.168.16.199:64753 --> cloudflare-dns.com:443 match Match using PROXY[tuic-jp]
23-09-09 19:36:03 debug [DNS]  cloudflare-dns.com --> 104.16.248.249
23-09-09 19:36:03 debug [DNS]  cloudflare-dns.com --> [104.16.248.249 104.16.249.249], from udp://223.5.5.5:53
23-09-09 19:36:03 debug [DNS]  resolve cloudflare-dns.com from udp://223.5.5.5:53
23-09-09 19:36:03 debug [Rule] use default rules

23-09-09 19:36:02 info  [TCP]  192.168.16.199:64752 --> cloudflare-dns.com:443 match Match using PROXY[tuic-jp]
23-09-09 19:36:02 debug [DNS]  cloudflare-dns.com --> 104.16.249.249
23-09-09 19:36:02 debug [DNS]  cloudflare-dns.com --> [104.16.248.249 104.16.249.249], from udp://223.5.5.5:53
23-09-09 19:36:02 debug [DNS]  resolve cloudflare-dns.com from udp://223.5.5.5:53
23-09-09 19:36:02 debug [Rule] use default rules

23-09-09 19:36:01 info  [TCP]  192.168.16.199:64751 --> cloudflare-dns.com:443 match Match using PROXY[tuic-jp]
23-09-09 19:36:01 debug [DNS]  cloudflare-dns.com --> 104.16.248.249
23-09-09 19:36:01 debug [DNS]  cloudflare-dns.com --> [104.16.248.249 104.16.249.249], from udp://223.5.5.5:53
23-09-09 19:36:01 debug [DNS]  resolve cloudflare-dns.com from udp://223.5.5.5:53
23-09-09 19:36:01 debug [Rule] use default rules

23-09-09 19:36:00 info  [TCP]  192.168.16.199:64750 --> cloudflare-dns.com:443 match Match using PROXY[tuic-jp]
23-09-09 19:36:00 debug [DNS]  cloudflare-dns.com --> 104.16.249.249
23-09-09 19:36:00 debug [DNS]  cloudflare-dns.com --> [104.16.249.249 104.16.248.249], from udp://223.5.5.5:53
23-09-09 19:36:00 debug [DNS]  resolve cloudflare-dns.com from udp://223.5.5.5:53
23-09-09 19:36:00 debug [Rule] use default rules

23-09-09 19:35:59 info  [TCP]  192.168.16.199:64749 --> cloudflare-dns.com:443 match Match using PROXY[tuic-jp]
23-09-09 19:35:59 debug [DNS]  cloudflare-dns.com --> 104.16.248.249
23-09-09 19:35:59 debug [DNS]  cloudflare-dns.com --> [104.16.249.249 104.16.248.249], from udp://223.5.5.5:53
23-09-09 19:35:59 debug [DNS]  resolve cloudflare-dns.com from udp://223.5.5.5:53
23-09-09 19:35:59 debug [Rule] use default rules

23-09-09 19:35:58 info  [TCP]  192.168.16.199:64748 --> cloudflare-dns.com:443 match Match using PROXY[tuic-jp]
23-09-09 19:35:58 debug [DNS]  cloudflare-dns.com --> 104.16.248.249
23-09-09 19:35:58 debug [DNS]  cloudflare-dns.com --> [104.16.249.249 104.16.248.249], from udp://223.5.5.5:53
23-09-09 19:35:58 debug [DNS]  resolve cloudflare-dns.com from udp://223.5.5.5:53
23-09-09 19:35:58 debug [Rule] use default rules
```

配置文件：

``` yaml


profile:
  store-fake-ip: true
  store-selected: true

dns:
  enable: true
  listen: 0.0.0.0:1053

  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

  default-nameserver:
    - 223.5.5.5

  nameserver:
    - 223.5.5.5

  proxy-server-nameserver:
    - 223.5.5.5

  fallback:
    - 'tcp://1.1.1.1#PROXY'
    - 'tcp://8.8.8.8#PROXY'

  fallback-filter:
    geoip: true
    geoip-code: CN
    domain:
      - '+.google.com'
      - '+.youtube.com'
      - '+.facebook.com'
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32

  fake-ip-filter:
    - '*.lan'
    - 'gateway.icloud.com'
    - 'client.wns.windows.com'
    # 以下域名列表参考自 vernesong/OpenClash 项目，并由 Hackl0us 整理补充
    # === Linksys Wireless Router ===
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    # === Apple Software Update Service ===
    - 'swscan.apple.com'
    - 'mesu.apple.com'
    # === Windows 10 Connnect Detection ===
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    # === NTP Service ===
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp.*.com'
    - 'ntp.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    # === Music Service ===
    ## NetEase
    - '+.music.163.com'
    - '*.126.net'
    ## Baidu
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    ## Kugou
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    ## Kuwo
    - '*.kuwo.cn'
    ## JOOX
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    ## QQ
    - '+.y.qq.com'
    - '+.music.tc.qq.com'
    - 'aqqmusic.tc.qq.com'
    - '+.stream.qqmusic.qq.com'
    ## Xiami
    - '*.xiami.com'
    ## Migu
    - '+.music.migu.cn'
    # === Game Service ===
    ## Nintendo Switch
    - '+.srv.nintendo.net'
    ## Sony PlayStation
    - '+.stun.playstation.net'
    ## Microsoft Xbox
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    # === Other ===
    ## QQ Quick Login
    - 'localhost.ptlogin2.qq.com'
    ## Golang
    - 'proxy.golang.org'
    ## STUN Server
    - 'stun.*.*'
    - 'stun.*.*.*'
    ## Bilibili CDN
    - '*.mcdn.bilivideo.cn'

```
