### ISSUE TITLE
对代理服务器的域名进行DNS请求是十分频繁的

### ISSUE THREAD

**Issue by 0xCandy** [MetaCubeX/Clash.Meta#743]
很多机场提供的代理服务器都是域名，每次通过该服务器链接外网时都会对代理服务器的域名进行DNS请求，这种请求是通过直连的方式获取的，并且这种DNS请求非常频繁（如果经常使用代理），这种奇怪的请求也可能被被其他DNS服务器（非本机）记录下来，从而被针对。

我想能否将代理服务器的域名与IP地址记录在本地，每次使用代理服务器时，直接使用域名即可，所以每个代理服务器只需一次DNS请求即可，这样不仅能够降低延迟，还更加安全。

**Comment by ArchGuyWu** [comment]
@0xCandy 你在说啥？clash只会在连接前请求一次代理服务器域名所对应的IP，在缓存过期前会一直使用这个IP，你如果确定你的机场不怎么变IP，可以手动填hosts

**Comment by 0xCandy** [comment]
我使用wireshark对本地以太网进行抓包，发现每次使用proxy，都会对proxy-server的域名进行DNS解析，这种解析量是非常频繁的，可能会被后台记录下来。所以我想能否实现如下功能：

"proxy-server能否只进行一次DNS解析？将获取到的IP地址保存在本地，以后使用时直接在本地读取就好了。"

这样做的不仅能保护隐私（不需要大量且怪异地请求proxy-server的IP地址），还能降低延迟（直接使用proxy-server的IP地址进行连接，不需要解析，所以降低延迟）。

**Comment by 0xCandy** [comment]
> @0xCandy 你在说啥？clash只会在连接前请求一次代理服务器域名所对应的IP，在缓存过期前会一直使用这个IP，你如果确定你的机场不怎么变IP，可以手动填hosts

![image](https://github.com/MetaCubeX/Clash.Meta/assets/35843157/9e9b6cfe-30fc-4df6-a08a-d57b670ca187)

我使用的是 Meta内核 + Clash Verge（Windows版本），上图是wireshark对本地以太网抓包的结果，其中"cu3.nekov.org"就是我的代理服务器域名，可以看出有这里很多很频繁的DNS请求。

**Comment by stevejohnson7** [comment]
建议reopen，有类似问题。
clash-verge+meta内核，正在用VS写东西发现很卡，进任务管理器一看系统DNS Client服务占用大量CPU（有大量解析正在进行）
![image](https://github.com/MetaCubeX/Clash.Meta/assets/144257728/aa98500c-aee6-445e-9514-837896f2bd4d)
切换到premium内核后完全恢复正常。
再切回meta内核，DNS Client又开始大量占用CPU。

系统Windows 22H2，使用clash-verge规则模式代理，未使用TUN。
dns配置：
```yaml
dns:
  enable: true 
  enhanced-mode: fake-ip
  fake-ip-filter: 
    - "*.lan"
    # === Windows Connnect Detection ===
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    # === QQ Quick Login ===
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    # === STUN Server ===
    - 'stun.*.*'
    - 'stun.*.*.*'
  nameserver:
    - 223.5.5.5   # 阿里DNS
    - 180.76.76.76  # 百度DNS
    - 119.29.29.29  # 腾讯DNS
    - https://dns.alidns.com/dns-query  # 阿里 DoH DNS
  fallback:
    - tls://8.8.8.8:853
    - tls://8.8.4.4:853
    - tls://1.0.0.1:853
    - tls://dns.google:853
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true 
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
    domain:
      - +.google.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
```
