### ISSUE TITLE
[Bug] Openclash配置中包含xtls+reality时，meta内核启动报错

### ISSUE THREAD

**Issue by pafans** [MetaCubeX/Clash.Meta#765]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-g3a9fc39

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
- name: "2333"
    type: vless
    server: "xxxx"
    port: 443
    uuid: xxx
    udp: false
    skip-cert-verify: true
    tls: true
    client-fingerprint: "ios"
    servername: "www.icloud.com"
    network: tcp
    flow: "xtls-rprx-vision"
    reality-opts:
      public-key: "xxxx"
    ip-version: "ipv4"
    tfo: false
    smux:
      enabled: true
    protocol: smux
    max-connections: 4
    min-streams: 4
    max-streams: 0
    padding: false
    statistic: false
    only-tcp: false
```

### Clash log

```shell
github.com/Dreamacro/clash/main.go:112 +0x7b6
main.main()
	github.com/Dreamacro/clash/hub/hub.go:32 +0x45
github.com/Dreamacro/clash/hub.Parse({0x0, 0x0, 0x1466c92?})
	github.com/Dreamacro/clash/hub/executor/executor.go:57
github.com/Dreamacro/clash/hub/executor.Parse(...)
	github.com/Dreamacro/clash/hub/executor/executor.go:67 +0x3c
github.com/Dreamacro/clash/hub/executor.ParseWithPath({0x7ffe91ad0aca?, 0x1662080?})
	github.com/Dreamacro/clash/hub/executor/executor.go:72
github.com/Dreamacro/clash/hub/executor.ParseWithBytes(...)
	github.com/Dreamacro/clash/config/config.go:330 +0x36
github.com/Dreamacro/clash/config.Parse({0xc000200000?, 0x1e?, 0xc00019bd68?})
	github.com/Dreamacro/clash/config/config.go:458 +0x1f2
github.com/Dreamacro/clash/config.ParseRawConfig(0xc00019d500)
	github.com/Dreamacro/clash/config/config.go:605 +0x9fc
github.com/Dreamacro/clash/config.parseProxies(0xc00019d500)
	github.com/Dreamacro/clash/adapter/parser.go:73 +0x658
github.com/Dreamacro/clash/adapter.ParseProxy(0x1268dc0?)
	github.com/Dreamacro/clash/adapter/outbound/vless.go:557 +0x5cf
github.com/Dreamacro/clash/adapter/outbound.NewVless({{0x0, 0x0, {0x0, 0x0}, 0x0, {0xc0002ecbfc, 0x4}, {0x0, 0x0}}, {0xc0002eca60, ...}, ...})
	github.com/Dreamacro/clash/adapter/outbound/reality.go:22 +0xad
github.com/Dreamacro/clash/adapter/outbound.RealityOptions.Parse({{0xc000052e10?, 0xc00009d710?}, {0x0?, 0x4?}})
	encoding/base64/base64.go:543 +0x565
encoding/base64.(*Encoding).Decode(0xc0000b0420, {0xc0004f1770, 0x20, 0x20}, {0xc0000522d0, 0x4f, 0x50})
	encoding/base64/base64.go:375 +0x2b3
encoding/base64.(*Encoding).decodeQuantum(0xc00019a110?, {0xc0004f178e?, 0x50?, 0x0?}, {0xc0000522d0?, 0x50?, 0xc0000522d0?}, 0xc0000522d0?)
goroutine 1 [running]:
panic: runtime error: index out of range [2] with length 2
```

### Description

配置中包含xtls+reality时，启动报错，调用不存在的路径“github.com/Dreamacro/clash/adapter/outbound/reality.go”
meta内核和openclash均已升级到最新版本

**Comment by jdwchiao** [comment]
请问现在的clash meta安卓端的漏洞修复了吗，不会被植入木马了吧，还是需要如何设置这个漏洞

**Comment by iKira** [comment]
你写配置都不看文档吗？错得一塌糊涂

https://wiki.metacubex.one/config/proxies/vless/

**Comment by pafans** [comment]
> 你写配置都不看文档吗？错得一塌糊涂
> 
> https://wiki.metacubex.one/config/proxies/vless/
错误是指双引号和多余的参数么？
我在Opeclash中配置的，内容是从生成的配置文件中直接摘录出来的，而且从目前的错误来看，也不是完全和配置相关啊

**Comment by fillpit** [comment]
这是我的配置, 你可以参考一下
```
  - name: "🇸🇬 [vless-reality-vision] 新家坡-me"
    type: vless
    server: xxx
    port: xxx
    uuid: xxx
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: addons.mozilla.org
    reality-opts:
      public-key: "qhTzYYIgBzDLNYR79oxftqdo1kzL-1_hGJKfqrOliCY"
      short-id: 9ab288f7
    client-fingerprint: chrome
```
