### ISSUE TITLE
[Bug] 设置DNS的结果是无效的，请求指点

### ISSUE THREAD

**Issue by nkta3m** [MetaCubeX/Clash.Meta#772]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.16.0

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
dns:
  enable: true
  prefer-h3: true
  listen: 127.0.0.1:53
  ipv6: false
  #默认 dns, 用于解析 DNS 服务器的域名,必须为 ip, 可为加密 dns
  default-nameserver:
    - 185.228.168.10
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: "198.18.0.1/16"
    nameserver-policy:
    "geosite:cn,private,apple":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "geosite:category-ads-all": rcode://success
    "www.baidu.com,+.google.cn": [223.5.5.5, 'https://dns.alidns.com/dns-query']
  # 默认的域名解析服务器，如不配置 fallback/proxy-server-nameserver , 则所有域名都由 nameserver 解析
  nameserver:
    - 114.114.114.114 # default value
    - 185.228.168.10 # default value
  # 后备域名解析服务器，一般情况下使用境外 DNS, 保证结果可信
  # 配置 fallback后默认启用 fallback-filter,geoip-code为 cn
  fallback:
    - https://doh.cleanbrowsing.org/doh/family-filter/
  # 后备域名解析服务器筛选，满足条件的将使用 fallback 结果或只使用 fallback 解析
  fallback-filter:
    geoip: true
    geoip-code: CN
```

### Description

我指定了国外dns为185.228.168.10和https://doh.cleanbrowsing.org/doh/family-filter/，这个dns的功能是过滤成人内容，但是在搜索时，并不能过滤，如果把这个dns设为vps的dns，即使config不指定这个dns，也可以成功过滤，config的dns该如何设置？谢谢
