### ISSUE TITLE
[Bug]使用4G上网卡时，tun已检测到接口，但流量发出时却提示error: interface not found

### ISSUE THREAD

**Issue by ArchGuyWu** [MetaCubeX/Clash.Meta#774]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta alpha-0dfe696 windows amd64 with go1.21.1 Mon Sep 25 01:12:08 UTC 2023

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
tun:
  enable: true
  stack: system
  dns-hijack:
    - 127.0.0.1:53
  auto-route: true
  auto-detect-interface: true
  strict-route: true
geodata-mode: true
log-level: info
ipv6: false
dns:
  enable: true
  default-nameserver:
    - tls://223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - nameserver_addr
proxies:
  - name: tuic
    server: server_addr
    port: server_port
    type: tuic
    uuid: 00000000-0000-0000-0000-000000000000
    password: password
    alpn: [h3]
    congestion-controller: bbr
rules:
  - GEOSITE,geolocation-!cn,tuic
  - GEOIP,cn,DIRECT
  - MATCH,tuic
```

### Clash log

```shell
在下方附上日志截图
```

### Description

日志截图：
![2023-09-26_12-41](https://github.com/MetaCubeX/Clash.Meta/assets/52102426/ef87b27b-4c89-46fd-9abe-388fd81dee47)

4G上网卡接口名：
![2023-09-26_12-44](https://github.com/MetaCubeX/Clash.Meta/assets/52102426/05d3a4f8-1816-495a-b77f-25a5739de669)
![2023-09-26_12-45](https://github.com/MetaCubeX/Clash.Meta/assets/52102426/d82413e2-ceb4-4578-b9b6-6cd80b4fb752)
