### ISSUE TITLE
[Bug] strict route模式下网页加载缓慢

### ISSUE THREAD

**Issue by transformer10015** [MetaCubeX/Clash.Meta#778]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.16.0 windows amd64 with go1.21.1

### Clash config

```yaml
tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
  # strict-route: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 0.0.0.0:53
  prefer-h3: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range:  198.18.0.1/16
  fake-ip-filter:
    - '*'
    - '+.lan'
    - '+.local'
    - '+.msftconnecttest.com'
    - '+.msftnsci.com'
  default-nameserver:
    - 'tls://8.8.8.8#dns'
    - 'tls://8.8.4.4#dns'
  nameserver:
    - 223.5.5.5
    - 223.6.6.6
  fallback:
    - 'tls://8.8.8.8#dns'
    - 'tls://8.8.4.4#dns'
    - 'tls://1.1.1.1#dns'
    - 'tls://1.0.0.1#dns'
    - 'https://dns.cloudflare.com/dns-query#dns'
    - 'https://doh.dns.sb/dns-query#dns'
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
  proxy-server-nameserver:
    - 'https://223.5.5.5/dns-query?'
    - 'https://223.6.6.6/dns-query?'
```
除dns策略外全部选择direct
```


### Clash log

_No response_

### Description

开启strict route时，网页加载缓慢。利用wireshark抓包发现当刷新网页时，没有立刻发送dns请求。
