### ISSUE TITLE
[Bug] 无法使用hysteria2 encoding/hex: invalid byte: U+0068 'h'

### ISSUE THREAD

**Issue by onlyJinx** [MetaCubeX/Clash.Meta#779]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

alpha-g21fb5f7

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 10801 

mode: rule

proxies:
  - name: "hysteria2"
    type: hysteria2
    server: 10.0.0.5
    port: 443
    up: "50 Mbps"
    down: "300 Mbps"
    password: yourpassword
    sni: my.domain
    fingerprint: chrome
    alpn:
      - h3

proxy-groups:
  # select 用户自行选择节点
  - name: Proxy
    type: select
    # disable-udp: true
    proxies:
      - hysteria2

rules:
  - MATCH,DIRECT
```

### Clash log

```shell
启动失败，无log
```

### Description

当存在hysteria2时无法启动，报错如下
```
root@OpenWrt:/etc/openclash/core#
root@OpenWrt:/etc/openclash/core# ./clash_meta -f config.yaml
INFO[2023-09-28T15:14:40.589981962Z] Start initial configuration in progress
FATA[2023-09-28T15:14:40.590222106Z] Parse config error: proxy 0: encoding/hex: invalid byte: U+0068 'h'
root@OpenWrt:/etc/openclash/core# ./clash_meta -v
Clash Meta alpha-g21fb5f7 linux amd64 with go1.21.1 Wed Sep 27 20:11:11 UTC 2023
Use tags: with_gvisor
root@OpenWrt:/etc/openclash/core#
```
