### ISSUE TITLE
[Bug] mmdb格式的geoip不被读取

### ISSUE THREAD

**Issue by k3bc999** [MetaCubeX/Clash.Meta#791]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.16.0

### What OS are you seeing the problem on?

Windows, Linux

### Clash config

```yaml
mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
geodata-mode: true
geodata-loader: standard
allow-lan: true
mode: rule
log-level: info
ipv6: true
external-controller: 0.0.0.0:9999
external-ui: ./ui


iptables:
  enable: true
  inbound-interface: eth0

geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country.mmdb"


profile:
  store-selected: true
  store-fake-ip: true

dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - system
    - 114.114.114.114
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
    - https://doh.360.cn/dns-query


tun:
  enable: false
  stack: system
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-route: true
  auto-detect-interface: true

proxy-providers:

proxy-groups:

rule-providers:

rules:
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,PRIVATE,DIRECT,no-resolve
  - GEOIP,cloudflare,PROXY,no-resolve
  - GEOIP,cloudfront,PROXY,no-resolve
  - GEOIP,google,PROXY,no-resolve
  - GEOIP,telegram,PROXY,no-resolve
  - GEOIP,twitter,PROXY,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,PROXY
```

### Description

如果geodata-mode: true  geodata-loader: standard
则
![image](https://github.com/MetaCubeX/Clash.Meta/assets/27000015/bed228c5-4ffc-4e1a-8f94-20c9dea7d469)
如果geodata-mode: false 并注释#geodata-loader: standard
![image](https://github.com/MetaCubeX/Clash.Meta/assets/27000015/05cd964c-d2c3-486b-960b-716304cb03d1)

以上为armv7 armbian所现 metacube 1.124.2
在windows上同样有此问题 
![image](https://github.com/MetaCubeX/Clash.Meta/assets/27000015/cde856ff-e3ca-47bf-be1d-8f3bdf23f40f)
geoip同样为0
![image](https://github.com/MetaCubeX/Clash.Meta/assets/27000015/89e87ec7-5d08-40ed-b4b3-c248636a4609)

于windows上测试alaph问题依旧
![image](https://github.com/MetaCubeX/Clash.Meta/assets/27000015/5d7c576b-da68-4451-b1cf-67f9eb1c86ee)
![image](https://github.com/MetaCubeX/Clash.Meta/assets/27000015/6a746aa3-242b-4c79-aee3-a5053352691b)
