### ISSUE TITLE
[Bug] api dns/query all DNS requests failed, first error: interface not found

### ISSUE THREAD

**Issue by 0jinxing** [MetaCubeX/Clash.Meta#793]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [x]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta alpha-1292830 darwin amd64 with go1.21.2 Wed Oct 11 14:55:00 UTC 2023 Use tags: with_gvisor

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
pr:
  &pr { type: select, proxies: [SELF-HOSTED, SUBSCRIBED, AUTO, DIRECT, REJECT] }

p:
  &p {
    type: http,
    interval: 3600,
    health-check:
      {
        enable: true,
        url: https://www.gstatic.com/generate_204,
        interval: 300,
      },
  }

use: &use
  type: select
  use:
    - "provider@ones.gq"

proxy-providers:
  "provider@ones.gq":
    <<: *p
    url: "http://provider@ones.gq"

mode: rule
log-level: info
allow-lan: false
mixed-port: 7890
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090

geodata-mode: true
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
tun:
  enable: true
  stack: system
  dns-hijack:
    - 'any:53'
  auto-route: true
  auto-detect-interface: true
  
dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - "tls://8.8.4.4#dns"
    - "tls://1.0.0.1#dns"
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query

proxies:
  - {
      "name": "SELF-HOSTED",
      "type": "vless",
      "server": "server",
      "port": port,
      "udp": true,
      "uuid": "uuid",
      "tls": true,
      "servername": "swdist.apple.com",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "reality-opts":
        {
          "public-key": "public-key",
          "short-id": "short-id",
        },
      "client-fingerprint": "chrome",
    }

proxy-groups:
  - { name: 🇨🇳国内, type: select, proxies: [DIRECT] }
  - { name: 🏳️‍🌈外网, <<: *pr }
  - { name: 🏴‍☠️流媒体, <<: *pr }
  - { name: SUBSCRIBED, <<: *use }
  - { name: AUTO, <<: *use, tolerance: 2, type: url-test }

rules:
  - GEOSITE,CN,🇨🇳国内
  - GEOIP,CN,🇨🇳国内
  - GEOSITE,!CN,🏳️‍🌈外网
  - GEOIP,!CN,🏳️‍🌈外网
  - GEOSITE,netflix,🏴‍☠️流媒体
  - GEOSITE,youtube,🏴‍☠️流媒体
  - GEOSITE,disney,🏴‍☠️流媒体
```

### Clash log

```shell
all DNS requests failed, first error: interface not found
```

### Description

<img width="848" alt="截屏2023-10-14 21 51 41" src="https://github.com/MetaCubeX/Clash.Meta/assets/32119282/18288f93-9c9e-4290-acd9-56892e8b12a8">
