### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by jashok4** [MetaCubeX/Clash.Meta#798]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.16.0 darwin amd64 with go1.21.1

### What OS are you seeing the problem on?

macOS

### Clash config

```yaml
mode: rule
mixed-port: 7890
allow-lan: true
log-level: debug
secret: ''
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: :1053
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
  - '*'
  - +.lan
  - +.local
  default-nameserver:
  - 223.5.5.5
  nameserver:
  - tls://8.8.4.4#dns
  - tls://1.0.0.1#dns
  proxy-server-nameserver:
  - https://doh.pub/dns-query
  nameserver-policy:
    geosite:cn,private:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
tun:
  enable: false
  stack: system
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
proxies:
- name: PROXY-HK
  type: vless
  server: ***
  port: ***
  uuid: ***
  servername: ***
  network: tcp
  tls: true
  reality-opts:
    public-key: ***
    short-id: ***
  client-fingerprint: randomized
  flow: xtls-rprx-vision
- name: PROXY-US
  type: vless
  server: ***
  port: 8443
  uuid: ***
  servername: ***
  network: tcp
  tls: true
  reality-opts:
    public-key: ***
  client-fingerprint: randomized
  flow: xtls-rprx-vision
- name: PROXY-JP
  type: vless
  server: ***
  port: 8443
  uuid: ***
  servername: ***
  network: tcp
  tls: true
  reality-opts:
    public-key: ***
  client-fingerprint: randomized
  flow: xtls-rprx-vision
rules:
- DOMAIN-SUFFIX,bilibili.com,DIRECT,tcp
- DOMAIN-SUFFIX,openai.com,PROXY-US
- DOMAIN-SUFFIX,bing.com,PROXY-JP
- DOMAIN-SUFFIX,github.com,PROXY-HK
- DOMAIN-SUFFIX,google.com,PROXY-HK
- DST-PORT,123/136/137-139,DIRECT,udp
- GEOSITE,category-ads-all,REJECT
- GEOSITE,icloud@cn,DIRECT
- GEOSITE,apple@cn,DIRECT
- GEOSITE,apple-cn,DIRECT
- GEOSITE,microsoft@cn,DIRECT
- GEOSITE,facebook,PROXY-HK
- GEOSITE,youtube,PROXY-HK
- GEOSITE,geolocation-cn,DIRECT
- GEOSITE,geolocation-!cn,PROXY-HK
- GEOIP,telegram,PROXY-HK,no-resolve
- GEOIP,private,DIRECT,no-resolve
- GEOIP,cn,DIRECT
- MATCH,PROXY-HK
```

### Description

原 Clash Premium核心提供的API： /connections  获取连接信息的API，所返回的数据字段中可以正确返回processPath（进程路径）信息，ClashMeta似乎不能正确返回该字段信息。
