### ISSUE TITLE
[Bug] 使用 proxy-providers 在更新节点信息时接口 503

### ISSUE THREAD

**Issue by QuentinHsu** [MetaCubeX/Clash.Meta#815]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

1.16.0

### What OS are you seeing the problem on?

Linux

### Clash config

```yaml
mixed-port: 7890
mode: rule
log-level: info

proxy-providers:
  # 全部节点
  subs: &subs
    type: http
    interval: 86400
    url: http://192.168.100.2:3000/download/collection/subs?target=Clash
    path: ./proxy-providers/subs.yml
    health-check:
      enable: true
      interval: 600
      url: https://captive.apple.com

proxies:

proxy-groups:
  - name: Outbound Policy
    type: select

    proxies:
      - Auto Select
      - Manual Select
      - Fallback
      - Country
      - DIRECT

  - name: Global Proxy
    type: select
    proxies:
      - Outbound Policy
      - DIRECT

  - name: Global Direct
    type: select
    proxies: &global-direct
      - DIRECT
      - Outbound Policy

  - name: Final
    type: select
    proxies: *global-direct

  - name: Apple
    type: select
    proxies: *global-direct

  - name: Microsoft
    type: select
    proxies: *global-direct

  - name: Duolingo
    type: select
    proxies:
      - Hong Kong
      - Auto Hong Kong
      - Fallback Hong Kong
      - DIRECT
    use:
      - subs
    filter: 港|🇭🇰|HK|Hong Kong

  - name: Speedtest
    type: select
    proxies: *global-direct

  - name: Discord
    type: select
    proxies:
      - Auto Hong Kong
      - Fallback Hong Kong
      - DIRECT
    use:
      - subs
    filter: 港|🇭🇰|HK|Hong Kong

  - name: Steam
    type: select
    proxies:
      - Auto Hong Kong
      - Fallback Hong Kong
      - DIRECT
    use:
      - subs
    filter: 港|🇭🇰|HK|Hong Kong

  - name: AD Block
    type: select
    proxies:
      - REJECT
      - DIRECT

  - name: Privacy
    type: select
    proxies:
      - REJECT
      - DIRECT

  - name: Server Policy
    type: select
    proxies:
      - Auto Select
      - Manual Select
      - Fallback
      - Country

  - name: Manual Select
    type: select
    use:
      - subs

  - name: Auto Select
    type: url-test
    url: https://captive.apple.com
    interval: 300
    use:
      - subs

  - name: Fallback
    type: fallback
    url: https://captive.apple.com
    interval: 300
    use:
      - subs

  - name: Country
    type: select
    proxies: &Country
      - Hong Kong
      - Japan
      - Tai Wan
      - America
      - Other Country

  - name: Hong Kong
    type: select
    use:
      - subs
    filter: 港|🇭🇰|HK|Hong Kong

  - name: Auto Hong Kong
    type: url-test
    url: https://captive.apple.com
    interval: 300
    use:
      - subs
    filter: 港|🇭🇰|HK|Hong Kong

  - name: Fallback Hong Kong
    type: fallback
    url: https://captive.apple.com
    use:
      - subs
    filter: 港|🇭🇰|HK|Hong Kong

  - name: Japan
    type: select
    use:
      - subs
    filter: 日|🇯🇵|东京|JP|Japan

  - name: Tai Wan
    type: select
    use:
      - subs
    filter: 台|🇨🇳|🇹🇼|湾|TW|Taiwan

  - name: America
    type: select
    use:
      - subs
    filter: 美国|美|🇺🇲|US|American

  - name: Other Country
    type: select
    use:
      - subs
    filter: ^(?!.*(香港|港|🇭🇰|HK|Hong Kong|日本|日|🇯🇵|JP|Japan|台湾|台|🇹🇼|TW|Taiwan|美国|美|🇺🇲|US|American|CN)).*

rule-providers:
  privacy:
    type: http
    interval: 86400
    behavior: classical
    url: https://ghproxy.com/https://github.com/QuentinHsu/network-rules/blob/release/Clash/DivineEngine-Privacy.yaml?raw=true
    path: ./ruleset/privacy.yaml

  ad-block:
    type: http
    interval: 86400
    behavior: classical
    url: https://ghproxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Advertising/Advertising_Classical.yaml?raw=true
    path: ./ruleset/ad.yaml

  youtube:
    type: http
    interval: 86400
    behavior: classical
    url: https://ghproxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/YouTube/YouTube.yaml?raw=true
    path: ./ruleset/youtube.yaml

  google:
    type: http
    interval: 86400
    behavior: classical
    url: https://ghproxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Google/Google.yaml?raw=true
    path: ./ruleset/google.yaml

  github:
    type: http
    interval: 86400
    behavior: classical
    url: https://ghproxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/GitHub/GitHub.yaml?raw=true
    path: ./ruleset/github.yaml

  twitter:
    type: http
    interval: 86400
    behavior: classical
    url: https://ghproxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Twitter/Twitter.yaml?raw=true
    path: ./ruleset/twitter.yaml
  telegram:
    type: http
    interval: 86400
    behavior: classical
    url: https://ghproxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Telegram/Telegram.yaml?raw=true
    path: ./ruleset/telegram.yaml

  apple:
    type: http
    interval: 86400
    behavior: classical
    url: https://ghproxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Apple/Apple.yaml?raw=true
    path: ./ruleset/apple.yaml

  microsoft:
    type: http
    interval: 86400
    behavior: classical
    url: https://ghproxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Microsoft/Microsoft.yaml?raw=true
    path: ./ruleset/microsoft.yaml

  speedtest:
    type: http
    interval: 86400
    behavior: classical
    url: https://ghproxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Speedtest/Speedtest.yaml?raw=true
    path: ./ruleset/speedtest.yaml

  discord:
    type: http
    interval: 86400
    behavior: classical
    url: https://ghproxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Discord/Discord.yaml?raw=true
    path: ./ruleset/discord.yaml

  steam:
    type: http
    interval: 86400
    behavior: classical
    url: https://ghproxy.com/https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Steam/Steam.yaml?raw=true
    path: ./ruleset/steam.yaml

  global-proxy:
    type: http
    interval: 86400
    behavior: classical
    url: https://ghproxy.com/https://github.com/QuentinHsu/network-rules/blob/release/Clash/ACL4SSR-Proxy.yaml?raw=true
    path: ./ruleset/global-proxy.yaml

rules:
  # ################ Local Rule
  - DOMAIN-SUFFIX,vercel.app,Global Proxy
  - DOMAIN-KEYWORD,duolingo,Duolingo
  # ################ Remote Rule
  - RULE-SET,ad-block,AD Block
  - RULE-SET,privacy,Privacy
  - RULE-SET,apple,Apple
  - RULE-SET,microsoft,Microsoft
  - RULE-SET,speedtest,Speedtest
  - RULE-SET,discord,Discord
  - RULE-SET,steam,Steam
  - RULE-SET,github,Global Proxy
  - RULE-SET,telegram,Global Proxy
  - RULE-SET,twitter,Global Proxy
  - RULE-SET,youtube,Global Proxy
  - RULE-SET,google,Global Proxy
  - RULE-SET,global-proxy,Global Proxy
  - GEOIP,CN,Global Direct
  - MATCH,Final
```

### Clash log

```shell
debug 模式在面板上完全看不到
```

### Description

是使用的 shellClash 跑 Meta。

同配置下，P 核无该问题。

![CleanShot 2023-10-22 at 22 47 10@2x](https://github.com/MetaCubeX/Clash.Meta/assets/21162238/60a572f8-6ca0-4d9c-ae69-fa78e28ad05e)
