### ISSUE TITLE
nameserver dns still using dns server

### ISSUE THREAD

**Issue by adiprasetya** [MetaCubeX/Clash.Meta#821]
just asking why when using custom dns like:
``` yaml
dns:
  ...
  nameserver:
    - tls://1.1.1.1
    - https://1.1.1.1/dns-query
```
it's should using `cloudflare dns` right? why is it still using dns server configuration? like if i using `digitalocean` server and using `built-in dns` server configuration, it's still using `digitalocean dns`. not the `cloudflare dns`. it should using client configuration, like sing-box do. tell me the reason, i'm not chinese so i don't know.

is it possible to using client dns configuration? any help?
