### ISSUE TITLE
[Bug] ipv6经常断连

### ISSUE THREAD

**Issue by XboxSoldier** [MetaCubeX/Clash.Meta#838]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

v1.16.0

### Clash config

```yaml
allow-lan: true
external-controller: 127.0.0.1:9090
global-client-fingerprint: ios
ipv6: true
log-level: info
mixed-port: 7890
mode: rule
profile:
  store-selected: true
  store-fake-ip: true
tcp-concurrent: true
unified-delay: true

dns:
  default-nameserver:
    - https://[2606:4700:4700::1111]/dns-query#proxy
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - +.*
  ipv6: true
  listen: 0.0.0.0:53
  nameserver:
    - https://<my doh>/dns-query#proxy
  use-hosts: true

hosts:
  '<my domain>': <my ipv6 address>

proxies:
  - client-fingerprint: ios
    flow: xtls-rprx-vision-udp443
    name: com-6
    network: tcp
    port: 443
    server: <my domain>
    servername: <my domain>
    reality-opts:
      public-key: 
    tls: true
    type: vless
    udp: true
    uuid:

proxy-groups:
  - name: proxy
    proxies:
      - com-6
    type: select

rules:
  - PROCESS-NAME,xray.exe,DIRECT
  - PROCESS-NAME,wxray.exe,DIRECT
  - GEOIP,private,DIRECT
  - IP-CIDR,0.0.0.0/8,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT
  - IP-CIDR,100.64.0.0/10,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT
  - IP-CIDR,169.254.0.0/16,DIRECT
  - IP-CIDR,172.16.0.0/12,DIRECT
  - IP-CIDR,192.0.0.0/24,DIRECT
  - IP-CIDR,192.88.99.0/24,DIRECT
  - IP-CIDR,192.168.0.0/16,DIRECT
  - IP-CIDR,198.18.0.0/15,DIRECT
  - IP-CIDR,198.51.100.0/24,DIRECT
  - IP-CIDR,203.0.113.0/24,DIRECT
  - IP-CIDR,224.0.0.0/4,DIRECT
  - IP-CIDR,233.252.0.0/24,DIRECT
  - IP-CIDR,240.0.0.0/4,DIRECT
  - IP-CIDR,255.255.255.255/32,DIRECT
  - IP-CIDR6,::/128,DIRECT
  - IP-CIDR6,::1/128,DIRECT
  - IP-CIDR6,::ffff:0:0/96,DIRECT
  - IP-CIDR6,100::/64,DIRECT
  - IP-CIDR6,64:ff9b::/96,DIRECT
  - IP-CIDR6,2001::/32,DIRECT
  - IP-CIDR6,2001:10::/28,DIRECT
  - IP-CIDR6,2001:20::/28,DIRECT
  - IP-CIDR6,2001:db8::/32,DIRECT
  - IP-CIDR6,2002::/16,DIRECT
  - IP-CIDR6,fc00::/7,DIRECT
  - IP-CIDR6,fe80::/10,DIRECT
  - IP-CIDR6,ff00::/8,DIRECT
  - MATCH,proxy

sniffer:
  enable: false

tun:
  auto-detect-interface: true
  auto-route: true
  dns-hijack:
    - any:53
  enable: true
  stack: system
  strict-route: true
```

### Clash log

```shell
time="2023-10-31T17:58:51.7719327+08:00" level=info msg="Start initial configuration in progress"
time="2023-10-31T17:58:51.7833455+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2023-10-31T17:58:51.7864464+08:00" level=info msg="Initial configuration complete, total time: 3ms"
time="2023-10-31T17:58:51.7864464+08:00" level=info msg="Sniffer is closed"
time="2023-10-31T17:58:51.7869564+08:00" level=info msg="RESTful API listening at: 127.0.0.1:9400"
time="2023-10-31T17:58:51.7874696+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2023-10-31T17:58:51.7874696+08:00" level=info msg="Start initial compatible provider default"
time="2023-10-31T17:58:51.9986632+08:00" level=info msg="Start initial configuration in progress"
time="2023-10-31T17:58:51.9991675+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2023-10-31T17:58:51.9991675+08:00" level=warning msg="To use xtls-rprx-vision, ensure your server is upgrade to Xray-core v1.8.0+"
time="2023-10-31T17:58:51.9991675+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2023-10-31T17:58:52.0021687+08:00" level=info msg="Initial configuration complete, total time: 3ms"
time="2023-10-31T17:58:52.0021687+08:00" level=info msg="Sniffer is closed"
time="2023-10-31T17:58:52.0021687+08:00" level=info msg="Use tcp concurrent"
time="2023-10-31T17:58:52.0026714+08:00" level=info msg="DNS server listening at: [::]:53"
time="2023-10-31T17:58:52.0048844+08:00" level=warning msg="[TUN] default interface changed by monitor,  => Ethernet"
time="2023-10-31T17:58:52.1465906+08:00" level=info msg="[TUN] Tun adapter listening at: Meta([198.18.0.1/30],[fdfe:dcba:9876::1/126]), mtu: 9000, auto route: true, ip stack: System"
time="2023-10-31T17:58:52.1465906+08:00" level=info msg="Start initial compatible provider proxy"
time="2023-10-31T17:58:52.1532795+08:00" level=info msg="Start initial compatible provider default"
time="2023-10-31T17:58:52.5442268+08:00" level=info msg="[TCP] 198.18.0.1:9530(avp.exe) --> 119.255.133.12:443 match Match using proxy[com-6]"
time="2023-10-31T17:58:52.6455675+08:00" level=info msg="[TCP] 198.18.0.1:9532(avp.exe) --> dc1.ksn.kaspersky-labs.com:443 match Match using proxy[com-6]"
time="2023-10-31T17:58:52.8174269+08:00" level=info msg="[TCP] 198.18.0.1:9535(svchost.exe) --> detectportal.firefox.com:80 match Match using proxy[com-6]"
time="2023-10-31T17:58:53.0375591+08:00" level=info msg="[TCP] 198.18.0.1:9538(OneDrive.exe) --> skydrive.wns.windows.com:443 match Match using proxy[com-6]"
time="2023-10-31T17:58:53.0836014+08:00" level=info msg="[TCP] 198.18.0.1:9541 --> dc1.ksn.kaspersky-labs.com:443 match Match using proxy[com-6]"
...
time="2023-10-31T17:59:52.0673146+08:00" level=info msg="[TCP] 198.18.0.1:9820(WerFault.exe) --> watson.events.data.microsoft.com:443 match Match using proxy[com-6]"
time="2023-10-31T17:59:52.1373105+08:00" level=info msg="[TCP] 198.18.0.1:9822(Battle.net.exe) --> kr.actual.battle.net:1119 match Match using proxy[com-6]"
time="2023-10-31T17:59:59.5515286+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9827(WerFault.exe) --> watson.events.data.microsoft.com:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:02.3195799+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9832 --> s01.upd.kaspersky.com:80 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:04.8905726+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9837(wermgr.exe) --> watson.events.data.microsoft.com:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:05.87877+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9839(WerFault.exe) --> watson.events.data.microsoft.com:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:06.9996283+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9841(avp.exe) --> 180.87.4.189:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:11.2331115+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9850(wermgr.exe) --> watson.events.data.microsoft.com:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:11.7451417+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9852(OneDrive.exe) --> self.events.data.microsoft.com:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:12.0100407+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9854(avp.exe) --> 119.255.133.16:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:12.164043+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9856(WerFault.exe) --> watson.events.data.microsoft.com:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:13.147738+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9858(explorer.exe) --> assets.msn.com:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:13.3514874+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9860 --> s01.upd.kaspersky.com:80 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:15.5755977+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9866(firefox.exe) --> alive.github.com:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:16.3114446+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9870(wermgr.exe) --> watson.events.data.microsoft.com:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:17.0273927+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9877(avp.exe) --> 119.255.133.14:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:18.4421468+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9881(WerFault.exe) --> watson.events.data.microsoft.com:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
time="2023-10-31T18:00:19.8429631+08:00" level=warning msg="[TCP] dial proxy (match Match/) 198.18.0.1:9886(avp.exe) --> 119.255.133.14:443 error: <my domain>:443 connect error: dial tcp [<my ipv6 address>]:443: i/o timeout"
```

### Description

我想用tun模式，让所有流量走ipv6代理，从而规避校园网的认证和计费。在笔记本上，这套配置没有问题；但是在台式机运行时，只能正常连接不到一分钟，接着网络中断，log里面所有连接显示“i/o timeout”。
我尝试用笔记本连接同一个无线网络，一切正常；然后我怀疑是外接无线网卡的问题，改有线连接以后，问题照旧。
换用proxifier，不存在断连，但是不能代理udp流量，因此还是不如clash的tun好用。
请问这个问题有人遇到过吗？可能是什么原因导致的？怎么才能解决呢？
