### ISSUE TITLE
[Bug] "www.youtube.com" DNS结果为127.0.0.1，导致无法连接

### ISSUE THREAD

**Issue by silicer** [MetaCubeX/Clash.Meta#844]
### Verify steps

- [X]  确保你使用的是**本仓库**最新的的 clash 或 clash Alpha 版本 Ensure you are using the latest version of Clash or Clash Premium from **this repository**. 
- [ ]  如果你可以自己 debug 并解决的话，提交 PR 吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的问题 I have searched on the [issue tracker](……/) for a related issue. 
- [X]  我已经使用 Alpha 分支版本测试过，问题依旧存在 I have tested using the dev branch, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://wiki.metacubex.one/) 并无法自行解决问题 I have read the [documentation](https://wiki.metacubex.one/) and was unable to solve the issue. 
- [X]  这是 Clash 核心的问题，并非我所使用的 Clash 衍生版本（如 OpenClash、KoolClash 等）的特定问题 This is an issue of the Clash core *per se*, not to the derivatives of Clash, like OpenClash or KoolClash. 

### Clash version

Clash Meta v1.16.0 windows amd64 with go1.21.1 Mon Sep 25 11:37:53 UTC 2023 Use tags: with_gvisor

### What OS are you seeing the problem on?

Windows

### Clash config

```yaml
dns:
  enable: true
  ipv6: true
  enhanced-mode: redir-host
  listen: 127.0.0.1:1053
  nameserver:    
    # 阿里 DNS
    - "[2400:3200::1]:53"
    - 223.5.5.5
  default-nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - 223.5.5.5
  fallback:
    - "udp://1.1.1.1#节点选择"
    - "udp://8.8.8.8#节点选择"
    - "tls://1.0.0.1"
    - "tls://1.1.1.1"
    - "https://dns.google/dns-query#节点选择"
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - bing
      - "geolocation-!cn"
      - gfw
    domain:
      - "services.googleapis.cn"
  nameserver-policy:
    "dl.google.com": ["223.5.5.5"]
    "+.google.cn": ["223.5.5.5"]
```

### Description

使用 1.16.0 以及 alpha 无法访问 youtube，发现其 destination ip 为 127.0.0.1 ，通过 1053 查询 DNS 记录发现结果也为 127.0.0.1 。目前仅发现 "www.youtube.com" 有此现象。"youtube.com" 则一切正常。
1.15.1 一切正常。
