### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ag2s20150909** [MetaCubeX/Clash.Meta#87]
```

goroutine 1199 [running]:
github.com/Dreamacro/clash/dns.dialContextExtra({0x1ad99c8, 0xc000acb9e0}, {0xc00020a162, 0x3}, {0x19606b7, 0x3}, {{0xc0002d46c0?, 0xc0002d46c0?}, 0xc000004078?}, {0xc0006080c8, ...}, ...)
        github.com/Dreamacro/clash/dns/util.go:186 +0x4da
github.com/Dreamacro/clash/dns.(*client).ExchangeContext(0xc0002047d0, {0x1ad99c8, 0xc000acb9e0}, 0xc0008de630)
        github.com/Dreamacro/clash/dns/client.go:59 +0x591
github.com/Dreamacro/clash/dns.(*Resolver).batchExchange.func1()
        github.com/Dreamacro/clash/dns/resolver.go:210 +0x35
github.com/Dreamacro/clash/common/picker.(*Picker[...]).Go.func1()
        github.com/Dreamacro/clash/common/picker/picker.go:67 +0x87
created by github.com/Dreamacro/clash/common/picker.(*Picker[...]).Go
        github.com/Dreamacro/clash/common/picker/picker.go:64 +0x98
```

**Comment by Skyxim** [comment]
@ag2s20150909 dns配置贴出来

**Comment by ag2s20150909** [comment]
```yaml
#DNS
dns:
  enable: true
  use-hosts: true
  ipv6: true
  enhanced-mode: fake-ip #fake-ip or redir-host
  fake-ip-range: 198.18.0.1/16
  listen: 127.0.0.1:6868
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
  nameserver:
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
    - tls://223.5.5.5:853
    - quic://c.passcloud.xyz:784
    - quic://x.passcloud.xyz:784
    - quic://b.iqiq.io:784
    - quic://h.iqiq.io:784
    - quic://j.iqiq.io:784
  fallback:
    - quic://i.passcloud.xyz:784
    - quic://a.passcloud.xyz:784
    - quic://c.passcloud.xyz:784
    - quic://x.passcloud.xyz:784
    - quic://b.iqiq.io:784
    - quic://h.iqiq.io:784
    - quic://j.iqiq.io:784
    - tls://j.iqiq.io:853
    - tls://c.passcloud.xyz:853
    - tls://x.passcloud.xyz:853
    - https://1.0.0.1/dns-query
    - tls://8.8.4.4:853
  proxy-server-nameserver:
    - quic://i.passcloud.xyz:784
    - quic://a.passcloud.xyz:784

  fallback-filter:
    geoip: true
    geosite:
    - gfw
    domain:
    - +.example.com
    - +.google.com
    ipcidr:
    - 0.0.0.0/32
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - "time.*.com"
    - "time.*.gov"
    - "time.*.edu.cn"
    - "time.*.apple.com"
    - "time1.*.com"
    - "time2.*.com"
    - "time3.*.com"
    - "time4.*.com"
    - "time5.*.com"
    - "time6.*.com"
    - "time7.*.com"
    - "ntp.*.com"
    - "ntp1.*.com"
    - "ntp2.*.com"
    - "ntp3.*.com"
    - "ntp4.*.com"
    - "ntp5.*.com"
    - "ntp6.*.com"
    - "ntp7.*.com"
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - "time1.cloud.tencent.com"
    - "music.163.com"
    - "*.music.163.com"
    - "*.126.net"
    - "musicapi.taihe.com"
    - "music.taihe.com"
    - "songsearch.kugou.com"
    - "trackercdn.kugou.com"
    - "*.kuwo.cn"
    - "api-jooxtt.sanook.com"
    - "api.joox.com"
    - "joox.com"
    - "y.qq.com"
    - "*.y.qq.com"
    - "+.jd.com"
    - "streamoc.music.tc.qq.com"
    - "mobileoc.music.tc.qq.com"
    - "isure.stream.qqmusic.qq.com"
    - "dl.stream.qqmusic.qq.com"
    - "aqqmusic.tc.qq.com"
    - "amobile.music.tc.qq.com"
    - "*.xiami.com"
    - "*.music.migu.cn"
    - "music.migu.cn"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - "msftconnecttest.com"
    - "msftncsi.com"
    - "localhost.ptlogin2.qq.com"
    - "localhost.sec.qq.com"
    - "+.srv.nintendo.net"
    - "+.stun.playstation.net"
    - "xbox.*.microsoft.com"
    - "xnotify.xboxlive.com"
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - "proxy.golang.org"
    - "stun.*.*"
    - "stun.*.*.*"
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "heartbeat.belkin.com"
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - "mesu.apple.com"
    - "swscan.apple.com"
    - "swquery.apple.com"
    - "swdownload.apple.com"
    - "swcdn.apple.com"
    - "swdist.apple.com"
    - "lens.l.google.com"
    - "stun.l.google.com"
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.mcdn.bilivideo.cn"
```
