### ISSUE TITLE
ProxyProvider被filter之后的urltest还有效吗

### ISSUE THREAD

**Issue by bash99** [MetaCubeX/Clash.Meta#92]
配置
```
proxy-providers:
  meta:
  type: http
  url: url
  health-check:
      enable: true
      interval: 86400
      url: http://www.gstatic.com/generate_204
......
- name: ♻️ 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    use:
      - meta
    filter: "trojan" 
```

能否实现 filter之后的代理按300秒测一次速，整个meta中的所有代理86400秒测一次？

另外
如果proxy-provider的配置中       enable: true 换成      enable: false
下面的测速就无效了，永远不会促发。
